package cs.system.data.common;

/** Automatically generates single-table commands used to reconcile changes made to a  with the associated database. This is an abstract class that can only be inherited. */
@:native("System.Data.Common.DbCommandBuilder")
extern class DbCommandBuilder extends cs.system.componentmodel.Component {
	/**
	 * Sets or gets the  for an instance of the  class.
	 * @return A  object.
	 */
	var CatalogLocation(default, default):cs.system.data.common.CatalogLocation;
	/**
	 * Sets or gets a string used as the catalog separator for an instance of the 
	 * class.
	 * @return A string indicating the catalog separator for use with an instance of
	 * the  class.
	 */
	var CatalogSeparator(default, default):String;
	/**
	 * Specifies which  is to be used by the .
	 * @return Returns one of the  values describing the behavior of this .
	 */
	var ConflictOption(default, default):cs.system.data.ConflictOption;
	/**
	 * Gets or sets a  object for which Transact-SQL statements are automatically
	 * generated.
	 * @return A  object.
	 */
	var DataAdapter(default, default):cs.system.data.common.DbDataAdapter;
	/**
	 * Gets or sets the beginning character or characters to use when specifying
	 * database objects (for example, tables or columns) whose names contain characters
	 * such as spaces or reserved tokens.
	 * @return The beginning character or characters to use. The default is an empty
	 * string.
	 */
	var QuotePrefix(default, default):String;
	/**
	 * Gets or sets the ending character or characters to use when specifying database
	 * objects (for example, tables or columns) whose names contain characters such as
	 * spaces or reserved tokens.
	 * @return The ending character or characters to use. The default is an empty
	 * string.
	 */
	var QuoteSuffix(default, default):String;
	/**
	 * Gets or sets the character to be used for the separator between the schema
	 * identifier and any other identifiers.
	 * @return The character to be used as the schema separator.
	 */
	var SchemaSeparator(default, default):String;
	/**
	 * Specifies whether all column values in an update statement are included or only
	 * changed ones.
	 * @return if the UPDATE statement generated by the  includes all columns;  if it
	 * includes only changed columns.
	 */
	var SetAllValues(default, default):Bool;
	@:overload(function():cs.system.data.common.DbCommand {})
	/**
	 * Gets the automatically generated  object required to perform deletions at the
	 * data source.
	 * @return The automatically generated  object required to perform deletions.
	 */
	function GetDeleteCommand(useColumnsForParameterNames:Bool):cs.system.data.common.DbCommand;
	@:overload(function():cs.system.data.common.DbCommand {})
	/**
	 * Gets the automatically generated  object required to perform insertions at the
	 * data source.
	 * @return The automatically generated  object required to perform insertions.
	 */
	function GetInsertCommand(useColumnsForParameterNames:Bool):cs.system.data.common.DbCommand;
	@:overload(function():cs.system.data.common.DbCommand {})
	/**
	 * Gets the automatically generated  object required to perform updates at the data
	 * source.
	 * @return The automatically generated  object required to perform updates.
	 */
	function GetUpdateCommand(useColumnsForParameterNames:Bool):cs.system.data.common.DbCommand;
	/**
	 * Given an unquoted identifier in the correct catalog case, returns the correct
	 * quoted form of that identifier, including properly escaping any embedded quotes
	 * in the identifier.
	 * @param unquotedIdentifier The original unquoted identifier.
	 * @return The quoted version of the identifier. Embedded quotes within the
	 * identifier are properly escaped.
	 */
	function QuoteIdentifier(unquotedIdentifier:String):String;
	/** Clears the commands associated with this . */
	function RefreshSchema():Void;
	/**
	 * Given a quoted identifier, returns the correct unquoted form of that identifier,
	 * including properly un-escaping any embedded quotes in the identifier.
	 * @param quotedIdentifier The identifier that will have its embedded quotes
	 * removed.
	 * @return The unquoted identifier, with embedded quotes properly un-escaped.
	 */
	function UnquoteIdentifier(quotedIdentifier:String):String;
}
