package cs.system.data.common;

/** Provides the data for the RowUpdating event of a .NET Framework data provider. */
@:native("System.Data.Common.RowUpdatingEventArgs")
extern class RowUpdatingEventArgs extends cs.system.EventArgs {
	/**
	 * Gets or sets the  object for an instance of this class.
	 * @return The  to execute during the .
	 */
	var BaseCommand(default, default):cs.system.data.IDbCommand;
	/**
	 * Gets the  to execute during the  operation.
	 * @return The  to execute during the .
	 */
	var Command(default, default):cs.system.data.IDbCommand;
	/**
	 * Gets any errors generated by the .NET Framework data provider when the 
	 * executes.
	 * @return The errors generated by the .NET Framework data provider when the 
	 * executes.
	 */
	var Errors(default, default):cs.system.Exception;
	/**
	 * Gets the  that will be sent to the server as part of an insert, update, or
	 * delete operation.
	 * @return The  to send through an .
	 */
	var Row(default, never):cs.system.data.DataRow;
	/**
	 * Gets the type of SQL statement to execute.
	 * @return The type of SQL statement to execute.
	 */
	var StatementType(default, never):cs.system.data.StatementType;
	/**
	 * Gets or sets the  of the  property.
	 * @return One of the  values. The default is .
	 */
	var Status(default, default):cs.system.data.UpdateStatus;
	/**
	 * Gets the  to send through the .
	 * @return The  to send through the .
	 */
	var TableMapping(default, never):cs.system.data.common.DataTableMapping;
	function new(dataRow:cs.system.data.DataRow, command:cs.system.data.IDbCommand, statementType:cs.system.data.StatementType, tableMapping:cs.system.data.common.DataTableMapping):Void;
}
