name: Setup Ocaml Windows
runs:
  using: composite
  steps:
  - name: Setup ocaml
    uses: ocaml/setup-ocaml@v3
    with:
      ocaml-compiler: ${{ env.OCAML_VERSION }}
      opam-local-packages: |
        haxe.opam

  - name: Install dependencies
    shell: pwsh
    env:
      MBEDTLS_VERSION: 3.6.5
    run: |
      curl.exe -fsSL -o "libmbedtls.tar.xz" --retry 3 `
        https://github.com/Simn/mingw64-mbedtls/releases/download/${{ env.MBEDTLS_VERSION }}/mingw64-${{ env.MINGW_ARCH }}-mbedtls-${{ env.MBEDTLS_VERSION }}-1-noarch.tar.xz
      ${{ env.CYG_ROOT }}\bin\tar.exe -C ${{ env.CYG_ROOT }} -xvf libmbedtls.tar.xz

  - name: Install OCaml libraries
    uses: nick-fields/retry@v3
    with:
      timeout_minutes: 10
      max_attempts: 10
      retry_on: timeout
      shell: pwsh
      command: |
        Set-PSDebug -Trace 1
        # stop after any command returns an error
        $PSNativeCommandUseErrorActionPreference = $true
        $ErrorActionPreference = 'Stop'
        # see: https://github.com/aantron/luv/issues/162
        $env:PATH="${env:CYG_ROOT}\bin;${env:CYG_ROOT}\usr\x86_64-w64-mingw32\bin;${env:PATH}"
        opam install haxe --deps-only
        opam list
    env:
      # Work around default resolver installing 32-bit libraries
      OPAMEXTERNALSOLVER: builtin-mccs+glpk
