package flash.display;

extern class Stage extends DisplayObjectContainer {
	var align(get,set) : StageAlign;
	var allowsFullScreen(get,never) : Bool;
	@:require(flash11_3) var allowsFullScreenInteractive(get,never) : Bool;
	var browserZoomFactor(get,never) : Float;
	@:require(flash10_2) var color(get,set) : UInt;
	@:require(flash10) var colorCorrection(get,set) : ColorCorrection;
	@:require(flash10) var colorCorrectionSupport(get,never) : ColorCorrectionSupport;
	@:require(flash11_4) var contentsScaleFactor(get,never) : Float;
	@:require(flash11) var displayContextInfo(get,never) : String;
	var displayState(get,set) : StageDisplayState;
	var focus(get,set) : InteractiveObject;
	var frameRate(get,set) : Float;
	var fullScreenHeight(get,never) : UInt;
	var fullScreenSourceRect(get,set) : flash.geom.Rectangle;
	var fullScreenWidth(get,never) : UInt;
	@:require(flash11_2) var mouseLock(get,set) : Bool;
	var quality(get,set) : StageQuality;
	var scaleMode(get,set) : StageScaleMode;
	var showDefaultContextMenu(get,set) : Bool;
	@:require(flash11) var softKeyboardRect(get,never) : flash.geom.Rectangle;
	@:require(flash11) var stage3Ds(get,never) : flash.Vector<Stage3D>;
	var stageFocusRect(get,set) : Bool;
	var stageHeight(get,set) : Int;
	@:require(flash10_2) var stageVideos(get,never) : flash.Vector<flash.media.StageVideo>;
	var stageWidth(get,set) : Int;
	@:require(flash10_1) var wmodeGPU(get,never) : Bool;
	private function get_align() : StageAlign;
	private function get_allowsFullScreen() : Bool;
	private function get_allowsFullScreenInteractive() : Bool;
	private function get_browserZoomFactor() : Float;
	private function get_color() : UInt;
	private function get_colorCorrection() : ColorCorrection;
	private function get_colorCorrectionSupport() : ColorCorrectionSupport;
	private function get_constructor() : Dynamic;
	private function get_contentsScaleFactor() : Float;
	private function get_displayContextInfo() : String;
	private function get_displayState() : StageDisplayState;
	private function get_focus() : InteractiveObject;
	private function get_frameRate() : Float;
	private function get_fullScreenHeight() : UInt;
	private function get_fullScreenSourceRect() : flash.geom.Rectangle;
	private function get_fullScreenWidth() : UInt;
	private function get_mouseLock() : Bool;
	private function get_quality() : StageQuality;
	private function get_scaleMode() : StageScaleMode;
	private function get_showDefaultContextMenu() : Bool;
	private function get_softKeyboardRect() : flash.geom.Rectangle;
	private function get_stage3Ds() : flash.Vector<Stage3D>;
	private function get_stageFocusRect() : Bool;
	private function get_stageHeight() : Int;
	private function get_stageVideos() : flash.Vector<flash.media.StageVideo>;
	private function get_stageWidth() : Int;
	private function get_wmodeGPU() : Bool;
	function invalidate() : Void;
	function isFocusInaccessible() : Bool;
	private function set_align(value : StageAlign) : StageAlign;
	private function set_color(value : UInt) : UInt;
	private function set_colorCorrection(value : ColorCorrection) : ColorCorrection;
	private function set_constructor(value : Dynamic) : Dynamic;
	private function set_displayState(value : StageDisplayState) : StageDisplayState;
	private function set_focus(value : InteractiveObject) : InteractiveObject;
	private function set_frameRate(value : Float) : Float;
	private function set_fullScreenSourceRect(value : flash.geom.Rectangle) : flash.geom.Rectangle;
	private function set_mouseLock(value : Bool) : Bool;
	private function set_quality(value : StageQuality) : StageQuality;
	private function set_scaleMode(value : StageScaleMode) : StageScaleMode;
	private function set_showDefaultContextMenu(value : Bool) : Bool;
	private function set_stageFocusRect(value : Bool) : Bool;
	private function set_stageHeight(value : Int) : Int;
	private function set_stageWidth(value : Int) : Int;
}
