EXTLIB=../../mtcvs/extlib-dev
SWFLIB=../../mtcvs/swflib
EXTC=../../mtcvs/extc
NEKO=../neko
FILES=$(EXTLIB)/*.ml* -n $(EXTLIB)/install.ml $(SWFLIB)/*.ml* $(EXTC)/extc.ml* $(NEKO)/libs/include/ocaml/*.ml* *.ml*
LIBS=unix.cmxa
FLAGS=-o haxe -pp camlp4o -lp "-cclib $(EXTC)/extc_stubs.o -cclib -lz"

all:
	ocamlc -c $(EXTC)/extc_stubs.c
	ocamake $(FLAGS) $(FILES) $(LIBS)

clean:
	ocamake $(FLAGS) -clean $(FILES) $(LIBS)
