// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_ds__ReadOnlyArray_ReadOnlyArray_Impl_
#include <haxe/ds/_ReadOnlyArray/ReadOnlyArray_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_7f14d7e3dcced88b_41_get_length,"haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_","get_length",0xa04b5705,"haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_.get_length","haxe/ds/ReadOnlyArray.hx",41,0x1a4daefe)
HX_LOCAL_STACK_FRAME(_hx_pos_7f14d7e3dcced88b_44_get,"haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_","get",0x6cc23f80,"haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_.get","haxe/ds/ReadOnlyArray.hx",44,0x1a4daefe)
HX_LOCAL_STACK_FRAME(_hx_pos_7f14d7e3dcced88b_60_concat,"haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_","concat",0x9672f86a,"haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_.concat","haxe/ds/ReadOnlyArray.hx",60,0x1a4daefe)

namespace {

struct __ReadOnlyArray_Impl__objget_length final : public ::hx::AutoCallable_obj< int (::cpp::VirtualArray) > {
	__ReadOnlyArray_Impl__objget_length() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __ReadOnlyArray_Impl__objget_length*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	int HX_LOCAL_RUN(::cpp::VirtualArray this1) override {
		return haxe::ds::_ReadOnlyArray::ReadOnlyArray_Impl__obj::get_length(this1);
	}
};

::hx::Callable< int (::cpp::VirtualArray) > _hx_alloc__ReadOnlyArray_Impl__objget_length;

struct __ReadOnlyArray_Impl__objget final : public ::hx::AutoCallable_obj<  ::Dynamic (::cpp::VirtualArray,int) > {
	__ReadOnlyArray_Impl__objget() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __ReadOnlyArray_Impl__objget*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Dynamic HX_LOCAL_RUN(::cpp::VirtualArray this1,int i) override {
		return haxe::ds::_ReadOnlyArray::ReadOnlyArray_Impl__obj::get(this1, i);
	}
};

::hx::Callable<  ::Dynamic (::cpp::VirtualArray,int) > _hx_alloc__ReadOnlyArray_Impl__objget;

struct __ReadOnlyArray_Impl__objconcat final : public ::hx::AutoCallable_obj< ::cpp::VirtualArray (::cpp::VirtualArray,::cpp::VirtualArray) > {
	__ReadOnlyArray_Impl__objconcat() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __ReadOnlyArray_Impl__objconcat*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::cpp::VirtualArray HX_LOCAL_RUN(::cpp::VirtualArray this1,::cpp::VirtualArray a) override {
		return haxe::ds::_ReadOnlyArray::ReadOnlyArray_Impl__obj::concat(this1, a);
	}
};

::hx::Callable< ::cpp::VirtualArray (::cpp::VirtualArray,::cpp::VirtualArray) > _hx_alloc__ReadOnlyArray_Impl__objconcat;

}

namespace haxe{
namespace ds{
namespace _ReadOnlyArray{

void ReadOnlyArray_Impl__obj::__construct() { }

::Dynamic ReadOnlyArray_Impl__obj::__CreateEmpty() { return new ReadOnlyArray_Impl__obj; }

void* ReadOnlyArray_Impl__obj::_hx_vtable = 0;

::Dynamic ReadOnlyArray_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< ReadOnlyArray_Impl__obj > _hx_result = new ReadOnlyArray_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool ReadOnlyArray_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x6432b6ca;
}

int ReadOnlyArray_Impl__obj::get_length(::cpp::VirtualArray this1){
            	HX_STACKFRAME(&_hx_pos_7f14d7e3dcced88b_41_get_length)
HXDLIN(  41)		return this1->get_length();
            	}


::hx::Callable< int (::cpp::VirtualArray) > ReadOnlyArray_Impl__obj::get_length_dyn() { return _hx_alloc__ReadOnlyArray_Impl__objget_length; }

 ::Dynamic ReadOnlyArray_Impl__obj::get(::cpp::VirtualArray this1,int i){
            	HX_STACKFRAME(&_hx_pos_7f14d7e3dcced88b_44_get)
HXDLIN(  44)		return this1->__get(i);
            	}


::hx::Callable<  ::Dynamic (::cpp::VirtualArray,int) > ReadOnlyArray_Impl__obj::get_dyn() { return _hx_alloc__ReadOnlyArray_Impl__objget; }

::cpp::VirtualArray ReadOnlyArray_Impl__obj::concat(::cpp::VirtualArray this1,::cpp::VirtualArray a){
            	HX_STACKFRAME(&_hx_pos_7f14d7e3dcced88b_60_concat)
HXDLIN(  60)		return this1->concat(a);
            	}


::hx::Callable< ::cpp::VirtualArray (::cpp::VirtualArray,::cpp::VirtualArray) > ReadOnlyArray_Impl__obj::concat_dyn() { return _hx_alloc__ReadOnlyArray_Impl__objconcat; }


ReadOnlyArray_Impl__obj::ReadOnlyArray_Impl__obj()
{
}

bool ReadOnlyArray_Impl__obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { outValue = get_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"concat") ) { outValue = concat_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"get_length") ) { outValue = get_length_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo* ReadOnlyArray_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo* ReadOnlyArray_Impl__obj_sStaticStorageInfo = 0;
#endif

static ::String* ReadOnlyArray_Impl__obj_sMemberFields = 0;

::hx::Class ReadOnlyArray_Impl__obj::__mClass;

static ::String ReadOnlyArray_Impl__obj_sStaticFields[] = {
	HX_("get_length",af,04,8f,8f),
	HX_("get",96,80,4e,00),
	HX_("concat",14,09,d0,c7),
	::String(null())
};

void ReadOnlyArray_Impl__obj::__register()
{
	ReadOnlyArray_Impl__obj _hx_dummy;
	ReadOnlyArray_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.ds._ReadOnlyArray.ReadOnlyArray_Impl_",58,e2,2f,d0);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &ReadOnlyArray_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(ReadOnlyArray_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ReadOnlyArray_Impl__obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< ReadOnlyArray_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ReadOnlyArray_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ReadOnlyArray_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void ReadOnlyArray_Impl__obj::__boot()
{
_hx_alloc__ReadOnlyArray_Impl__objget_length = new (::hx::NewObjectType::NewObjConst) __ReadOnlyArray_Impl__objget_length();

_hx_alloc__ReadOnlyArray_Impl__objget = new (::hx::NewObjectType::NewObjConst) __ReadOnlyArray_Impl__objget();

_hx_alloc__ReadOnlyArray_Impl__objconcat = new (::hx::NewObjectType::NewObjConst) __ReadOnlyArray_Impl__objconcat();

}

} // end namespace haxe
} // end namespace ds
} // end namespace _ReadOnlyArray
