// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_macro_AbstractFlag
#include <haxe/macro/AbstractFlag.h>
#endif
#ifndef INCLUDED_haxe_macro_ComplexType
#include <haxe/macro/ComplexType.h>
#endif
namespace haxe{
namespace macro{

::haxe::macro::AbstractFlag AbstractFlag_obj::AbEnum;

::haxe::macro::AbstractFlag AbstractFlag_obj::AbFrom( ::haxe::macro::ComplexType ct)
{
	return ::hx::CreateEnum<AbstractFlag_obj>(HX_("AbFrom",0b,1f,13,99),1,1)->_hx_init(0,ct);
}

::haxe::macro::AbstractFlag AbstractFlag_obj::AbTo( ::haxe::macro::ComplexType ct)
{
	return ::hx::CreateEnum<AbstractFlag_obj>(HX_("AbTo",dc,84,41,2b),2,1)->_hx_init(0,ct);
}

bool AbstractFlag_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("AbEnum",a2,e4,66,98)) { outValue = AbstractFlag_obj::AbEnum; return true; }
	if (inName==HX_("AbFrom",0b,1f,13,99)) { outValue = AbstractFlag_obj::AbFrom_dyn(); return true; }
	if (inName==HX_("AbTo",dc,84,41,2b)) { outValue = AbstractFlag_obj::AbTo_dyn(); return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(AbstractFlag_obj)

bool AbstractFlag_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId == (int)0x00000001 || inClassId == ::hx::EnumBase_obj::_hx_ClassId || inClassId == _hx_ClassId;
}
int AbstractFlag_obj::__FindIndex(::String inName)
{
	if (inName==HX_("AbEnum",a2,e4,66,98)) return 0;
	if (inName==HX_("AbFrom",0b,1f,13,99)) return 1;
	if (inName==HX_("AbTo",dc,84,41,2b)) return 2;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC1(AbstractFlag_obj, AbFrom, return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(AbstractFlag_obj, AbTo, return)

int AbstractFlag_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("AbEnum",a2,e4,66,98)) return 0;
	if (inName==HX_("AbFrom",0b,1f,13,99)) return 1;
	if (inName==HX_("AbTo",dc,84,41,2b)) return 1;
	return super::__FindArgCount(inName);
}

::hx::Val AbstractFlag_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("AbEnum",a2,e4,66,98)) return AbEnum;
	if (inName==HX_("AbFrom",0b,1f,13,99)) return AbFrom_dyn();
	if (inName==HX_("AbTo",dc,84,41,2b)) return AbTo_dyn();
	return super::__Field(inName,inCallProp);
}

static ::String AbstractFlag_obj_sStaticFields[] = {
	HX_("AbEnum",a2,e4,66,98),
	HX_("AbFrom",0b,1f,13,99),
	HX_("AbTo",dc,84,41,2b),
	::String(null())
};

::hx::Class AbstractFlag_obj::__mClass;

::Dynamic __Create_AbstractFlag_obj() { return new AbstractFlag_obj; }

void AbstractFlag_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("haxe.macro.AbstractFlag",b8,c2,23,17), ::hx::TCanCast< AbstractFlag_obj >,AbstractFlag_obj_sStaticFields,0,
	&__Create_AbstractFlag_obj, &__Create,
	&super::__SGetClass(), &CreateAbstractFlag_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &AbstractFlag_obj::__GetStatic;
}

void AbstractFlag_obj::__boot()
{
AbEnum = ::hx::CreateConstEnum<AbstractFlag_obj>(HX_("AbEnum",a2,e4,66,98), 0);
}


} // end namespace haxe
} // end namespace macro
