// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_macro_EFieldKind
#include <haxe/macro/EFieldKind.h>
#endif
namespace haxe{
namespace macro{

::haxe::macro::EFieldKind EFieldKind_obj::Normal;

::haxe::macro::EFieldKind EFieldKind_obj::Safe;

bool EFieldKind_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("Normal",47,e6,fd,64)) { outValue = EFieldKind_obj::Normal; return true; }
	if (inName==HX_("Safe",6d,a9,26,37)) { outValue = EFieldKind_obj::Safe; return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(EFieldKind_obj)

bool EFieldKind_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId == (int)0x00000001 || inClassId == ::hx::EnumBase_obj::_hx_ClassId || inClassId == _hx_ClassId;
}
int EFieldKind_obj::__FindIndex(::String inName)
{
	if (inName==HX_("Normal",47,e6,fd,64)) return 0;
	if (inName==HX_("Safe",6d,a9,26,37)) return 1;
	return super::__FindIndex(inName);
}

int EFieldKind_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("Normal",47,e6,fd,64)) return 0;
	if (inName==HX_("Safe",6d,a9,26,37)) return 0;
	return super::__FindArgCount(inName);
}

::hx::Val EFieldKind_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("Normal",47,e6,fd,64)) return Normal;
	if (inName==HX_("Safe",6d,a9,26,37)) return Safe;
	return super::__Field(inName,inCallProp);
}

static ::String EFieldKind_obj_sStaticFields[] = {
	HX_("Normal",47,e6,fd,64),
	HX_("Safe",6d,a9,26,37),
	::String(null())
};

::hx::Class EFieldKind_obj::__mClass;

::Dynamic __Create_EFieldKind_obj() { return new EFieldKind_obj; }

void EFieldKind_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("haxe.macro.EFieldKind",93,2c,f0,ba), ::hx::TCanCast< EFieldKind_obj >,EFieldKind_obj_sStaticFields,0,
	&__Create_EFieldKind_obj, &__Create,
	&super::__SGetClass(), &CreateEFieldKind_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &EFieldKind_obj::__GetStatic;
}

void EFieldKind_obj::__boot()
{
Normal = ::hx::CreateConstEnum<EFieldKind_obj>(HX_("Normal",47,e6,fd,64), 0);
Safe = ::hx::CreateConstEnum<EFieldKind_obj>(HX_("Safe",6d,a9,26,37), 1);
}


} // end namespace haxe
} // end namespace macro
