// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_macro_StringLiteralKind
#include <haxe/macro/StringLiteralKind.h>
#endif
namespace haxe{
namespace macro{

::haxe::macro::StringLiteralKind StringLiteralKind_obj::DoubleQuotes;

::haxe::macro::StringLiteralKind StringLiteralKind_obj::SingleQuotes;

bool StringLiteralKind_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("DoubleQuotes",c8,bf,7d,8d)) { outValue = StringLiteralKind_obj::DoubleQuotes; return true; }
	if (inName==HX_("SingleQuotes",7f,6e,2c,3f)) { outValue = StringLiteralKind_obj::SingleQuotes; return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(StringLiteralKind_obj)

bool StringLiteralKind_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId == (int)0x00000001 || inClassId == ::hx::EnumBase_obj::_hx_ClassId || inClassId == _hx_ClassId;
}
int StringLiteralKind_obj::__FindIndex(::String inName)
{
	if (inName==HX_("DoubleQuotes",c8,bf,7d,8d)) return 0;
	if (inName==HX_("SingleQuotes",7f,6e,2c,3f)) return 1;
	return super::__FindIndex(inName);
}

int StringLiteralKind_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("DoubleQuotes",c8,bf,7d,8d)) return 0;
	if (inName==HX_("SingleQuotes",7f,6e,2c,3f)) return 0;
	return super::__FindArgCount(inName);
}

::hx::Val StringLiteralKind_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("DoubleQuotes",c8,bf,7d,8d)) return DoubleQuotes;
	if (inName==HX_("SingleQuotes",7f,6e,2c,3f)) return SingleQuotes;
	return super::__Field(inName,inCallProp);
}

static ::String StringLiteralKind_obj_sStaticFields[] = {
	HX_("DoubleQuotes",c8,bf,7d,8d),
	HX_("SingleQuotes",7f,6e,2c,3f),
	::String(null())
};

::hx::Class StringLiteralKind_obj::__mClass;

::Dynamic __Create_StringLiteralKind_obj() { return new StringLiteralKind_obj; }

void StringLiteralKind_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("haxe.macro.StringLiteralKind",c8,d3,fe,ec), ::hx::TCanCast< StringLiteralKind_obj >,StringLiteralKind_obj_sStaticFields,0,
	&__Create_StringLiteralKind_obj, &__Create,
	&super::__SGetClass(), &CreateStringLiteralKind_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &StringLiteralKind_obj::__GetStatic;
}

void StringLiteralKind_obj::__boot()
{
DoubleQuotes = ::hx::CreateConstEnum<StringLiteralKind_obj>(HX_("DoubleQuotes",c8,bf,7d,8d), 0);
SingleQuotes = ::hx::CreateConstEnum<StringLiteralKind_obj>(HX_("SingleQuotes",7f,6e,2c,3f), 1);
}


} // end namespace haxe
} // end namespace macro
