// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_hxparse_LexEngine
#define INCLUDED_hxparse_LexEngine

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,StringMap)
HX_DECLARE_CLASS2(haxe,io,Bytes)
HX_DECLARE_CLASS1(hxparse,LexEngine)
HX_DECLARE_CLASS1(hxparse,State)
HX_DECLARE_CLASS2(hxparse,_LexEngine,CharRange)
HX_DECLARE_CLASS2(hxparse,_LexEngine,Node)
HX_DECLARE_CLASS2(hxparse,_LexEngine,Pattern)

namespace hxparse{


class HXCPP_CLASS_ATTRIBUTES LexEngine_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef LexEngine_obj OBJ_;
		LexEngine_obj();

	public:
		enum { _hx_ClassId = 0x653cb29e };

		void __construct(::Array< ::Dynamic> patterns);
		inline void *operator new(size_t inSize, bool inContainer=true, const char* inName="hxparse.LexEngine")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, true, "hxparse.LexEngine"); }
		static ::hx::ObjectPtr< LexEngine_obj > __new(::Array< ::Dynamic> patterns);
		static ::hx::ObjectPtr< LexEngine_obj > __alloc(::hx::Ctx *_hx_ctx,::Array< ::Dynamic> patterns);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~LexEngine_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, ::Dynamic &ioValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(::Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("LexEngine",e1,98,ba,df); }

		static void __boot();
		static ::Array< ::Dynamic> single(int c);
		static ::hx::Callable< ::Array< ::Dynamic> (int) > single_dyn();

		static  ::hxparse::_LexEngine::Pattern parse(::String pattern);
		static ::hx::Callable<  ::hxparse::_LexEngine::Pattern (::String) > parse_dyn();

		static  ::hxparse::_LexEngine::Pattern next( ::hxparse::_LexEngine::Pattern a, ::hxparse::_LexEngine::Pattern b);
		static ::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Pattern) > next_dyn();

		static  ::hxparse::_LexEngine::Pattern plus( ::hxparse::_LexEngine::Pattern r);
		static ::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > plus_dyn();

		static  ::hxparse::_LexEngine::Pattern star( ::hxparse::_LexEngine::Pattern r);
		static ::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > star_dyn();

		static  ::hxparse::_LexEngine::Pattern opt( ::hxparse::_LexEngine::Pattern r);
		static ::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > opt_dyn();

		static ::Array< ::Dynamic> cinter(::Array< ::Dynamic> c1,::Array< ::Dynamic> c2);
		static ::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > cinter_dyn();

		static ::Array< ::Dynamic> cdiff(::Array< ::Dynamic> c1,::Array< ::Dynamic> c2);
		static ::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > cdiff_dyn();

		static ::Array< ::Dynamic> ccomplement(::Array< ::Dynamic> c);
		static ::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>) > ccomplement_dyn();

		static ::Array< ::Dynamic> cunion(::Array< ::Dynamic> ca,::Array< ::Dynamic> cb);
		static ::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > cunion_dyn();

		static  ::Dynamic parseInner( ::haxe::io::Bytes pattern, ::Dynamic i, ::Dynamic pDepth);
		static ::hx::Callable<  ::Dynamic ( ::haxe::io::Bytes, ::Dynamic, ::Dynamic) > parseInner_dyn();

		static int MAX_CODE;
		static ::Array< ::Dynamic> EMPTY;
		static ::Array< ::Dynamic> ALL_CHARS;
		  ::hxparse::State firstState();
		::hx::Callable<  ::hxparse::State () > firstState_dyn();

		  ::hxparse::State makeState(::Array< ::Dynamic> nodes);
		::hx::Callable<  ::hxparse::State (::Array< ::Dynamic>) > makeState_dyn();

		 ::Array< ::Dynamic> getTransitions(::Array< ::Dynamic> nodes);
		::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>) > getTransitions_dyn();

		 void addNode(::Array< ::Dynamic> nodes, ::hxparse::_LexEngine::Node n);
		::hx::Callable< void (::Array< ::Dynamic>, ::hxparse::_LexEngine::Node) > addNode_dyn();

		 ::Array< ::Dynamic> addNodes(::Array< ::Dynamic> nodes,::Array< ::Dynamic> add);
		::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > addNodes_dyn();

		  ::hxparse::_LexEngine::Node node(int pid);
		::hx::Callable<  ::hxparse::_LexEngine::Node (int) > node_dyn();

		  ::hxparse::_LexEngine::Node initNode( ::hxparse::_LexEngine::Pattern p, ::hxparse::_LexEngine::Node finalId,int pid);
		::hx::Callable<  ::hxparse::_LexEngine::Node ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Node,int) > initNode_dyn();

		int uid;
		::Array< ::Dynamic> nodes;
		::Array< ::Dynamic> finals;
		::Array< ::Dynamic> states;
		 ::haxe::ds::StringMap hstates;
};

} // end namespace hxparse

#endif /* INCLUDED_hxparse_LexEngine */ 
