// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Event
#include <haxe/Event.h>
#endif
#ifndef INCLUDED_haxe_EventLoop
#include <haxe/EventLoop.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_Timer
#include <haxe/Timer.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_118___default_run,"haxe.Timer","__default_run",0xdc2b9b9c,"haxe.Timer.__default_run","haxe/Timer.hx",118,0x1a690682)
HX_DEFINE_STACK_FRAME(_hx_pos_102f69689d37b2bb_74_new,"haxe.Timer","new",0x4136b0cf,"haxe.Timer.new","haxe/Timer.hx",74,0x1a690682)
HX_DEFINE_STACK_FRAME(_hx_pos_102f69689d37b2bb_64_new,"haxe.Timer","new",0x4136b0cf,"haxe.Timer.new","haxe/Timer.hx",64,0x1a690682)
HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_97_stop,"haxe.Timer","stop",0xd1fd70b3,"haxe.Timer.stop","haxe/Timer.hx",97,0x1a690682)
HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_131_delay,"haxe.Timer","delay",0x3ed5f1b2,"haxe.Timer.delay","haxe/Timer.hx",131,0x1a690682)
HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_129_delay,"haxe.Timer","delay",0x3ed5f1b2,"haxe.Timer.delay","haxe/Timer.hx",129,0x1a690682)
HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_149_measure,"haxe.Timer","measure",0x42373f4d,"haxe.Timer.measure","haxe/Timer.hx",149,0x1a690682)
HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_173_stamp,"haxe.Timer","stamp",0xebba8a32,"haxe.Timer.stamp","haxe/Timer.hx",173,0x1a690682)
HX_LOCAL_STACK_FRAME(_hx_pos_102f69689d37b2bb_199_milliseconds,"haxe.Timer","milliseconds",0xe34827c3,"haxe.Timer.milliseconds","haxe/Timer.hx",199,0x1a690682)

namespace {

struct __Timer_objstop final : public ::hx::AutoCallable_obj< void () > {
	::hx::ObjectPtr<haxe::Timer_obj> __this;
	__Timer_objstop(::hx::ObjectPtr<haxe::Timer_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Timer_objstop*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN() override {
		__this->stop();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Timer_objdelay final : public ::hx::AutoCallable_obj<  ::haxe::Timer (::hx::Callable< void () >,int) > {
	__Timer_objdelay() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Timer_objdelay*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::haxe::Timer HX_LOCAL_RUN(::hx::Callable< void () > f,int time_ms) override {
		return haxe::Timer_obj::delay(f, time_ms);
	}
};

::hx::Callable<  ::haxe::Timer (::hx::Callable< void () >,int) > _hx_alloc__Timer_objdelay;

struct __Timer_objmeasure final : public ::hx::AutoCallable_obj<  ::Dynamic (::hx::Callable<  ::Dynamic () >, ::Dynamic) > {
	__Timer_objmeasure() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Timer_objmeasure*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Dynamic HX_LOCAL_RUN(::hx::Callable<  ::Dynamic () > f, ::Dynamic pos) override {
		return haxe::Timer_obj::measure(f, pos);
	}
};

::hx::Callable<  ::Dynamic (::hx::Callable<  ::Dynamic () >, ::Dynamic) > _hx_alloc__Timer_objmeasure;

struct __Timer_objstamp final : public ::hx::AutoCallable_obj< Float () > {
	__Timer_objstamp() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Timer_objstamp*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	Float HX_LOCAL_RUN() override {
		return haxe::Timer_obj::stamp();
	}
};

::hx::Callable< Float () > _hx_alloc__Timer_objstamp;

struct __Timer_objmilliseconds final : public ::hx::AutoCallable_obj< ::cpp::Int64 () > {
	__Timer_objmilliseconds() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Timer_objmilliseconds*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::cpp::Int64 HX_LOCAL_RUN() override {
		return haxe::Timer_obj::milliseconds();
	}
};

::hx::Callable< ::cpp::Int64 () > _hx_alloc__Timer_objmilliseconds;

struct __default_run final : public ::hx::AutoCallable_obj< void () > {
	::hx::ObjectPtr<haxe::Timer_obj> __this;
	__default_run(::hx::ObjectPtr<haxe::Timer_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __default_run*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN() override {
{
            	HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_118___default_run)
            	}
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

}

namespace haxe{

void Timer_obj::__construct(int time_ms){
HX_BEGIN_LOCAL_FUNC_S1(::hx::AutoCallable_obj< void() >, _hx_Closure_0,  ::haxe::Timer,_gthis)
            		void HX_LOCAL_RUN(  ){
            			HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_74_new)
HXLINE(  74)			_gthis->run();
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC0((void))

            	HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_64_new)
HXDLIN(  64)		 ::haxe::Timer _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE(  74)		this->event = ::haxe::EventLoop_obj::get_current()->addTimer(::hx::Callable< void() >(new _hx_Closure_0(_gthis)),(( (Float)(time_ms) ) / ((Float)1000.)),null());
            	}

::Dynamic Timer_obj::__CreateEmpty() { return new Timer_obj; }

void* Timer_obj::_hx_vtable = 0;

::Dynamic Timer_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Timer_obj > _hx_result = new Timer_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Timer_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x04eaa0bb;
}

void Timer_obj::stop(){
            	HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_97_stop)
HXDLIN(  97)		if (::hx::IsNotNull( this->event )) {
HXLINE(  98)			this->event->stop();
HXLINE(  99)			this->event = null();
            		}
            	}


::hx::Callable< void () > Timer_obj::stop_dyn() { return new __Timer_objstop(this); }

 ::haxe::Timer Timer_obj::delay(::hx::Callable< void () > f,int time_ms){
HX_BEGIN_LOCAL_FUNC_S2(::hx::AutoCallable_obj< void() >, _hx_Closure_0,  ::haxe::Timer,t,::hx::Callable< void () >,f)
            		void HX_LOCAL_RUN(  ){
            			HX_GC_STACKFRAME(&_hx_pos_102f69689d37b2bb_131_delay)
HXLINE( 132)			t->stop();
HXLINE( 133)			f();
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC0((void))

            	HX_GC_STACKFRAME(&_hx_pos_102f69689d37b2bb_129_delay)
HXLINE( 130)		 ::haxe::Timer t =  ::haxe::Timer_obj::__alloc( HX_CTX ,time_ms);
HXLINE( 131)		t->run = ::hx::Callable< void() >(new _hx_Closure_0(t,f));
HXLINE( 135)		return t;
            	}


::hx::Callable<  ::haxe::Timer (::hx::Callable< void () >,int) > Timer_obj::delay_dyn() { return _hx_alloc__Timer_objdelay; }

 ::Dynamic Timer_obj::measure(::hx::Callable<  ::Dynamic () > f, ::Dynamic pos){
            	HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_149_measure)
HXLINE( 150)		Float t0 =  ::__time_stamp();
HXLINE( 151)		 ::Dynamic r = f();
HXLINE( 152)		::hx::Callable< void ( ::Dynamic, ::Dynamic) > _hx_tmp = ::haxe::Log_obj::trace;
HXDLIN( 152)		_hx_tmp((( ::__time_stamp() - t0) + HX_("s",73,00,00,00)),pos);
HXLINE( 153)		return r;
            	}


::hx::Callable<  ::Dynamic (::hx::Callable<  ::Dynamic () >, ::Dynamic) > Timer_obj::measure_dyn() { return _hx_alloc__Timer_objmeasure; }

Float Timer_obj::stamp(){
            	HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_173_stamp)
HXDLIN( 173)		return  ::__time_stamp();
            	}


::hx::Callable< Float () > Timer_obj::stamp_dyn() { return _hx_alloc__Timer_objstamp; }

::cpp::Int64 Timer_obj::milliseconds(){
            	HX_STACKFRAME(&_hx_pos_102f69689d37b2bb_199_milliseconds)
HXDLIN( 199)		return  ::__time_stamp_ms();
            	}


::hx::Callable< ::cpp::Int64 () > Timer_obj::milliseconds_dyn() { return _hx_alloc__Timer_objmilliseconds; }


void Timer_obj::__alloc_dynamic_functions(::hx::Ctx* _hx_ctx, Timer_obj* _hx_obj) {
	if (!_hx_obj->run.mPtr) { _hx_obj->run = new __default_run(_hx_obj); }
}
::hx::ObjectPtr< Timer_obj > Timer_obj::__new(int time_ms) {
	::hx::ObjectPtr< Timer_obj > __this = new Timer_obj();
	__this->__construct(time_ms);
	return __this;
}

::hx::ObjectPtr< Timer_obj > Timer_obj::__alloc(::hx::Ctx *_hx_ctx,int time_ms) {
	Timer_obj* __this = (Timer_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Timer_obj), true, "haxe.Timer"));
	*(void **)__this = Timer_obj::_hx_vtable;
	haxe::Timer_obj::__alloc_dynamic_functions(_hx_ctx,__this);
	__this->__construct(time_ms);
	return __this;
}

Timer_obj::Timer_obj()
{
	run = new __default_run(this);
}

void Timer_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Timer);
	HX_MARK_MEMBER_NAME(event, "event");
	HX_MARK_MEMBER_NAME(run, "run");
	HX_MARK_END_CLASS();
}

void Timer_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(event, "event");
	HX_VISIT_MEMBER_NAME(run, "run");
}

::hx::Val Timer_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { return ::hx::Val( run ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"stop") ) { return ::hx::Val( stop_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"event") ) { return ::hx::Val( event ); }
	}
	return super::__Field(inName,inCallProp);
}

bool Timer_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"delay") ) { outValue = delay_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"stamp") ) { outValue = stamp_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"measure") ) { outValue = measure_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"milliseconds") ) { outValue = milliseconds_dyn(); return true; }
	}
	return false;
}

::hx::Val Timer_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { _hx_set_run(HX_CTX_GET, inValue.Cast< ::hx::Callable< void () > >()); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"event") ) { event = inValue.Cast<  ::haxe::Event >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Timer_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("event",1a,c8,c4,75));
	outFields->push(HX_("run",4b,e7,56,00));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Timer_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /*  ::haxe::Event */ , (int)offsetof(Timer_obj, event), HX_("event",1a,c8,c4,75) },
	{ ::hx::fsObject /* ::hx::Callable< void () > */ , (int)offsetof(Timer_obj, run), HX_("run",4b,e7,56,00) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo* Timer_obj_sStaticStorageInfo = 0;
#endif

static ::String Timer_obj_sMemberFields[] = {
	HX_("stop",02,f0,5b,4c),
	HX_("event",1a,c8,c4,75),
	HX_("run",4b,e7,56,00),
	::String(null())
};

::hx::Class Timer_obj::__mClass;

static ::String Timer_obj_sStaticFields[] = {
	HX_("delay",83,d7,26,d7),
	HX_("measure",5e,fb,e9,3c),
	HX_("stamp",03,70,0b,84),
	HX_("milliseconds",12,0e,3d,c7),
	::String(null())
};

void Timer_obj::__register()
{
	Timer_obj _hx_dummy;
	Timer_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.Timer",5d,9d,24,4b);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Timer_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Timer_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Timer_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Timer_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Timer_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Timer_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Timer_obj::__boot()
{
_hx_alloc__Timer_objdelay = new (::hx::NewObjectType::NewObjConst) __Timer_objdelay();

_hx_alloc__Timer_objmeasure = new (::hx::NewObjectType::NewObjConst) __Timer_objmeasure();

_hx_alloc__Timer_objstamp = new (::hx::NewObjectType::NewObjConst) __Timer_objstamp();

_hx_alloc__Timer_objmilliseconds = new (::hx::NewObjectType::NewObjConst) __Timer_objmilliseconds();

}

} // end namespace haxe
