// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Unit
#include <haxe/Unit.h>
#endif
namespace haxe{

::haxe::Unit Unit_obj::Unit;

bool Unit_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("Unit",a4,f6,82,38)) { outValue = Unit_obj::Unit; return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(Unit_obj)

bool Unit_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId == (int)0x00000001 || inClassId == ::hx::EnumBase_obj::_hx_ClassId || inClassId == _hx_ClassId;
}
int Unit_obj::__FindIndex(::String inName)
{
	if (inName==HX_("Unit",a4,f6,82,38)) return 0;
	return super::__FindIndex(inName);
}

int Unit_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("Unit",a4,f6,82,38)) return 0;
	return super::__FindArgCount(inName);
}

::hx::Val Unit_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("Unit",a4,f6,82,38)) return Unit;
	return super::__Field(inName,inCallProp);
}

static ::String Unit_obj_sStaticFields[] = {
	HX_("Unit",a4,f6,82,38),
	::String(null())
};

::hx::Class Unit_obj::__mClass;

::Dynamic __Create_Unit_obj() { return new Unit_obj; }

void Unit_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("haxe.Unit",ec,a7,3c,f3), ::hx::TCanCast< Unit_obj >,Unit_obj_sStaticFields,0,
	&__Create_Unit_obj, &__Create,
	&super::__SGetClass(), &CreateUnit_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &Unit_obj::__GetStatic;
}

void Unit_obj::__boot()
{
Unit = ::hx::CreateConstEnum<Unit_obj>(HX_("Unit",a4,f6,82,38), 0);
}


} // end namespace haxe
