// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_haxe_ds_GenericStack_haxe_ds_StringMap_Dynamic
#define INCLUDED_haxe_ds_GenericStack_haxe_ds_StringMap_Dynamic

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,GenericCell_haxe_ds_StringMap_Dynamic)
HX_DECLARE_CLASS2(haxe,ds,GenericStack_haxe_ds_StringMap_Dynamic)
HX_DECLARE_CLASS2(haxe,ds,StringMap)

namespace haxe{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES GenericStack_haxe_ds_StringMap_Dynamic_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef GenericStack_haxe_ds_StringMap_Dynamic_obj OBJ_;
		GenericStack_haxe_ds_StringMap_Dynamic_obj();

	public:
		enum { _hx_ClassId = 0x222eeedb };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true, const char* inName="haxe.ds.GenericStack_haxe_ds_StringMap_Dynamic")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, true, "haxe.ds.GenericStack_haxe_ds_StringMap_Dynamic"); }
		static ::hx::ObjectPtr< GenericStack_haxe_ds_StringMap_Dynamic_obj > __new();
		static ::hx::ObjectPtr< GenericStack_haxe_ds_StringMap_Dynamic_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~GenericStack_haxe_ds_StringMap_Dynamic_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(::Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("GenericStack_haxe_ds_StringMap_Dynamic",e6,8e,4d,8d); }

		 void add( ::haxe::ds::StringMap item);
		::hx::Callable< void ( ::haxe::ds::StringMap) > add_dyn();

		  ::haxe::ds::StringMap first();
		::hx::Callable<  ::haxe::ds::StringMap () > first_dyn();

		  ::haxe::ds::StringMap pop();
		::hx::Callable<  ::haxe::ds::StringMap () > pop_dyn();

		 bool isEmpty();
		::hx::Callable< bool () > isEmpty_dyn();

		 bool remove( ::haxe::ds::StringMap v);
		::hx::Callable< bool ( ::haxe::ds::StringMap) > remove_dyn();

		  ::Dynamic iterator();
		::hx::Callable<  ::Dynamic () > iterator_dyn();

		virtual ::String toString();
		::hx::Callable< ::String () > toString_dyn();

		 ::haxe::ds::GenericCell_haxe_ds_StringMap_Dynamic head;
};

} // end namespace haxe
} // end namespace ds

#endif /* INCLUDED_haxe_ds_GenericStack_haxe_ds_StringMap_Dynamic */ 
