// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_haxe_ds_ObjectMap
#define INCLUDED_haxe_ds_ObjectMap

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,ObjectMap)

namespace haxe{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES ObjectMap_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef ObjectMap_obj OBJ_;
		ObjectMap_obj();

	public:
		enum { _hx_ClassId = 0x6cba6d44 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true, const char* inName="haxe.ds.ObjectMap")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, true, "haxe.ds.ObjectMap"); }
		static ::hx::ObjectPtr< ObjectMap_obj > __new();
		static ::hx::ObjectPtr< ObjectMap_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~ObjectMap_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(::Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		void *_hx_getInterface(int inHash);
		int size_a5c03efb();

		 ::Dynamic get_a7a2487a( ::Dynamic k);

		void set_dca24b06( ::Dynamic k, ::Dynamic v);

		bool exists_64bfc92f( ::Dynamic k);

		bool remove_64bfc92f( ::Dynamic k);

		 ::Dynamic keys_2aa2127b();

		 ::Dynamic iterator_2aa2127b();

		 ::Dynamic keyValueIterator_2aa2127b();

		::Dynamic copy_ee952b4b();

		::String toString_cfeeb009();

		void clear_e5532386();

		::String __ToString() const { return HX_("ObjectMap",fd,a4,50,e5); }

		 void set( ::Dynamic key, ::Dynamic value);
		::hx::Callable< void ( ::Dynamic, ::Dynamic) > set_dyn();

		  ::Dynamic get( ::Dynamic key);
		::hx::Callable<  ::Dynamic ( ::Dynamic) > get_dyn();

		 bool exists( ::Dynamic key);
		::hx::Callable< bool ( ::Dynamic) > exists_dyn();

		 bool remove( ::Dynamic key);
		::hx::Callable< bool ( ::Dynamic) > remove_dyn();

		  ::Dynamic keys();
		::hx::Callable<  ::Dynamic () > keys_dyn();

		  ::Dynamic iterator();
		::hx::Callable<  ::Dynamic () > iterator_dyn();

		  ::Dynamic keyValueIterator();
		::hx::Callable<  ::Dynamic () > keyValueIterator_dyn();

		  ::haxe::ds::ObjectMap copy();
		::hx::Callable<  ::haxe::ds::ObjectMap () > copy_dyn();

		virtual ::String toString();
		::hx::Callable< ::String () > toString_dyn();

		 void clear();
		::hx::Callable< void () > clear_dyn();

		 int size();
		::hx::Callable< int () > size_dyn();

		 ::Dynamic h;

  inline void set(Dynamic key, ::null value) { __object_hash_set(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, bool value) { __object_hash_set(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, char value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, unsigned char value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, signed char value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, short value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, unsigned short value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, int value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, unsigned int value) { __object_hash_set_int(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, float value) { __object_hash_set_float(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, double value) { __object_hash_set_float(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, ::String value) { __object_hash_set_string(HX_MAP_THIS,key,value); }
  inline void set(Dynamic key, cpp::Int64 value) { __object_hash_set_int64(HX_MAP_THIS,key,value); }


  template<typename V, typename H>
  inline void set(Dynamic key, const ::cpp::Struct<V,H> &value) {__object_hash_set(HX_MAP_THIS,key,value); }
  template<typename V>
  inline void set(Dynamic key, const ::cpp::Function<V> &value) {__object_hash_set(HX_MAP_THIS,key,(Dynamic)value ); }
  template<typename V>
  inline void set(Dynamic key, const ::cpp::Pointer<V> &value) {__object_hash_set(HX_MAP_THIS,key,(Dynamic)value ); }

  inline bool get_bool(Dynamic key) { return __object_hash_get_bool(h,key); }
  inline int get_int(Dynamic key) { return __object_hash_get_int(h,key); }
  inline Float get_float(Dynamic key) { return __object_hash_get_float(h,key); }
  inline String get_string(Dynamic key) { return __object_hash_get_string(h,key); }
  inline cpp::Int64 get_int64(Dynamic key) { return __object_hash_get_int64(h,key); }

};

} // end namespace haxe
} // end namespace ds

#endif /* INCLUDED_haxe_ds_ObjectMap */ 
