package flash.net;

extern class NetStream extends flash.events.EventDispatcher {
	function new(connection : flash.net.NetConnection) : Void;
	function attachAudio(microphone : flash.media.Microphone) : Void;
	function attachCamera(theCamera : flash.media.Camera, ?snapshotMilliseconds : Int) : Void;
	var audioCodec(default,null) : UInt;
	var bufferLength(default,null) : Float;
	var bufferTime : Float;
	var bytesLoaded(default,null) : UInt;
	var bytesTotal(default,null) : UInt;
	var checkPolicyFile : Bool;
	var client : Dynamic;
	function close() : Void;
	var currentFPS(default,null) : Float;
	var decodedFrames(default,null) : UInt;
	var liveDelay(default,null) : Float;
	var objectEncoding(default,null) : UInt;
	function pause() : Void;
	function play( /* ...arguments */) : Void;
	function publish(?name : String, ?type : String) : Void;
	function receiveAudio(flag : Bool) : Void;
	function receiveVideo(flag : Bool) : Void;
	function resume() : Void;
	function seek(offset : Float) : Void;
	function send(handlerName : String /* ...arguments */) : Void;
	var soundTransform : flash.media.SoundTransform;
	var time(default,null) : Float;
	function togglePause() : Void;
	var videoCodec(default,null) : UInt;
	private function call(stream : flash.net.NetStream, command : String, responder : flash.net.Responder /* ...arguments */) : Void;
	private function construct(connection : flash.net.NetConnection) : Void;
	private function invoke(index : UInt /* ...arguments */) : Void;
	private function invokeWithArgsArray(index : UInt, p_arguments : Array<Dynamic>) : Void;
	private function onResult(streamId : Int) : Void;
	private function onStatus(info : Dynamic) : Void;
	private static var kAttachAudio : UInt;
	private static var kAttachVideo : UInt;
	private static var kCall : UInt;
	private static var kClose : UInt;
	private static var kGetAudioCodecID : UInt;
	private static var kGetBufferLength : UInt;
	private static var kGetBufferTime : UInt;
	private static var kGetBytesLoaded : UInt;
	private static var kGetBytesTotal : UInt;
	private static var kGetCurrentFps : UInt;
	private static var kGetLiveDelay : UInt;
	private static var kGetTime : UInt;
	private static var kGetTotalFrames : UInt;
	private static var kGetVideoCodecID : UInt;
	private static var kSend : UInt;
	private static var kSetAudioCodecID : UInt;
	private static var kSetBufferTime : UInt;
	private static var kSetTotalFrames : UInt;
	private static var kSetVideoCodecID : UInt;
}
