// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED_Lambda
#include <Lambda.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_dox_Api
#include <dox/Api.h>
#endif
#ifndef INCLUDED_dox_Config
#include <dox/Config.h>
#endif
#ifndef INCLUDED_dox_Generator
#include <dox/Generator.h>
#endif
#ifndef INCLUDED_dox_Infos
#include <dox/Infos.h>
#endif
#ifndef INCLUDED_dox_Writer
#include <dox/Writer.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_rtti_TypeTree
#include <haxe/rtti/TypeTree.h>
#endif
#ifndef INCLUDED_templo_Template
#include <templo/Template.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_a5cda18a72ed195f_17_new,"dox.Generator","new",0x7372c904,"dox.Generator.new","dox/Generator.hx",17,0x350cc06d)
HX_LOCAL_STACK_FRAME(_hx_pos_a5cda18a72ed195f_31_generate,"dox.Generator","generate",0x6dc79411,"dox.Generator.generate","dox/Generator.hx",31,0x350cc06d)
HX_LOCAL_STACK_FRAME(_hx_pos_a5cda18a72ed195f_34_generateNavigation,"dox.Generator","generateNavigation",0x76a28f05,"dox.Generator.generateNavigation","dox/Generator.hx",34,0x350cc06d)
HX_LOCAL_STACK_FRAME(_hx_pos_a5cda18a72ed195f_46_generateErrorPage,"dox.Generator","generateErrorPage",0x062517e6,"dox.Generator.generateErrorPage","dox/Generator.hx",46,0x350cc06d)
HX_LOCAL_STACK_FRAME(_hx_pos_a5cda18a72ed195f_65_generateTree,"dox.Generator","generateTree",0xacce360f,"dox.Generator.generateTree","dox/Generator.hx",65,0x350cc06d)
HX_LOCAL_STACK_FRAME(_hx_pos_a5cda18a72ed195f_127_fileUrl,"dox.Generator","fileUrl",0x270264f7,"dox.Generator.fileUrl","dox/Generator.hx",127,0x350cc06d)
HX_LOCAL_STACK_FRAME(_hx_pos_a5cda18a72ed195f_131_write,"dox.Generator","write",0x83a2d683,"dox.Generator.write","dox/Generator.hx",131,0x350cc06d)

namespace {

struct __Generator_objgenerate final : public ::hx::AutoCallable_obj< void (::Array< ::Dynamic>) > {
	::hx::ObjectPtr<dox::Generator_obj> __this;
	__Generator_objgenerate(::hx::ObjectPtr<dox::Generator_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Generator_objgenerate*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(::Array< ::Dynamic> root) override {
		__this->generate(root);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Generator_objgenerateNavigation final : public ::hx::AutoCallable_obj< void (::Array< ::Dynamic>) > {
	::hx::ObjectPtr<dox::Generator_obj> __this;
	__Generator_objgenerateNavigation(::hx::ObjectPtr<dox::Generator_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Generator_objgenerateNavigation*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(::Array< ::Dynamic> root) override {
		__this->generateNavigation(root);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Generator_objgenerateErrorPage final : public ::hx::AutoCallable_obj< void (::Array< ::Dynamic>) > {
	::hx::ObjectPtr<dox::Generator_obj> __this;
	__Generator_objgenerateErrorPage(::hx::ObjectPtr<dox::Generator_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Generator_objgenerateErrorPage*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(::Array< ::Dynamic> root) override {
		__this->generateErrorPage(root);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Generator_objgenerateTree final : public ::hx::AutoCallable_obj< void ( ::haxe::rtti::TypeTree) > {
	::hx::ObjectPtr<dox::Generator_obj> __this;
	__Generator_objgenerateTree(::hx::ObjectPtr<dox::Generator_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Generator_objgenerateTree*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN( ::haxe::rtti::TypeTree tree) override {
		__this->generateTree(tree);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Generator_objfileUrl final : public ::hx::AutoCallable_obj< ::String (::String) > {
	::hx::ObjectPtr<dox::Generator_obj> __this;
	__Generator_objfileUrl(::hx::ObjectPtr<dox::Generator_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Generator_objfileUrl*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::String HX_LOCAL_RUN(::String path) override {
		return __this->fileUrl(path);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Generator_objwrite final : public ::hx::AutoCallable_obj< void (::String,::String) > {
	::hx::ObjectPtr<dox::Generator_obj> __this;
	__Generator_objwrite(::hx::ObjectPtr<dox::Generator_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Generator_objwrite*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(::String fileUrl,::String content) override {
		__this->write(fileUrl, content);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

}

namespace dox{

void Generator_obj::__construct( ::dox::Api api, ::dox::Writer writer){
            	HX_STACKFRAME(&_hx_pos_a5cda18a72ed195f_17_new)
HXLINE(  18)		this->api = api;
HXLINE(  19)		this->writer = writer;
HXLINE(  20)		 ::dox::Config config = api->config;
HXLINE(  21)		this->tplNav = config->loadTemplate(HX_("nav.mtt",22,66,da,b6));
HXLINE(  22)		this->tplPackage = config->loadTemplate(HX_("package.mtt",45,52,8f,ef));
HXLINE(  23)		this->tplClass = config->loadTemplate(HX_("class.mtt",f7,df,1f,c7));
HXLINE(  24)		this->tplEnum = config->loadTemplate(HX_("enum.mtt",40,6b,49,18));
HXLINE(  25)		this->tplTypedef = config->loadTemplate(HX_("typedef.mtt",8a,24,88,9c));
HXLINE(  26)		this->tplAbstract = config->loadTemplate(HX_("abstract.mtt",a1,c5,28,ee));
HXLINE(  27)		this->tplError = config->loadTemplate(HX_("404.mtt",f7,86,0e,b3));
            	}

::Dynamic Generator_obj::__CreateEmpty() { return new Generator_obj; }

void* Generator_obj::_hx_vtable = 0;

::Dynamic Generator_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Generator_obj > _hx_result = new Generator_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool Generator_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x1e97372a;
}

void Generator_obj::generate(::Array< ::Dynamic> root){
            	HX_STACKFRAME(&_hx_pos_a5cda18a72ed195f_31_generate)
HXDLIN(  31)		::Lambda_obj::iter(root,this->generateTree_dyn());
            	}


::hx::Callable< void (::Array< ::Dynamic>) > Generator_obj::generate_dyn() { return new __Generator_objgenerate(this); }

void Generator_obj::generateNavigation(::Array< ::Dynamic> root){
            	HX_GC_STACKFRAME(&_hx_pos_a5cda18a72ed195f_34_generateNavigation)
HXLINE(  35)		this->api->config->rootPath = HX_("::rootPath::",27,56,99,f7);
HXLINE(  36)		 ::templo::Template s = this->tplNav;
HXLINE(  37)		 ::dox::Api s1 = this->api;
HXLINE(  38)		::Array< ::Dynamic> s2;
HXDLIN(  38)		if ((root->length == 1)) {
HXLINE(  38)			 ::haxe::rtti::TypeTree _ga = root->__get(0).StaticCast<  ::haxe::rtti::TypeTree >();
HXDLIN(  38)			if ((_ga->_hx_getIndex() == 0)) {
HXLINE(  39)				if ((_ga->_hx_getString(1) == HX_("",00,00,00,00))) {
HXLINE(  39)					::Array< ::Dynamic> subs = _ga->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXLINE(  38)					s2 = subs;
            				}
            				else {
HXLINE(  40)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("root should be [top level package]",6b,e1,be,ac)));
            				}
            			}
            			else {
HXLINE(  40)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("root should be [top level package]",6b,e1,be,ac)));
            			}
            		}
            		else {
HXLINE(  40)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("root should be [top level package]",6b,e1,be,ac)));
            		}
HXLINE(  36)		::String s3 = s->execute( ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("api",9a,fc,49,00),s1)
            			->setFixed(1,HX_("root",22,ee,ae,4b),s2)));
HXLINE(  43)		 ::dox::Writer _hx_tmp = this->writer;
HXDLIN(  43)		_hx_tmp->saveContent(HX_("nav.js",74,67,42,23), ::EReg_obj::__alloc( HX_CTX ,HX_("[\r\n\t]",ac,2e,16,6e),HX_("g",67,00,00,00))->replace(s3,HX_("",00,00,00,00)));
            	}


::hx::Callable< void (::Array< ::Dynamic>) > Generator_obj::generateNavigation_dyn() { return new __Generator_objgenerateNavigation(this); }

void Generator_obj::generateErrorPage(::Array< ::Dynamic> root){
            	HX_GC_STACKFRAME(&_hx_pos_a5cda18a72ed195f_46_generateErrorPage)
HXLINE(  47)		::String full = HX_("File not found",f1,c8,80,8d);
HXLINE(  48)		::String name = HX_("File not found",f1,c8,80,8d);
HXLINE(  49)		this->api->config->setRootPath(HX_("",00,00,00,00));
HXLINE(  50)		::String _hx_tmp;
HXDLIN(  50)		if ((full == HX_("",00,00,00,00))) {
HXLINE(  50)			_hx_tmp = name;
            		}
            		else {
HXLINE(  50)			_hx_tmp = full;
            		}
HXDLIN(  50)		this->api->currentPageName = _hx_tmp;
HXLINE(  51)		 ::templo::Template s = this->tplError;
HXLINE(  52)		 ::dox::Api s1 = this->api;
HXLINE(  55)		::Array< ::Dynamic> s2;
HXDLIN(  55)		if ((root->length == 1)) {
HXLINE(  55)			 ::haxe::rtti::TypeTree _ga = root->__get(0).StaticCast<  ::haxe::rtti::TypeTree >();
HXDLIN(  55)			if ((_ga->_hx_getIndex() == 0)) {
HXLINE(  56)				if ((_ga->_hx_getString(1) == HX_("",00,00,00,00))) {
HXLINE(  56)					::Array< ::Dynamic> subs = _ga->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXLINE(  55)					s2 = subs;
            				}
            				else {
HXLINE(  57)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("root should be [top level package]",6b,e1,be,ac)));
            				}
            			}
            			else {
HXLINE(  57)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("root should be [top level package]",6b,e1,be,ac)));
            			}
            		}
            		else {
HXLINE(  57)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("root should be [top level package]",6b,e1,be,ac)));
            		}
HXLINE(  51)		::String s3 = s->execute( ::Dynamic(::hx::Anon_obj::Create(4)
            			->setFixed(0,HX_("api",9a,fc,49,00),s1)
            			->setFixed(1,HX_("full",8f,e9,c4,43),full)
            			->setFixed(2,HX_("name",4b,72,ff,48),name)
            			->setFixed(3,HX_("root",22,ee,ae,4b),s2)));
HXLINE(  60)		 ::dox::Writer _hx_tmp1 = this->writer;
HXDLIN(  60)		_hx_tmp1->saveContent(HX_("404.html",61,7a,59,f6), ::EReg_obj::__alloc( HX_CTX ,HX_("[\r\n\t]",ac,2e,16,6e),HX_("g",67,00,00,00))->replace(s3,HX_("",00,00,00,00)));
            	}


::hx::Callable< void (::Array< ::Dynamic>) > Generator_obj::generateErrorPage_dyn() { return new __Generator_objgenerateErrorPage(this); }

void Generator_obj::generateTree( ::haxe::rtti::TypeTree tree){
            	HX_STACKFRAME(&_hx_pos_a5cda18a72ed195f_65_generateTree)
HXDLIN(  65)		switch((int)(tree->_hx_getIndex())){
            			case (int)0: {
HXLINE(  66)				::String name = tree->_hx_getString(0);
HXDLIN(  66)				::String full = tree->_hx_getString(1);
HXDLIN(  66)				::Array< ::Dynamic> subs = tree->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXDLIN(  66)				{
HXLINE(  67)					if ((name.charAt(0) == HX_("_",5f,00,00,00))) {
HXLINE(  68)						return;
            					}
HXLINE(  69)					::String _hx_tmp;
HXDLIN(  69)					if ((full == HX_("",00,00,00,00))) {
HXLINE(  69)						_hx_tmp = name;
            					}
            					else {
HXLINE(  69)						_hx_tmp = full;
            					}
HXDLIN(  69)					this->api->currentPageName = _hx_tmp;
HXLINE(  70)					::String _hx_tmp1;
HXDLIN(  70)					if ((full == HX_("",00,00,00,00))) {
HXLINE(  70)						_hx_tmp1 = full;
            					}
            					else {
HXLINE(  70)						_hx_tmp1 = (full + HX_(".pack",07,86,c0,c6));
            					}
HXDLIN(  70)					this->api->config->setRootPath(_hx_tmp1);
HXLINE(  71)					::String _hx_tmp2;
HXDLIN(  71)					if ((full == HX_("",00,00,00,00))) {
HXLINE(  71)						_hx_tmp2 = HX_("index",12,9b,14,be);
            					}
            					else {
HXLINE(  71)						_hx_tmp2 = (full + HX_(".index",24,34,7f,22));
            					}
HXDLIN(  71)					this->api->currentPageUrl = this->fileUrl(_hx_tmp2);
HXLINE(  72)					::String s = this->tplPackage->execute( ::Dynamic(::hx::Anon_obj::Create(4)
            						->setFixed(0,HX_("api",9a,fc,49,00),this->api)
            						->setFixed(1,HX_("full",8f,e9,c4,43),full)
            						->setFixed(2,HX_("name",4b,72,ff,48),name)
            						->setFixed(3,HX_("subs",f3,a6,5c,4c),subs)));
HXLINE(  78)					this->write(this->api->currentPageUrl,s);
HXLINE(  79)					this->api->infos->numGeneratedPackages++;
HXLINE(  80)					::Lambda_obj::iter(subs,this->generateTree_dyn());
            				}
            			}
            			break;
            			case (int)1: {
HXLINE(  81)				 ::Dynamic c = tree->_hx_getObject(0);
HXDLIN(  81)				{
HXLINE(  82)					this->api->currentPageName = ( (::String)(c->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) );
HXLINE(  83)					this->api->config->setRootPath(( (::String)(c->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXLINE(  84)					::String _hx_tmp3 = this->api->sanitizePath(( (::String)(c->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXDLIN(  84)					this->api->currentPageUrl = this->fileUrl(_hx_tmp3);
HXLINE(  85)					 ::templo::Template s1 = this->tplClass;
HXLINE(  86)					 ::dox::Api s2 = this->api;
HXLINE(  88)					::Array< ::Dynamic> s3 = ( (::Array< ::Dynamic>)(this->api->infos->subClasses->get(( (::String)(c->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ))) );
HXLINE(  85)					::String s4 = s1->execute( ::Dynamic(::hx::Anon_obj::Create(4)
            						->setFixed(0,HX_("subClasses",06,fd,fa,e5),s3)
            						->setFixed(1,HX_("api",9a,fc,49,00),s2)
            						->setFixed(2,HX_("implementors",2d,94,4f,3f),( (::Array< ::Dynamic>)(this->api->infos->implementors->get(( (::String)(c->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ))) ))
            						->setFixed(3,HX_("type",ba,f2,08,4d),c)));
HXLINE(  91)					this->write(this->api->currentPageUrl,s4);
HXLINE(  92)					 ::dox::Infos fh = this->api->infos;
HXDLIN(  92)					fh->set_numGeneratedTypes((fh->numGeneratedTypes + 1));
            				}
            			}
            			break;
            			case (int)2: {
HXLINE(  93)				 ::Dynamic e = tree->_hx_getObject(0);
HXDLIN(  93)				{
HXLINE(  94)					this->api->currentPageName = ( (::String)(e->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) );
HXLINE(  95)					this->api->config->setRootPath(( (::String)(e->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXLINE(  96)					::String _hx_tmp4 = this->api->sanitizePath(( (::String)(e->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXDLIN(  96)					this->api->currentPageUrl = this->fileUrl(_hx_tmp4);
HXLINE(  97)					::String s5 = this->tplEnum->execute( ::Dynamic(::hx::Anon_obj::Create(2)
            						->setFixed(0,HX_("api",9a,fc,49,00),this->api)
            						->setFixed(1,HX_("type",ba,f2,08,4d),e)));
HXLINE( 101)					this->write(this->api->currentPageUrl,s5);
HXLINE( 102)					 ::dox::Infos fh1 = this->api->infos;
HXDLIN( 102)					fh1->set_numGeneratedTypes((fh1->numGeneratedTypes + 1));
            				}
            			}
            			break;
            			case (int)3: {
HXLINE( 103)				 ::Dynamic t = tree->_hx_getObject(0);
HXDLIN( 103)				{
HXLINE( 104)					this->api->currentPageName = ( (::String)(t->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) );
HXLINE( 105)					this->api->config->setRootPath(( (::String)(t->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXLINE( 106)					::String _hx_tmp5 = this->api->sanitizePath(( (::String)(t->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXDLIN( 106)					this->api->currentPageUrl = this->fileUrl(_hx_tmp5);
HXLINE( 107)					::String s6 = this->tplTypedef->execute( ::Dynamic(::hx::Anon_obj::Create(2)
            						->setFixed(0,HX_("api",9a,fc,49,00),this->api)
            						->setFixed(1,HX_("type",ba,f2,08,4d),t)));
HXLINE( 111)					this->write(this->api->currentPageUrl,s6);
HXLINE( 112)					 ::dox::Infos fh2 = this->api->infos;
HXDLIN( 112)					fh2->set_numGeneratedTypes((fh2->numGeneratedTypes + 1));
            				}
            			}
            			break;
            			case (int)4: {
HXLINE( 113)				 ::Dynamic a = tree->_hx_getObject(0);
HXDLIN( 113)				{
HXLINE( 114)					this->api->currentPageName = ( (::String)(a->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) );
HXLINE( 115)					this->api->config->setRootPath(( (::String)(a->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXLINE( 116)					::String _hx_tmp6 = this->api->sanitizePath(( (::String)(a->__Field(HX_("path",a5,e5,51,4a),::hx::paccDynamic)) ));
HXDLIN( 116)					this->api->currentPageUrl = this->fileUrl(_hx_tmp6);
HXLINE( 117)					::String s7 = this->tplAbstract->execute( ::Dynamic(::hx::Anon_obj::Create(2)
            						->setFixed(0,HX_("api",9a,fc,49,00),this->api)
            						->setFixed(1,HX_("type",ba,f2,08,4d),a)));
HXLINE( 121)					this->write(this->api->currentPageUrl,s7);
HXLINE( 122)					 ::dox::Infos fh3 = this->api->infos;
HXDLIN( 122)					fh3->set_numGeneratedTypes((fh3->numGeneratedTypes + 1));
            				}
            			}
            			break;
            		}
            	}


::hx::Callable< void ( ::haxe::rtti::TypeTree) > Generator_obj::generateTree_dyn() { return new __Generator_objgenerateTree(this); }

::String Generator_obj::fileUrl(::String path){
            	HX_STACKFRAME(&_hx_pos_a5cda18a72ed195f_127_fileUrl)
HXDLIN( 127)		return (::StringTools_obj::replace(::StringTools_obj::replace(::StringTools_obj::replace(path,HX_(".",2e,00,00,00),HX_("/",2f,00,00,00)),HX_("<",3c,00,00,00),HX_("_",5f,00,00,00)),HX_(">",3e,00,00,00),HX_("_",5f,00,00,00)) + HX_(".html",99,44,85,c1));
            	}


::hx::Callable< ::String (::String) > Generator_obj::fileUrl_dyn() { return new __Generator_objfileUrl(this); }

void Generator_obj::write(::String fileUrl,::String content){
            	HX_STACKFRAME(&_hx_pos_a5cda18a72ed195f_131_write)
HXDLIN( 131)		this->writer->saveContent(fileUrl,content);
            	}


::hx::Callable< void (::String,::String) > Generator_obj::write_dyn() { return new __Generator_objwrite(this); }


::hx::ObjectPtr< Generator_obj > Generator_obj::__new( ::dox::Api api, ::dox::Writer writer) {
	::hx::ObjectPtr< Generator_obj > __this = new Generator_obj();
	__this->__construct(api,writer);
	return __this;
}

::hx::ObjectPtr< Generator_obj > Generator_obj::__alloc(::hx::Ctx *_hx_ctx, ::dox::Api api, ::dox::Writer writer) {
	Generator_obj* __this = (Generator_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Generator_obj), true, "dox.Generator"));
	*(void **)__this = Generator_obj::_hx_vtable;
	__this->__construct(api,writer);
	return __this;
}

Generator_obj::Generator_obj()
{
}

void Generator_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Generator);
	HX_MARK_MEMBER_NAME(api, "api");
	HX_MARK_MEMBER_NAME(writer, "writer");
	HX_MARK_MEMBER_NAME(tplNav, "tplNav");
	HX_MARK_MEMBER_NAME(tplPackage, "tplPackage");
	HX_MARK_MEMBER_NAME(tplClass, "tplClass");
	HX_MARK_MEMBER_NAME(tplEnum, "tplEnum");
	HX_MARK_MEMBER_NAME(tplTypedef, "tplTypedef");
	HX_MARK_MEMBER_NAME(tplAbstract, "tplAbstract");
	HX_MARK_MEMBER_NAME(tplError, "tplError");
	HX_MARK_END_CLASS();
}

void Generator_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(api, "api");
	HX_VISIT_MEMBER_NAME(writer, "writer");
	HX_VISIT_MEMBER_NAME(tplNav, "tplNav");
	HX_VISIT_MEMBER_NAME(tplPackage, "tplPackage");
	HX_VISIT_MEMBER_NAME(tplClass, "tplClass");
	HX_VISIT_MEMBER_NAME(tplEnum, "tplEnum");
	HX_VISIT_MEMBER_NAME(tplTypedef, "tplTypedef");
	HX_VISIT_MEMBER_NAME(tplAbstract, "tplAbstract");
	HX_VISIT_MEMBER_NAME(tplError, "tplError");
}

::hx::Val Generator_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"api") ) { return ::hx::Val( api ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"write") ) { return ::hx::Val( write_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"writer") ) { return ::hx::Val( writer ); }
		if (HX_FIELD_EQ(inName,"tplNav") ) { return ::hx::Val( tplNav ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"fileUrl") ) { return ::hx::Val( fileUrl_dyn() ); }
		if (HX_FIELD_EQ(inName,"tplEnum") ) { return ::hx::Val( tplEnum ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"generate") ) { return ::hx::Val( generate_dyn() ); }
		if (HX_FIELD_EQ(inName,"tplClass") ) { return ::hx::Val( tplClass ); }
		if (HX_FIELD_EQ(inName,"tplError") ) { return ::hx::Val( tplError ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"tplPackage") ) { return ::hx::Val( tplPackage ); }
		if (HX_FIELD_EQ(inName,"tplTypedef") ) { return ::hx::Val( tplTypedef ); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"tplAbstract") ) { return ::hx::Val( tplAbstract ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"generateTree") ) { return ::hx::Val( generateTree_dyn() ); }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"generateErrorPage") ) { return ::hx::Val( generateErrorPage_dyn() ); }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"generateNavigation") ) { return ::hx::Val( generateNavigation_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Generator_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"api") ) { api = inValue.Cast<  ::dox::Api >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"writer") ) { writer = inValue.Cast<  ::dox::Writer >(); return inValue; }
		if (HX_FIELD_EQ(inName,"tplNav") ) { tplNav = inValue.Cast<  ::templo::Template >(); return inValue; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"tplEnum") ) { tplEnum = inValue.Cast<  ::templo::Template >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"tplClass") ) { tplClass = inValue.Cast<  ::templo::Template >(); return inValue; }
		if (HX_FIELD_EQ(inName,"tplError") ) { tplError = inValue.Cast<  ::templo::Template >(); return inValue; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"tplPackage") ) { tplPackage = inValue.Cast<  ::templo::Template >(); return inValue; }
		if (HX_FIELD_EQ(inName,"tplTypedef") ) { tplTypedef = inValue.Cast<  ::templo::Template >(); return inValue; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"tplAbstract") ) { tplAbstract = inValue.Cast<  ::templo::Template >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Generator_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("api",9a,fc,49,00));
	outFields->push(HX_("writer",b3,d6,e5,7d));
	outFields->push(HX_("tplNav",53,63,e5,25));
	outFields->push(HX_("tplPackage",f6,b9,a6,9b));
	outFields->push(HX_("tplClass",a8,8a,50,26));
	outFields->push(HX_("tplEnum",91,76,e8,fc));
	outFields->push(HX_("tplTypedef",bb,c5,cd,52));
	outFields->push(HX_("tplAbstract",72,d4,65,05));
	outFields->push(HX_("tplError",38,de,21,51));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Generator_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /*  ::dox::Api */ , (int)offsetof(Generator_obj, api), HX_("api",9a,fc,49,00) },
	{ ::hx::fsObject /*  ::dox::Writer */ , (int)offsetof(Generator_obj, writer), HX_("writer",b3,d6,e5,7d) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplNav), HX_("tplNav",53,63,e5,25) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplPackage), HX_("tplPackage",f6,b9,a6,9b) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplClass), HX_("tplClass",a8,8a,50,26) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplEnum), HX_("tplEnum",91,76,e8,fc) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplTypedef), HX_("tplTypedef",bb,c5,cd,52) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplAbstract), HX_("tplAbstract",72,d4,65,05) },
	{ ::hx::fsObject /*  ::templo::Template */ , (int)offsetof(Generator_obj, tplError), HX_("tplError",38,de,21,51) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo* Generator_obj_sStaticStorageInfo = 0;
#endif

static ::String Generator_obj_sMemberFields[] = {
	HX_("generate",35,5f,a2,d9),
	HX_("generateNavigation",29,2f,50,75),
	HX_("generateErrorPage",42,c8,91,66),
	HX_("generateTree",33,63,d7,1f),
	HX_("fileUrl",53,4a,50,ff),
	HX_("write",df,6c,59,d0),
	HX_("api",9a,fc,49,00),
	HX_("writer",b3,d6,e5,7d),
	HX_("tplNav",53,63,e5,25),
	HX_("tplPackage",f6,b9,a6,9b),
	HX_("tplClass",a8,8a,50,26),
	HX_("tplEnum",91,76,e8,fc),
	HX_("tplTypedef",bb,c5,cd,52),
	HX_("tplAbstract",72,d4,65,05),
	HX_("tplError",38,de,21,51),
	::String(null())
};

::hx::Class Generator_obj::__mClass;

static ::String* Generator_obj_sStaticFields = 0;

void Generator_obj::__register()
{
	Generator_obj _hx_dummy;
	Generator_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("dox.Generator",12,37,19,ed);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Generator_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Generator_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Generator_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Generator_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Generator_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace dox
