// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_ds_List
#include <haxe/ds/List.h>
#endif
#ifndef INCLUDED_hxparse_Position
#include <hxparse/Position.h>
#endif
#ifndef INCLUDED_templo__Converter_Block
#include <templo/_Converter/Block.h>
#endif
#ifndef INCLUDED_templo__Converter_BlockType
#include <templo/_Converter/BlockType.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_60e42f1751bf7715_209_new,"templo._Converter.Block","new",0xd5c255e9,"templo._Converter.Block.new","templo/Converter.hx",209,0x5e847376)
HX_LOCAL_STACK_FRAME(_hx_pos_60e42f1751bf7715_216_toString,"templo._Converter.Block","toString",0x32229a83,"templo._Converter.Block.toString","templo/Converter.hx",216,0x5e847376)

namespace {

struct __Block_objtoString final : public ::hx::AutoCallable_obj< ::String () > {
	::hx::ObjectPtr<templo::_Converter::Block_obj> __this;
	__Block_objtoString(::hx::ObjectPtr<templo::_Converter::Block_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Block_objtoString*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::String HX_LOCAL_RUN() override {
		return __this->toString();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

}

namespace templo{
namespace _Converter{

void Block_obj::__construct( ::templo::_Converter::BlockType type, ::hxparse::Position pos){
            	HX_GC_STACKFRAME(&_hx_pos_60e42f1751bf7715_209_new)
HXLINE( 210)		this->type = type;
HXLINE( 211)		this->elements =  ::haxe::ds::List_obj::__alloc( HX_CTX );
HXLINE( 212)		this->pos = pos;
            	}

::Dynamic Block_obj::__CreateEmpty() { return new Block_obj; }

void* Block_obj::_hx_vtable = 0;

::Dynamic Block_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Block_obj > _hx_result = new Block_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool Block_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x3e0d6615;
}

::String Block_obj::toString(){
            	HX_STACKFRAME(&_hx_pos_60e42f1751bf7715_216_toString)
HXDLIN( 216)		switch((int)(this->type->_hx_getIndex())){
            			case (int)0: {
HXLINE( 217)				return HX_("{}",a2,6b,00,00);
            			}
            			break;
            			case (int)1: {
HXLINE( 218)				return HX_("if",dd,5b,00,00);
            			}
            			break;
            			case (int)2: {
HXLINE( 219)				return HX_("elseif",d6,a0,a2,dd);
            			}
            			break;
            			case (int)3: {
HXLINE( 220)				return HX_("else",b9,e4,14,43);
            			}
            			break;
            			case (int)4: {
HXLINE( 221)				return HX_("foreach",8a,fd,e4,d9);
            			}
            			break;
            			case (int)5: {
HXLINE( 222)				return HX_("fill",83,ce,bb,43);
            			}
            			break;
            			case (int)6: {
HXLINE( 223)				return HX_("switch",f4,49,79,c5);
            			}
            			break;
            			case (int)7: {
HXLINE( 224)				return HX_("case",b0,1e,ba,41);
            			}
            			break;
            			case (int)8: {
HXLINE( 225)				return HX_("use",47,2c,59,00);
            			}
            			break;
            		}
HXLINE( 216)		return null();
            	}


::hx::Callable< ::String () > Block_obj::toString_dyn() { return new __Block_objtoString(this); }


::hx::ObjectPtr< Block_obj > Block_obj::__new( ::templo::_Converter::BlockType type, ::hxparse::Position pos) {
	::hx::ObjectPtr< Block_obj > __this = new Block_obj();
	__this->__construct(type,pos);
	return __this;
}

::hx::ObjectPtr< Block_obj > Block_obj::__alloc(::hx::Ctx *_hx_ctx, ::templo::_Converter::BlockType type, ::hxparse::Position pos) {
	Block_obj* __this = (Block_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Block_obj), true, "templo._Converter.Block"));
	*(void **)__this = Block_obj::_hx_vtable;
	__this->__construct(type,pos);
	return __this;
}

Block_obj::Block_obj()
{
}

void Block_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Block);
	HX_MARK_MEMBER_NAME(type, "type");
	HX_MARK_MEMBER_NAME(elements, "elements");
	HX_MARK_MEMBER_NAME(pos, "pos");
	HX_MARK_END_CLASS();
}

void Block_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(type, "type");
	HX_VISIT_MEMBER_NAME(elements, "elements");
	HX_VISIT_MEMBER_NAME(pos, "pos");
}

::hx::Val Block_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { return ::hx::Val( pos ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"type") ) { return ::hx::Val( type ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"toString") ) { return ::hx::Val( toString_dyn() ); }
		if (HX_FIELD_EQ(inName,"elements") ) { return ::hx::Val( elements ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Block_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { pos = inValue.Cast<  ::hxparse::Position >(); return inValue; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"type") ) { type = inValue.Cast<  ::templo::_Converter::BlockType >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"elements") ) { elements = inValue.Cast<  ::haxe::ds::List >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Block_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("type",ba,f2,08,4d));
	outFields->push(HX_("elements",37,36,c4,83));
	outFields->push(HX_("pos",94,5d,55,00));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Block_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /*  ::templo::_Converter::BlockType */ , (int)offsetof(Block_obj, type), HX_("type",ba,f2,08,4d) },
	{ ::hx::fsObject /*  ::haxe::ds::List */ , (int)offsetof(Block_obj, elements), HX_("elements",37,36,c4,83) },
	{ ::hx::fsObject /*  ::hxparse::Position */ , (int)offsetof(Block_obj, pos), HX_("pos",94,5d,55,00) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo* Block_obj_sStaticStorageInfo = 0;
#endif

static ::String Block_obj_sMemberFields[] = {
	HX_("toString",ac,d0,6e,38),
	HX_("type",ba,f2,08,4d),
	HX_("elements",37,36,c4,83),
	HX_("pos",94,5d,55,00),
	::String(null())
};

::hx::Class Block_obj::__mClass;

static ::String* Block_obj_sStaticFields = 0;

void Block_obj::__register()
{
	Block_obj _hx_dummy;
	Block_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("templo._Converter.Block",77,2d,bd,07);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Block_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Block_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Block_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Block_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Block_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace templo
} // end namespace _Converter
