package flash.media;

extern class AVCaptionStyle {
	var backgroundColor : String;
	var backgroundOpacity : String;
	var bottomInset : String;
	var edgeColor : String;
	var fillColor : String;
	var fillOpacity : String;
	var font : String;
	var fontColor : String;
	var fontEdge : String;
	var fontOpacity : String;
	var size : String;
	function new() : Void;
	static final BLACK : String;
	static final BLUE : String;
	static final BRIGHT_BLUE : String;
	static final BRIGHT_CYAN : String;
	static final BRIGHT_GREEN : String;
	static final BRIGHT_MAGENTA : String;
	static final BRIGHT_RED : String;
	static final BRIGHT_WHITE : String;
	static final BRIGHT_YELLOW : String;
	static final CASUAL : String;
	static final CURSIVE : String;
	static final CYAN : String;
	static final DARK_BLUE : String;
	static final DARK_CYAN : String;
	static final DARK_GREEN : String;
	static final DARK_MAGENTA : String;
	static final DARK_RED : String;
	static final DARK_YELLOW : String;
	static final DEFAULT : String;
	static final DEPRESSED : String;
	static final GRAY : String;
	static final GREEN : String;
	static final LARGE : String;
	static final LEFT_DROP_SHADOW : String;
	static final MAGENTA : String;
	static final MEDIUM : String;
	static final MONOSPACED_WITHOUT_SERIFS : String;
	static final MONOSPACE_WITH_SERIFS : String;
	static final NONE : String;
	static final PROPORTIONAL_WITHOUT_SERIFS : String;
	static final PROPORTIONAL_WITH_SERIFS : String;
	static final RAISED : String;
	static final RED : String;
	static final RIGHT_DROP_SHADOW : String;
	static final SMALL : String;
	static final SMALL_CAPITALS : String;
	static final UNIFORM : String;
	static final WHITE : String;
	static final YELLOW : String;
}
