package flash.media;

extern class AVCaptionStyle {
	var backgroundColor : String;
	var backgroundOpacity : String;
	var edgeColor : String;
	var fillColor : String;
	var fillOpacity : String;
	var font : String;
	var fontColor : String;
	var fontEdge : String;
	var fontOpacity : String;
	var size : String;
	function new() : Void;
	static var BLACK : String;
	static var BLUE : String;
	static var BRIGHT_BLUE : String;
	static var BRIGHT_CYAN : String;
	static var BRIGHT_GREEN : String;
	static var BRIGHT_MAGENTA : String;
	static var BRIGHT_RED : String;
	static var BRIGHT_WHITE : String;
	static var BRIGHT_YELLOW : String;
	static var CASUAL : String;
	static var CURSIVE : String;
	static var CYAN : String;
	static var DARK_BLUE : String;
	static var DARK_CYAN : String;
	static var DARK_GREEN : String;
	static var DARK_MAGENTA : String;
	static var DARK_RED : String;
	static var DARK_YELLOW : String;
	static var DEFAULT : String;
	static var DEPRESSED : String;
	static var GRAY : String;
	static var GREEN : String;
	static var LARGE : String;
	static var LEFT_DROP_SHADOW : String;
	static var MAGENTA : String;
	static var MEDIUM : String;
	static var MONOSPACED_WITHOUT_SERIFS : String;
	static var MONOSPACE_WITH_SERIFS : String;
	static var NONE : String;
	static var PROPORTIONAL_WITHOUT_SERIFS : String;
	static var PROPORTIONAL_WITH_SERIFS : String;
	static var RAISED : String;
	static var RED : String;
	static var RIGHT_DROP_SHADOW : String;
	static var SMALL : String;
	static var SMALL_CAPITALS : String;
	static var UNIFORM : String;
	static var WHITE : String;
	static var YELLOW : String;
}
