package flash.media;

extern class AVResult {
	var result(default,null) : Int;
	function new(inResult : Int) : Void;
	static var ASYNC_OPERATION_IN_PROGRESS : Int;
	static var BAD_MANIFEST_SIGNATURE : Int;
	static var BAD_MEDIA_INTERLEAVING : Int;
	static var CALLED_FROM_WRONG_THREAD : Int;
	static var CANNOT_FAIL_OVER : Int;
	static var CANNOT_LOAD_PLAY_LIST : Int;
	static var CODEC_NOT_SUPPORTED : Int;
	static var COMPONENT_CREATION_FAILURE : Int;
	static var CONTAINER_NOT_SUPPORTED : Int;
	static var CONTENT_LENGTH_MISMATCH : Int;
	static var CURRENT_PERIOD_EXPIRED : Int;
	static var DECODER_FAILED : Int;
	static var DEVICE_OPEN_ERROR : Int;
	static var DRM_INIT_ERROR : Int;
	static var DRM_NOT_AVAILABLE : Int;
	static var EOF : Int;
	static var FILE_NOT_FOUND : Int;
	static var FILE_STRUCTURE_INVALID : Int;
	static var FRAGMENT_READ_ERROR : Int;
	static var GENERIC_ERROR : Int;
	static var HTTP_TIME_OUT : Int;
	static var INVALID_OPERATION : Int;
	static var INVALID_PARAMETER : Int;
	static var INVALID_REPLACE_DURATION : Int;
	static var INVALID_SEEK_TIME : Int;
	static var INVALID_WITH_AUDIO_ONLY_FILE : Int;
	static var IRRECOVERABLE_ERROR : Int;
	static var LIVE_HOLD : Int;
	static var LIVE_WINDOW_MOVED_BACKWARD : Int;
	static var LOST_CONNECTION_RECOVERABLE : Int;
	static var NETWORK_DOWN : Int;
	static var NETWORK_ERROR : Int;
	static var NETWORK_UNAVAILABLE : Int;
	static var NOT_IMPLEMENTED : Int;
	static var NO_FIXED_SIZE : Int;
	static var NO_USEABLE_BITRATE_PROFILE : Int;
	static var ONLY_ALLOWED_IN_PAUSED_STATE : Int;
	static var OPERATION_ABORTED : Int;
	static var OUT_OF_MEMORY : Int;
	static var OVERFLOW : Int;
	static var PARSE_ERROR : Int;
	static var PERIOD_HOLD : Int;
	static var PERIOD_NOT_LOADED : Int;
	static var PLAYBACK_NOT_ENABLED : Int;
	static var PREVIOUS_STEP_SEEK_IN_PROGRESS : Int;
	static var RANGE_ERROR : Int;
	static var REPLACEMENT_FAILED : Int;
	static var RESOURCE_NOT_SPECIFIED : Int;
	static var SEEK_FAILED : Int;
	static var SIZE_UNKNOWN : Int;
	static var SUCCESS : Int;
	static var SWITCH_TO_ASYMMETRIC_PROFILE : Int;
	static var UNDERFLOW : Int;
	static var UNSUPPORTED_CONFIGURATION : Int;
	static var UNSUPPORTED_HLS_VERSION : Int;
	static var UNSUPPORTED_OPERATION : Int;
	static var VIDEO_PROFILE_NOT_SUPPORTED : Int;
	static var WAITING_FOR_INIT : Int;
}
