package flash.media;

extern final class Camera extends flash.events.EventDispatcher {
	var activityLevel(get,never) : Float;
	var bandwidth(get,never) : Int;
	var currentFPS(get,never) : Float;
	var fps(get,never) : Float;
	var height(get,never) : Int;
	var index(get,never) : Int;
	var keyFrameInterval(get,never) : Int;
	var loopback(get,never) : Bool;
	var motionLevel(get,never) : Int;
	var motionTimeout(get,never) : Int;
	var muted(get,never) : Bool;
	var name(get,never) : String;
	@:require(flash11_2) var position(get,never) : String;
	var quality(get,never) : Int;
	var width(get,never) : Int;
	function new() : Void;
	@:require(flash11_4) function copyToByteArray(rect : flash.geom.Rectangle, destination : flash.utils.ByteArray) : Void;
	@:require(flash11_4) function copyToVector(rect : flash.geom.Rectangle, destination : flash.Vector<UInt>) : Void;
	@:require(flash11_4) function drawToBitmapData(destination : flash.display.BitmapData) : Void;
	private function get_activityLevel() : Float;
	private function get_bandwidth() : Int;
	private function get_currentFPS() : Float;
	private function get_fps() : Float;
	private function get_height() : Int;
	private function get_index() : Int;
	private function get_keyFrameInterval() : Int;
	private function get_loopback() : Bool;
	private function get_motionLevel() : Int;
	private function get_motionTimeout() : Int;
	private function get_muted() : Bool;
	private function get_name() : String;
	private function get_position() : String;
	private function get_quality() : Int;
	private function get_width() : Int;
	function setCursor(value : Bool) : Void;
	function setKeyFrameInterval(keyFrameInterval : Int) : Void;
	function setLoopback(compress : Bool = false) : Void;
	function setMode(width : Int, height : Int, fps : Float, favorArea : Bool = true) : Void;
	function setMotionLevel(motionLevel : Int, timeout : Int = 2000) : Void;
	function setQuality(bandwidth : Int, quality : Int) : Void;
	@:require(flash10_1) static var isSupported(get,never) : Bool;
	static var names(get,never) : Array<Dynamic>;
	@:require(flash10_1) static function _scanHardware() : Void;
	static function getCamera(?name : String) : Camera;
	private static function get_isSupported() : Bool;
	private static function get_names() : Array<Dynamic>;
}
