// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_c5dd76a1d5581e67
#define INCLUDED_c5dd76a1d5581e67
#include "hx/zip/Compress.hpp"
#endif
#ifndef INCLUDED_dc6f9f23dbe74273
#define INCLUDED_dc6f9f23dbe74273
#include "hx/zip/Zip.hpp"
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_zip_Compress
#include <haxe/zip/Compress.h>
#endif
#ifndef INCLUDED_haxe_zip_FlushMode
#include <haxe/zip/FlushMode.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_d39ba5f842b5bc35_31_new,"haxe.zip.Compress","new",0x4ddc50a9,"haxe.zip.Compress.new","haxe/zip/Compress.hx",31,0x2847cda5)
HX_LOCAL_STACK_FRAME(_hx_pos_d39ba5f842b5bc35_34_execute,"haxe.zip.Compress","execute",0xd015e2fe,"haxe.zip.Compress.execute","haxe/zip/Compress.hx",34,0x2847cda5)
HX_LOCAL_STACK_FRAME(_hx_pos_d39ba5f842b5bc35_43_setFlushMode,"haxe.zip.Compress","setFlushMode",0x35ab82dc,"haxe.zip.Compress.setFlushMode","haxe/zip/Compress.hx",43,0x2847cda5)
HX_LOCAL_STACK_FRAME(_hx_pos_d39ba5f842b5bc35_53_close,"haxe.zip.Compress","close",0x6942fc41,"haxe.zip.Compress.close","haxe/zip/Compress.hx",53,0x2847cda5)
HX_LOCAL_STACK_FRAME(_hx_pos_d39ba5f842b5bc35_57_run,"haxe.zip.Compress","run",0x4ddf6794,"haxe.zip.Compress.run","haxe/zip/Compress.hx",57,0x2847cda5)

namespace {

struct __Compress_objexecute final : public ::hx::AutoCallable_obj<  ::Dynamic ( ::haxe::io::Bytes,int, ::haxe::io::Bytes,int) > {
	::hx::ObjectPtr<haxe::zip::Compress_obj> __this;
	__Compress_objexecute(::hx::ObjectPtr<haxe::zip::Compress_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Compress_objexecute*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	 ::Dynamic HX_LOCAL_RUN( ::haxe::io::Bytes src,int srcPos, ::haxe::io::Bytes dst,int dstPos) override {
		return __this->execute(src, srcPos, dst, dstPos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Compress_objsetFlushMode final : public ::hx::AutoCallable_obj< void ( ::haxe::zip::FlushMode) > {
	::hx::ObjectPtr<haxe::zip::Compress_obj> __this;
	__Compress_objsetFlushMode(::hx::ObjectPtr<haxe::zip::Compress_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Compress_objsetFlushMode*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN( ::haxe::zip::FlushMode f) override {
		__this->setFlushMode(f);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Compress_objclose final : public ::hx::AutoCallable_obj< void () > {
	::hx::ObjectPtr<haxe::zip::Compress_obj> __this;
	__Compress_objclose(::hx::ObjectPtr<haxe::zip::Compress_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Compress_objclose*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN() override {
		__this->close();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Compress_objrun final : public ::hx::AutoCallable_obj<  ::haxe::io::Bytes ( ::haxe::io::Bytes,int) > {
	__Compress_objrun() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Compress_objrun*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::haxe::io::Bytes HX_LOCAL_RUN( ::haxe::io::Bytes s,int level) override {
		return haxe::zip::Compress_obj::run(s, level);
	}
};

::hx::Callable<  ::haxe::io::Bytes ( ::haxe::io::Bytes,int) > _hx_alloc__Compress_objrun;

}

namespace haxe{
namespace zip{

void Compress_obj::__construct(int level){
            	HX_STACKFRAME(&_hx_pos_d39ba5f842b5bc35_31_new)
HXDLIN(  31)		this->impl = ::hx::zip::Compress_obj::create(level);
            	}

::Dynamic Compress_obj::__CreateEmpty() { return new Compress_obj; }

void* Compress_obj::_hx_vtable = 0;

::Dynamic Compress_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Compress_obj > _hx_result = new Compress_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Compress_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x4b87b6d9;
}

 ::Dynamic Compress_obj::execute( ::haxe::io::Bytes src,int srcPos, ::haxe::io::Bytes dst,int dstPos){
            	HX_STACKFRAME(&_hx_pos_d39ba5f842b5bc35_34_execute)
HXLINE(  35)		::cpp::Pointer< unsigned char > srcView = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(src->getData())) );
HXDLIN(  35)		::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > > srcView1 = ( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(srcView,( (::cpp::Int64)(src->length) ))) )->slice(( (::cpp::Int64)(srcPos) ));
HXLINE(  36)		::cpp::Pointer< unsigned char > dstView = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(dst->getData())) );
HXDLIN(  36)		::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > > dstView1 = ( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(dstView,( (::cpp::Int64)(dst->length) ))) )->slice(( (::cpp::Int64)(dstPos) ));
HXLINE(  37)		::cpp::marshal::ValueType< ::hx::zip::Result > result = this->impl->execute(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(srcView1) ),( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(dstView1) ));
HXLINE(  39)		return  ::Dynamic(::hx::Anon_obj::Create(3)
            			->setFixed(0,HX_("write",df,6c,59,d0),( (::cpp::marshal::ValueReference< ::hx::zip::Result >)(result) )->write)
            			->setFixed(1,HX_("done",82,f0,6d,42),( (::cpp::marshal::ValueReference< ::hx::zip::Result >)(result) )->done)
            			->setFixed(2,HX_("read",56,4b,a7,4b),( (::cpp::marshal::ValueReference< ::hx::zip::Result >)(result) )->read));
            	}


::hx::Callable<  ::Dynamic ( ::haxe::io::Bytes,int, ::haxe::io::Bytes,int) > Compress_obj::execute_dyn() { return new __Compress_objexecute(this); }

void Compress_obj::setFlushMode( ::haxe::zip::FlushMode f){
            	HX_STACKFRAME(&_hx_pos_d39ba5f842b5bc35_43_setFlushMode)
HXDLIN(  43)		::cpp::marshal::ValueReference< ::hx::zip::Flush > _hx_tmp;
HXDLIN(  43)		switch((int)(f->_hx_getIndex())){
            			case (int)0: {
HXDLIN(  43)				_hx_tmp = ( (::cpp::marshal::ValueReference< ::hx::zip::Flush >)(::cpp::marshal::Boxed< ::hx::zip::Flush >( new ::cpp::marshal::Boxed_obj< ::hx::zip::Flush > (::hx::zip::Flush::None))) );
            			}
            			break;
            			case (int)1: {
HXDLIN(  43)				_hx_tmp = ( (::cpp::marshal::ValueReference< ::hx::zip::Flush >)(::cpp::marshal::Boxed< ::hx::zip::Flush >( new ::cpp::marshal::Boxed_obj< ::hx::zip::Flush > (::hx::zip::Flush::Sync))) );
            			}
            			break;
            			case (int)2: {
HXDLIN(  43)				_hx_tmp = ( (::cpp::marshal::ValueReference< ::hx::zip::Flush >)(::cpp::marshal::Boxed< ::hx::zip::Flush >( new ::cpp::marshal::Boxed_obj< ::hx::zip::Flush > (::hx::zip::Flush::Full))) );
            			}
            			break;
            			case (int)3: {
HXDLIN(  43)				_hx_tmp = ( (::cpp::marshal::ValueReference< ::hx::zip::Flush >)(::cpp::marshal::Boxed< ::hx::zip::Flush >( new ::cpp::marshal::Boxed_obj< ::hx::zip::Flush > (::hx::zip::Flush::Finish))) );
            			}
            			break;
            			case (int)4: {
HXDLIN(  43)				_hx_tmp = ( (::cpp::marshal::ValueReference< ::hx::zip::Flush >)(::cpp::marshal::Boxed< ::hx::zip::Flush >( new ::cpp::marshal::Boxed_obj< ::hx::zip::Flush > (::hx::zip::Flush::Block))) );
            			}
            			break;
            		}
HXDLIN(  43)		this->impl->setFlushMode(_hx_tmp);
            	}


::hx::Callable< void ( ::haxe::zip::FlushMode) > Compress_obj::setFlushMode_dyn() { return new __Compress_objsetFlushMode(this); }

void Compress_obj::close(){
            	HX_STACKFRAME(&_hx_pos_d39ba5f842b5bc35_53_close)
HXDLIN(  53)		this->impl->close();
            	}


::hx::Callable< void () > Compress_obj::close_dyn() { return new __Compress_objclose(this); }

 ::haxe::io::Bytes Compress_obj::run( ::haxe::io::Bytes s,int level){
            	HX_STACKFRAME(&_hx_pos_d39ba5f842b5bc35_57_run)
HXDLIN(  57)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(s->getData())) );
HXDLIN(  57)		return ::haxe::io::Bytes_obj::ofData(::hx::zip::Compress_obj::run(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(s->length) ))) ),level));
            	}


::hx::Callable<  ::haxe::io::Bytes ( ::haxe::io::Bytes,int) > Compress_obj::run_dyn() { return _hx_alloc__Compress_objrun; }


::hx::ObjectPtr< Compress_obj > Compress_obj::__new(int level) {
	::hx::ObjectPtr< Compress_obj > __this = new Compress_obj();
	__this->__construct(level);
	return __this;
}

::hx::ObjectPtr< Compress_obj > Compress_obj::__alloc(::hx::Ctx *_hx_ctx,int level) {
	Compress_obj* __this = (Compress_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Compress_obj), true, "haxe.zip.Compress"));
	*(void **)__this = Compress_obj::_hx_vtable;
	__this->__construct(level);
	return __this;
}

Compress_obj::Compress_obj()
{
}

void Compress_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Compress);
	HX_MARK_MEMBER_NAME(impl, "impl");
	HX_MARK_END_CLASS();
}

void Compress_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(impl, "impl");
}

::hx::Val Compress_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"impl") ) { return ::hx::Val( impl ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"close") ) { return ::hx::Val( close_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"execute") ) { return ::hx::Val( execute_dyn() ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"setFlushMode") ) { return ::hx::Val( setFlushMode_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool Compress_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { outValue = run_dyn(); return true; }
	}
	return false;
}

::hx::Val Compress_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	return super::__SetField(inName,inValue,inCallProp);
}

void Compress_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("impl",e0,7e,ba,45));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Compress_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /* ::hx::zip::Compress */ , (int)offsetof(Compress_obj, impl), HX_("impl",e0,7e,ba,45) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo* Compress_obj_sStaticStorageInfo = 0;
#endif

static ::String Compress_obj_sMemberFields[] = {
	HX_("execute",35,0a,0d,cc),
	HX_("setFlushMode",45,d4,07,63),
	HX_("close",b8,17,63,48),
	HX_("impl",e0,7e,ba,45),
	::String(null())
};

::hx::Class Compress_obj::__mClass;

static ::String Compress_obj_sStaticFields[] = {
	HX_("run",4b,e7,56,00),
	::String(null())
};

void Compress_obj::__register()
{
	Compress_obj _hx_dummy;
	Compress_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.zip.Compress",37,c8,12,6f);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Compress_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Compress_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Compress_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Compress_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Compress_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Compress_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Compress_obj::__boot()
{
_hx_alloc__Compress_objrun = new (::hx::NewObjectType::NewObjConst) __Compress_objrun();

}

} // end namespace haxe
} // end namespace zip
