// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_Date
#include <Date.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_crypto_Crc32
#include <haxe/crypto/Crc32.h>
#endif
#ifndef INCLUDED_haxe_ds_List
#include <haxe/ds/List.h>
#endif
#ifndef INCLUDED_haxe_ds__List_ListNode
#include <haxe/ds/_List/ListNode.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_BytesOutput
#include <haxe/io/BytesOutput.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_zip_ExtraField
#include <haxe/zip/ExtraField.h>
#endif
#ifndef INCLUDED_haxe_zip_Writer
#include <haxe/zip/Writer.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_92bfc241ff880f68_55_new,"haxe.zip.Writer","new",0xcba2dcfa,"haxe.zip.Writer.new","haxe/zip/Writer.hx",55,0xea0d2af4)
HX_LOCAL_STACK_FRAME(_hx_pos_92bfc241ff880f68_60_writeZipDate,"haxe.zip.Writer","writeZipDate",0x393b2ab6,"haxe.zip.Writer.writeZipDate","haxe/zip/Writer.hx",60,0xea0d2af4)
HX_LOCAL_STACK_FRAME(_hx_pos_92bfc241ff880f68_71_writeEntryHeader,"haxe.zip.Writer","writeEntryHeader",0xe2ca9c26,"haxe.zip.Writer.writeEntryHeader","haxe/zip/Writer.hx",71,0xea0d2af4)
HX_LOCAL_STACK_FRAME(_hx_pos_92bfc241ff880f68_141_write,"haxe.zip.Writer","write",0x56f853f9,"haxe.zip.Writer.write","haxe/zip/Writer.hx",141,0xea0d2af4)
HX_LOCAL_STACK_FRAME(_hx_pos_92bfc241ff880f68_149_writeCDR,"haxe.zip.Writer","writeCDR",0xd586c038,"haxe.zip.Writer.writeCDR","haxe/zip/Writer.hx",149,0xea0d2af4)
HX_LOCAL_STACK_FRAME(_hx_pos_92bfc241ff880f68_35_boot,"haxe.zip.Writer","boot",0x5af77e58,"haxe.zip.Writer.boot","haxe/zip/Writer.hx",35,0xea0d2af4)
HX_LOCAL_STACK_FRAME(_hx_pos_92bfc241ff880f68_42_boot,"haxe.zip.Writer","boot",0x5af77e58,"haxe.zip.Writer.boot","haxe/zip/Writer.hx",42,0xea0d2af4)

namespace {

struct __Writer_objwriteZipDate final : public ::hx::AutoCallable_obj< void ( ::Date) > {
	::hx::ObjectPtr<haxe::zip::Writer_obj> __this;
	__Writer_objwriteZipDate(::hx::ObjectPtr<haxe::zip::Writer_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Writer_objwriteZipDate*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN( ::Date date) override {
		__this->writeZipDate(date);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Writer_objwriteEntryHeader final : public ::hx::AutoCallable_obj< void ( ::Dynamic) > {
	::hx::ObjectPtr<haxe::zip::Writer_obj> __this;
	__Writer_objwriteEntryHeader(::hx::ObjectPtr<haxe::zip::Writer_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Writer_objwriteEntryHeader*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN( ::Dynamic f) override {
		__this->writeEntryHeader(f);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Writer_objwrite final : public ::hx::AutoCallable_obj< void ( ::haxe::ds::List) > {
	::hx::ObjectPtr<haxe::zip::Writer_obj> __this;
	__Writer_objwrite(::hx::ObjectPtr<haxe::zip::Writer_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Writer_objwrite*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN( ::haxe::ds::List files) override {
		__this->write(files);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Writer_objwriteCDR final : public ::hx::AutoCallable_obj< void () > {
	::hx::ObjectPtr<haxe::zip::Writer_obj> __this;
	__Writer_objwriteCDR(::hx::ObjectPtr<haxe::zip::Writer_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Writer_objwriteCDR*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN() override {
		__this->writeCDR();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

}

namespace haxe{
namespace zip{

void Writer_obj::__construct( ::haxe::io::Output o){
            	HX_GC_STACKFRAME(&_hx_pos_92bfc241ff880f68_55_new)
HXLINE(  56)		this->o = o;
HXLINE(  57)		this->files =  ::haxe::ds::List_obj::__alloc( HX_CTX );
            	}

::Dynamic Writer_obj::__CreateEmpty() { return new Writer_obj; }

void* Writer_obj::_hx_vtable = 0;

::Dynamic Writer_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Writer_obj > _hx_result = new Writer_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Writer_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7faaed6a;
}

void Writer_obj::writeZipDate( ::Date date){
            	HX_STACKFRAME(&_hx_pos_92bfc241ff880f68_60_writeZipDate)
HXLINE(  61)		int hour = date->getHours();
HXLINE(  62)		int min = date->getMinutes();
HXLINE(  63)		int sec = (date->getSeconds() >> 1);
HXLINE(  64)		this->o->writeUInt16((((hour << 11) | (min << 5)) | sec));
HXLINE(  65)		int year = (date->getFullYear() - 1980);
HXLINE(  66)		int month = (date->getMonth() + 1);
HXLINE(  67)		int day = date->getDate();
HXLINE(  68)		this->o->writeUInt16((((year << 9) | (month << 5)) | day));
            	}


::hx::Callable< void ( ::Date) > Writer_obj::writeZipDate_dyn() { return new __Writer_objwriteZipDate(this); }

void Writer_obj::writeEntryHeader( ::Dynamic f){
            	HX_GC_STACKFRAME(&_hx_pos_92bfc241ff880f68_71_writeEntryHeader)
HXLINE(  72)		 ::haxe::io::Output o = this->o;
HXLINE(  73)		int flags = 0;
HXLINE(  74)		if (::hx::IsNotNull( ( ( ::haxe::ds::List)(f->__Field(HX_("extraFields",29,e9,47,7f),::hx::paccDynamic)) ) )) {
HXLINE(  75)			 ::haxe::ds::_List::ListNode _g_head = ( ( ::haxe::ds::List)(f->__Field(HX_("extraFields",29,e9,47,7f),::hx::paccDynamic)) )->h;
HXDLIN(  75)			while(::hx::IsNotNull( _g_head )){
HXLINE(  75)				 ::haxe::zip::ExtraField val = _g_head->item;
HXDLIN(  75)				_g_head = _g_head->next;
HXDLIN(  75)				 ::haxe::zip::ExtraField e = val;
HXLINE(  76)				if ((e->_hx_getIndex() == 2)) {
HXLINE(  78)					::hx::OrEq(flags,2048);
            				}
            			}
            		}
HXLINE(  82)		o->writeInt32(67324752);
HXLINE(  83)		o->writeUInt16(20);
HXLINE(  84)		o->writeUInt16(flags);
HXLINE(  85)		if (::hx::IsNull( ( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) ) )) {
HXLINE(  86)			f->__SetField(HX_("fileSize",5d,89,97,65),0,::hx::paccDynamic);
HXLINE(  87)			f->__SetField(HX_("dataSize",0b,80,c7,8b),0,::hx::paccDynamic);
HXLINE(  88)			f->__SetField(HX_("crc32",73,0c,51,4c),0,::hx::paccDynamic);
HXLINE(  89)			f->__SetField(HX_("compressed",81,4c,da,67),false,::hx::paccDynamic);
HXLINE(  90)			f->__SetField(HX_("data",2a,56,63,42),::haxe::io::Bytes_obj::alloc(0),::hx::paccDynamic);
            		}
            		else {
HXLINE(  92)			if (::hx::IsNull( f->__Field(HX_("crc32",73,0c,51,4c),::hx::paccDynamic) )) {
HXLINE(  93)				if (( (bool)(f->__Field(HX_("compressed",81,4c,da,67),::hx::paccDynamic)) )) {
HXLINE(  94)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("CRC32 must be processed before compression",ea,f9,2a,51)));
            				}
HXLINE(  95)				f->__SetField(HX_("crc32",73,0c,51,4c),::haxe::crypto::Crc32_obj::make(( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) )),::hx::paccDynamic);
            			}
HXLINE(  97)			if (!(( (bool)(f->__Field(HX_("compressed",81,4c,da,67),::hx::paccDynamic)) ))) {
HXLINE(  98)				f->__SetField(HX_("fileSize",5d,89,97,65),( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) )->length,::hx::paccDynamic);
            			}
HXLINE(  99)			f->__SetField(HX_("dataSize",0b,80,c7,8b),( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) )->length,::hx::paccDynamic);
            		}
HXLINE( 101)		int _hx_tmp;
HXDLIN( 101)		if (( (bool)(f->__Field(HX_("compressed",81,4c,da,67),::hx::paccDynamic)) )) {
HXLINE( 101)			_hx_tmp = 8;
            		}
            		else {
HXLINE( 101)			_hx_tmp = 0;
            		}
HXDLIN( 101)		o->writeUInt16(_hx_tmp);
HXLINE( 102)		this->writeZipDate(( ( ::Date)(f->__Field(HX_("fileTime",a9,b4,40,66),::hx::paccDynamic)) ));
HXLINE( 103)		o->writeInt32(( (int)(f->__Field(HX_("crc32",73,0c,51,4c),::hx::paccDynamic)) ));
HXLINE( 104)		o->writeInt32(( (int)(f->__Field(HX_("dataSize",0b,80,c7,8b),::hx::paccDynamic)) ));
HXLINE( 105)		o->writeInt32(( (int)(f->__Field(HX_("fileSize",5d,89,97,65),::hx::paccDynamic)) ));
HXLINE( 106)		o->writeUInt16(( (::String)(f->__Field(HX_("fileName",e7,5a,43,62),::hx::paccDynamic)) ).length);
HXLINE( 107)		 ::haxe::io::BytesOutput e1 =  ::haxe::io::BytesOutput_obj::__alloc( HX_CTX );
HXLINE( 108)		if (::hx::IsNotNull( ( ( ::haxe::ds::List)(f->__Field(HX_("extraFields",29,e9,47,7f),::hx::paccDynamic)) ) )) {
HXLINE( 109)			 ::haxe::ds::_List::ListNode _g_head1 = ( ( ::haxe::ds::List)(f->__Field(HX_("extraFields",29,e9,47,7f),::hx::paccDynamic)) )->h;
HXDLIN( 109)			while(::hx::IsNotNull( _g_head1 )){
HXLINE( 109)				 ::haxe::zip::ExtraField val1 = _g_head1->item;
HXDLIN( 109)				_g_head1 = _g_head1->next;
HXDLIN( 109)				 ::haxe::zip::ExtraField f1 = val1;
HXLINE( 110)				switch((int)(f1->_hx_getIndex())){
            					case (int)0: {
HXLINE( 118)						int tag = f1->_hx_getInt(0);
HXDLIN( 118)						 ::haxe::io::Bytes bytes = f1->_hx_getObject(1).StaticCast<  ::haxe::io::Bytes >();
HXDLIN( 118)						{
HXLINE( 119)							e1->writeUInt16(tag);
HXLINE( 120)							e1->writeUInt16(bytes->length);
HXLINE( 121)							e1->write(bytes);
            						}
            					}
            					break;
            					case (int)1: {
HXLINE( 111)						::String name = f1->_hx_getString(0);
HXDLIN( 111)						int crc = f1->_hx_getInt(1);
HXDLIN( 111)						{
HXLINE( 112)							 ::haxe::io::Bytes namebytes = ::haxe::io::Bytes_obj::ofString(name,null());
HXLINE( 113)							e1->writeUInt16(28789);
HXLINE( 114)							e1->writeUInt16((namebytes->length + 5));
HXLINE( 115)							e1->writeByte(1);
HXLINE( 116)							e1->writeInt32(crc);
HXLINE( 117)							e1->write(namebytes);
            						}
            					}
            					break;
            					case (int)2: {
            					}
            					break;
            				}
            			}
            		}
HXLINE( 126)		 ::haxe::io::Bytes ebytes = e1->getBytes();
HXLINE( 127)		o->writeUInt16(ebytes->length);
HXLINE( 128)		o->writeString(( (::String)(f->__Field(HX_("fileName",e7,5a,43,62),::hx::paccDynamic)) ),null());
HXLINE( 129)		o->write(ebytes);
HXLINE( 130)		this->files->add( ::Dynamic(::hx::Anon_obj::Create(7)
            			->setFixed(0,HX_("fields",79,8e,8e,80),ebytes)
            			->setFixed(1,HX_("crc",d4,82,4b,00),f->__Field(HX_("crc32",73,0c,51,4c),::hx::paccDynamic))
            			->setFixed(2,HX_("clen",52,6b,c2,41),( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) )->length)
            			->setFixed(3,HX_("date",2e,56,63,42),( ( ::Date)(f->__Field(HX_("fileTime",a9,b4,40,66),::hx::paccDynamic)) ))
            			->setFixed(4,HX_("name",4b,72,ff,48),( (::String)(f->__Field(HX_("fileName",e7,5a,43,62),::hx::paccDynamic)) ))
            			->setFixed(5,HX_("size",c1,a0,53,4c),( (int)(f->__Field(HX_("fileSize",5d,89,97,65),::hx::paccDynamic)) ))
            			->setFixed(6,HX_("compressed",81,4c,da,67),( (bool)(f->__Field(HX_("compressed",81,4c,da,67),::hx::paccDynamic)) ))));
            	}


::hx::Callable< void ( ::Dynamic) > Writer_obj::writeEntryHeader_dyn() { return new __Writer_objwriteEntryHeader(this); }

void Writer_obj::write( ::haxe::ds::List files){
            	HX_STACKFRAME(&_hx_pos_92bfc241ff880f68_141_write)
HXLINE( 142)		{
HXLINE( 142)			 ::haxe::ds::_List::ListNode _g_head = files->h;
HXDLIN( 142)			while(::hx::IsNotNull( _g_head )){
HXLINE( 142)				 ::Dynamic val = _g_head->item;
HXDLIN( 142)				_g_head = _g_head->next;
HXDLIN( 142)				 ::Dynamic f = val;
HXLINE( 143)				this->writeEntryHeader(f);
HXLINE( 144)				this->o->writeFullBytes(( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) ),0,( ( ::haxe::io::Bytes)(f->__Field(HX_("data",2a,56,63,42),::hx::paccDynamic)) )->length);
            			}
            		}
HXLINE( 146)		this->writeCDR();
            	}


::hx::Callable< void ( ::haxe::ds::List) > Writer_obj::write_dyn() { return new __Writer_objwrite(this); }

void Writer_obj::writeCDR(){
            	HX_STACKFRAME(&_hx_pos_92bfc241ff880f68_149_writeCDR)
HXLINE( 150)		int cdr_size = 0;
HXLINE( 151)		int cdr_offset = 0;
HXLINE( 152)		{
HXLINE( 152)			 ::haxe::ds::_List::ListNode _g_head = this->files->h;
HXDLIN( 152)			while(::hx::IsNotNull( _g_head )){
HXLINE( 152)				 ::Dynamic val = _g_head->item;
HXDLIN( 152)				_g_head = _g_head->next;
HXDLIN( 152)				 ::Dynamic f = val;
HXLINE( 153)				int namelen = ( (::String)(f->__Field(HX_("name",4b,72,ff,48),::hx::paccDynamic)) ).length;
HXLINE( 154)				int extraFieldsLength = ( ( ::haxe::io::Bytes)(f->__Field(HX_("fields",79,8e,8e,80),::hx::paccDynamic)) )->length;
HXLINE( 155)				this->o->writeInt32(33639248);
HXLINE( 156)				this->o->writeUInt16(20);
HXLINE( 157)				this->o->writeUInt16(20);
HXLINE( 158)				this->o->writeUInt16(0);
HXLINE( 159)				int _hx_tmp;
HXDLIN( 159)				if (( (bool)(f->__Field(HX_("compressed",81,4c,da,67),::hx::paccDynamic)) )) {
HXLINE( 159)					_hx_tmp = 8;
            				}
            				else {
HXLINE( 159)					_hx_tmp = 0;
            				}
HXDLIN( 159)				this->o->writeUInt16(_hx_tmp);
HXLINE( 160)				this->writeZipDate(( ( ::Date)(f->__Field(HX_("date",2e,56,63,42),::hx::paccDynamic)) ));
HXLINE( 161)				this->o->writeInt32(( (int)(f->__Field(HX_("crc",d4,82,4b,00),::hx::paccDynamic)) ));
HXLINE( 162)				this->o->writeInt32(( (int)(f->__Field(HX_("clen",52,6b,c2,41),::hx::paccDynamic)) ));
HXLINE( 163)				this->o->writeInt32(( (int)(f->__Field(HX_("size",c1,a0,53,4c),::hx::paccDynamic)) ));
HXLINE( 164)				this->o->writeUInt16(namelen);
HXLINE( 165)				this->o->writeUInt16(extraFieldsLength);
HXLINE( 166)				this->o->writeUInt16(0);
HXLINE( 167)				this->o->writeUInt16(0);
HXLINE( 168)				this->o->writeUInt16(0);
HXLINE( 169)				this->o->writeInt32(0);
HXLINE( 170)				this->o->writeInt32(cdr_offset);
HXLINE( 171)				this->o->writeString(( (::String)(f->__Field(HX_("name",4b,72,ff,48),::hx::paccDynamic)) ),null());
HXLINE( 172)				this->o->write(( ( ::haxe::io::Bytes)(f->__Field(HX_("fields",79,8e,8e,80),::hx::paccDynamic)) ));
HXLINE( 173)				::hx::AddEq(cdr_size,((46 + namelen) + extraFieldsLength));
HXLINE( 174)				::hx::AddEq(cdr_offset,(((30 + namelen) + extraFieldsLength) + ( (int)(f->__Field(HX_("clen",52,6b,c2,41),::hx::paccDynamic)) )));
            			}
            		}
HXLINE( 177)		this->o->writeInt32(101010256);
HXLINE( 179)		this->o->writeUInt16(0);
HXLINE( 181)		this->o->writeUInt16(0);
HXLINE( 183)		this->o->writeUInt16(this->files->length);
HXLINE( 185)		this->o->writeUInt16(this->files->length);
HXLINE( 187)		this->o->writeInt32(cdr_size);
HXLINE( 189)		this->o->writeInt32(cdr_offset);
HXLINE( 191)		this->o->writeUInt16(0);
            	}


::hx::Callable< void () > Writer_obj::writeCDR_dyn() { return new __Writer_objwriteCDR(this); }

int Writer_obj::CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE;

int Writer_obj::LOCAL_FILE_HEADER_FIELDS_SIZE;


::hx::ObjectPtr< Writer_obj > Writer_obj::__new( ::haxe::io::Output o) {
	::hx::ObjectPtr< Writer_obj > __this = new Writer_obj();
	__this->__construct(o);
	return __this;
}

::hx::ObjectPtr< Writer_obj > Writer_obj::__alloc(::hx::Ctx *_hx_ctx, ::haxe::io::Output o) {
	Writer_obj* __this = (Writer_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Writer_obj), true, "haxe.zip.Writer"));
	*(void **)__this = Writer_obj::_hx_vtable;
	__this->__construct(o);
	return __this;
}

Writer_obj::Writer_obj()
{
}

void Writer_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Writer);
	HX_MARK_MEMBER_NAME(o, "o");
	HX_MARK_MEMBER_NAME(files, "files");
	HX_MARK_END_CLASS();
}

void Writer_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(o, "o");
	HX_VISIT_MEMBER_NAME(files, "files");
}

::hx::Val Writer_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"o") ) { return ::hx::Val( o ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"write") ) { return ::hx::Val( write_dyn() ); }
		if (HX_FIELD_EQ(inName,"files") ) { return ::hx::Val( files ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"writeCDR") ) { return ::hx::Val( writeCDR_dyn() ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"writeZipDate") ) { return ::hx::Val( writeZipDate_dyn() ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"writeEntryHeader") ) { return ::hx::Val( writeEntryHeader_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Writer_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"o") ) { o = inValue.Cast<  ::haxe::io::Output >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"files") ) { files = inValue.Cast<  ::haxe::ds::List >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Writer_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("o",6f,00,00,00));
	outFields->push(HX_("files",77,de,98,00));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Writer_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /*  ::haxe::io::Output */ , (int)offsetof(Writer_obj, o), HX_("o",6f,00,00,00) },
	{ ::hx::fsObject /*  ::haxe::ds::List */ , (int)offsetof(Writer_obj, files), HX_("files",77,de,98,00) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo Writer_obj_sStaticStorageInfo[] = {
	{ ::hx::fsInt, (void*) &Writer_obj::CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE, HX_("CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE",f5,bd,11,77) },
	{ ::hx::fsInt, (void*) &Writer_obj::LOCAL_FILE_HEADER_FIELDS_SIZE, HX_("LOCAL_FILE_HEADER_FIELDS_SIZE",84,97,c0,94) },
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static ::String Writer_obj_sMemberFields[] = {
	HX_("writeZipDate",90,9a,ff,3b),
	HX_("writeEntryHeader",00,01,4d,97),
	HX_("write",df,6c,59,d0),
	HX_("writeCDR",12,bb,eb,23),
	HX_("o",6f,00,00,00),
	HX_("files",77,de,98,00),
	::String(null())
};

static void Writer_obj_sMarkStatics(HX_MARK_PARAMS) { 
	HX_MARK_MEMBER_NAME(Writer_obj::CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE, "CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE");
	HX_MARK_MEMBER_NAME(Writer_obj::LOCAL_FILE_HEADER_FIELDS_SIZE, "LOCAL_FILE_HEADER_FIELDS_SIZE");
 };

#ifdef HXCPP_VISIT_ALLOCS
static void Writer_obj_sVisitStatics(HX_VISIT_PARAMS) { 
	HX_VISIT_MEMBER_NAME(Writer_obj::CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE, "CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE");
	HX_VISIT_MEMBER_NAME(Writer_obj::LOCAL_FILE_HEADER_FIELDS_SIZE, "LOCAL_FILE_HEADER_FIELDS_SIZE");
 };

#endif

::hx::Class Writer_obj::__mClass;

static ::String Writer_obj_sStaticFields[] = {
	HX_("CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE",f5,bd,11,77),
	HX_("LOCAL_FILE_HEADER_FIELDS_SIZE",84,97,c0,94),
	::String(null())
};

void Writer_obj::__register()
{
	Writer_obj _hx_dummy;
	Writer_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.zip.Writer",08,98,86,6e);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = Writer_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Writer_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Writer_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Writer_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Writer_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Writer_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Writer_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Writer_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_92bfc241ff880f68_35_boot)
HXDLIN(  35)		::haxe::zip::Writer_obj::CENTRAL_DIRECTORY_RECORD_FIELDS_SIZE = 46;
            	}
{
            	HX_STACKFRAME(&_hx_pos_92bfc241ff880f68_42_boot)
HXDLIN(  42)		::haxe::zip::Writer_obj::LOCAL_FILE_HEADER_FIELDS_SIZE = 30;
            	}
}

} // end namespace haxe
} // end namespace zip
