package flash.net;

@:require(flash10_1) extern final class NetStreamMulticastInfo {
	var bytesPushedFromPeers(get,never) : Float;
	var bytesPushedToPeers(get,never) : Float;
	var bytesReceivedFromIPMulticast(get,never) : Float;
	var bytesReceivedFromServer(get,never) : Float;
	var bytesRequestedByPeers(get,never) : Float;
	var bytesRequestedFromPeers(get,never) : Float;
	var fragmentsPushedFromPeers(get,never) : Float;
	var fragmentsPushedToPeers(get,never) : Float;
	var fragmentsReceivedFromIPMulticast(get,never) : Float;
	var fragmentsReceivedFromServer(get,never) : Float;
	var fragmentsRequestedByPeers(get,never) : Float;
	var fragmentsRequestedFromPeers(get,never) : Float;
	var receiveControlBytesPerSecond(get,never) : Float;
	var receiveDataBytesPerSecond(get,never) : Float;
	var receiveDataBytesPerSecondFromIPMulticast(get,never) : Float;
	var receiveDataBytesPerSecondFromServer(get,never) : Float;
	var sendControlBytesPerSecond(get,never) : Float;
	var sendControlBytesPerSecondToServer(get,never) : Float;
	var sendDataBytesPerSecond(get,never) : Float;
	function new(sendDataBytesPerSecond : Float, sendControlBytesPerSecond : Float, receiveDataBytesPerSecond : Float, receiveControlBytesPerSecond : Float, bytesPushedToPeers : Float, fragmentsPushedToPeers : Float, bytesRequestedByPeers : Float, fragmentsRequestedByPeers : Float, bytesPushedFromPeers : Float, fragmentsPushedFromPeers : Float, bytesRequestedFromPeers : Float, fragmentsRequestedFromPeers : Float, sendControlBytesPerSecondToServer : Float, receiveDataBytesPerSecondFromServer : Float, bytesReceivedFromServer : Float, fragmentsReceivedFromServer : Float, receiveDataBytesPerSecondFromIPMulticast : Float, bytesReceivedFromIPMulticast : Float, fragmentsReceivedFromIPMulticast : Float) : Void;
	private function get_bytesPushedFromPeers() : Float;
	private function get_bytesPushedToPeers() : Float;
	private function get_bytesReceivedFromIPMulticast() : Float;
	private function get_bytesReceivedFromServer() : Float;
	private function get_bytesRequestedByPeers() : Float;
	private function get_bytesRequestedFromPeers() : Float;
	private function get_fragmentsPushedFromPeers() : Float;
	private function get_fragmentsPushedToPeers() : Float;
	private function get_fragmentsReceivedFromIPMulticast() : Float;
	private function get_fragmentsReceivedFromServer() : Float;
	private function get_fragmentsRequestedByPeers() : Float;
	private function get_fragmentsRequestedFromPeers() : Float;
	private function get_receiveControlBytesPerSecond() : Float;
	private function get_receiveDataBytesPerSecond() : Float;
	private function get_receiveDataBytesPerSecondFromIPMulticast() : Float;
	private function get_receiveDataBytesPerSecondFromServer() : Float;
	private function get_sendControlBytesPerSecond() : Float;
	private function get_sendControlBytesPerSecondToServer() : Float;
	private function get_sendDataBytesPerSecond() : Float;
	function toString() : String;
}
