package flash.net;

extern final class NetStreamInfo {
	var SRTT(get,never) : Float;
	var audioBufferByteLength(get,never) : Float;
	var audioBufferLength(get,never) : Float;
	var audioByteCount(get,never) : Float;
	var audioBytesPerSecond(get,never) : Float;
	var audioLossRate(get,never) : Float;
	var byteCount(get,never) : Float;
	var currentBytesPerSecond(get,never) : Float;
	var dataBufferByteLength(get,never) : Float;
	var dataBufferLength(get,never) : Float;
	var dataByteCount(get,never) : Float;
	var dataBytesPerSecond(get,never) : Float;
	var droppedFrames(get,never) : Float;
	var isLive(get,never) : Bool;
	var maxBytesPerSecond(get,never) : Float;
	var metaData(get,never) : Dynamic;
	var playbackBytesPerSecond(get,never) : Float;
	var resourceName(get,never) : String;
	var uri(get,never) : String;
	var videoBufferByteLength(get,never) : Float;
	var videoBufferLength(get,never) : Float;
	var videoByteCount(get,never) : Float;
	var videoBytesPerSecond(get,never) : Float;
	@:require(flash10_1) var videoLossRate(get,never) : Float;
	var xmpData(get,never) : Dynamic;
	function new(curBPS : Float, byteCount : Float, maxBPS : Float, audioBPS : Float, audioByteCount : Float, videoBPS : Float, videoByteCount : Float, dataBPS : Float, dataByteCount : Float, playbackBPS : Float, droppedFrames : Float, audioBufferByteLength : Float, videoBufferByteLength : Float, dataBufferByteLength : Float, audioBufferLength : Float, videoBufferLength : Float, dataBufferLength : Float, srtt : Float, audioLossRate : Float, videoLossRate : Float, ?metaData : Dynamic, ?xmpData : Dynamic, ?uri : String, ?resourceName : String, isLive : Bool = true) : Void;
	private function get_SRTT() : Float;
	private function get_audioBufferByteLength() : Float;
	private function get_audioBufferLength() : Float;
	private function get_audioByteCount() : Float;
	private function get_audioBytesPerSecond() : Float;
	private function get_audioLossRate() : Float;
	private function get_byteCount() : Float;
	private function get_currentBytesPerSecond() : Float;
	private function get_dataBufferByteLength() : Float;
	private function get_dataBufferLength() : Float;
	private function get_dataByteCount() : Float;
	private function get_dataBytesPerSecond() : Float;
	private function get_droppedFrames() : Float;
	private function get_isLive() : Bool;
	private function get_maxBytesPerSecond() : Float;
	private function get_metaData() : Dynamic;
	private function get_playbackBytesPerSecond() : Float;
	private function get_resourceName() : String;
	private function get_uri() : String;
	private function get_videoBufferByteLength() : Float;
	private function get_videoBufferLength() : Float;
	private function get_videoByteCount() : Float;
	private function get_videoBytesPerSecond() : Float;
	private function get_videoLossRate() : Float;
	private function get_xmpData() : Dynamic;
	function toString() : String;
}
