package cs.system.net.sockets;

/** Defines configuration option names. */
@:native("System.Net.Sockets.SocketOptionName")
extern enum SocketOptionName {
	AcceptConnection;
	AddMembership;
	AddSourceMembership;
	BlockSource;
	Broadcast;
	BsdUrgent;
	ChecksumCoverage;
	Debug;
	DontFragment;
	DontLinger;
	DontRoute;
	DropMembership;
	DropSourceMembership;
	Error;
	ExclusiveAddressUse;
	Expedited;
	HeaderIncluded;
	HopLimit;
	IPOptions;
	IPProtectionLevel;
	IpTimeToLive;
	IPv6Only;
	KeepAlive;
	Linger;
	MaxConnections;
	MulticastInterface;
	MulticastLoopback;
	MulticastTimeToLive;
	NoChecksum;
	NoDelay;
	OutOfBandInline;
	PacketInformation;
	ReceiveBuffer;
	ReceiveLowWater;
	ReceiveTimeout;
	ReuseAddress;
	ReuseUnicastPort;
	SendBuffer;
	SendLowWater;
	SendTimeout;
	Type;
	TypeOfService;
	UnblockSource;
	UpdateAcceptContext;
	UpdateConnectContext;
	UseLoopback;
}
