package haxe.coro;

import haxe.CallStack.StackItem;
import haxe.Exception;
import haxe.coro.context.Context;
import haxe.coro.context.ExceptionHandler;
import haxe.coro.dispatchers.Dispatcher;
import haxe.coro.dispatchers.IDispatchObject;

/**
	This class serves as the base class for all continuation classes generated by the compiler. It provides the
	basic functionality for managing the internal coroutine state, most of which should be uninteresting to the
	casual coroutine user.
**/
abstract class BaseContinuation<T> extends SuspensionResult<T> implements IContinuation<T> implements IStackFrame implements IDispatchObject {
    /**
		The continuation to resume once `this` continuation completes.
	**/
	public final completion:IContinuation<Any>;

	/**
		The immutable context of `this` continuation.
	**/
	public var context(get, null):Context;

	/**
		The current label of the internal state machine.
	**/
    public var gotoLabel:Int;

	var resumeResult:Null<SuspensionResult<Any>>;
	#if debug
	var stackItem:Null<StackItem>;
	var _hx_startedException:Bool;
	#end

	/**
		Creates a new continuation which starts in `initialLabel` state and resumes `completion` on completion.
	**/
    function new(completion:IContinuation<Any>, initialLabel:Int) {
		super(Pending);
        this.completion = completion;
        gotoLabel  = initialLabel;
        error      = null;
        result     = null;
		context    = completion.context;
		#if debug
		_hx_startedException = false;
		#end
    }

	inline function get_context() {
		return context;
	}

	/**
		@see `IContinuation.resume`
	**/
    public final function resume(result:Any, error:Exception):Void {
		this.result = result;
		this.error = error;
		// In a threaded environment, we have to assume that `invokeResume` might
		// go into this `resume` function before we're even done here. We can only
		// make assumptions about its return value if it's not the `suspended` marker,
		// because in that case it must be a final state of the coroutine.
		final resumeResult = invokeResume();
		switch (resumeResult.state) {
			case Pending:

			case Returned, Thrown:
				this.resumeResult = resumeResult;
				final dispatcher = context.get(Dispatcher);
				if (dispatcher != null) {
					dispatcher.dispatch(this);
				} else {
					onDispatch();
				}
		}
    }

	/**
		@see `IStackFrame.callerFrame`
	**/
    public function callerFrame():Null<IStackFrame> {
        return if (completion is IStackFrame) {
            cast completion;
        } else {
            null;
        }
    }

	/**
		@see `IStackFrame.callerFrame`
	**/
	public function getStackItem():Null<StackItem> {
		#if debug
		return stackItem;
		#else
		return null;
		#end
	}

    function setClassFuncStackItem(cls:String, func:String, file:String, line:Int, pos:Int, pmin:Int, pmax:Int) {
		#if debug
        stackItem = StackItem.FilePos(StackItem.Method(cls, func), file, line, pos);
		#if eval
		eval.vm.Context.callMacroApi("associate_enum_value_pos")(stackItem, haxe.macro.Context.makePosition({file: file, min: pmin, max: pmax}));
		#end
		#end
    }

    function setLocalFuncStackItem(id:Int, file:String, line:Int, pos:Int, pmin:Int, pmax:Int) {
		#if debug
        stackItem = StackItem.FilePos(StackItem.LocalFunction(id), file, line, pos);
		#if eval
		eval.vm.Context.callMacroApi("associate_enum_value_pos")(stackItem, haxe.macro.Context.makePosition({file: file, min: pmin, max: pmax}));
		#end
		#end
    }

	function startException(exception:Exception) {
		final handler = context.get(ExceptionHandler);
		if (handler != null) {
			return handler.startException(this, exception);
		}
		return exception;
	}

    function buildCallStack() {
		final handler = context.get(ExceptionHandler);
		if (handler != null) {
			handler.buildCallStack(this);
		}
    }

    abstract function invokeResume():SuspensionResult<T>;

	override function toString() {
		return '[BaseContinuation ${state.toString()}, $result]';
	}

	public function onDispatch() {
		switch (resumeResult.state) {
			case Pending:
				completion.resume(null, new Exception('Invalid dispatch call on suspended coroutine'));
			case Returned:
				completion.resume(resumeResult.result, null);
			case Thrown:
				completion.resume(null, resumeResult.error);
		}
	}
}