package cs.system.runtime.compilerservices;

/** Allows you to determine whether a method is a state machine method. */
@:native("System.Runtime.CompilerServices.StateMachineAttribute")
extern class StateMachineAttribute extends cs.system.Attribute {
	/**
	 * Returns the type object for the underlying state machine type that was generated
	 * by the compiler to implement the state machine method.
	 * @return Gets the type object for the underlying state machine type that was
	 * generated by the compiler to implement the state machine method.
	 */
	var StateMachineType(default, never):cs.system.Type;
	function new(stateMachineType:cs.system.Type):Void;
}
