package cs.system.xml.serialization;

/** Specifies that the  must serialize the class member as an encoded SOAP attribute. */
@:native("System.Xml.Serialization.SoapAttributeAttribute")
extern class SoapAttributeAttribute extends cs.system.Attribute {
	/**
	 * Gets or sets the name of the XML attribute generated by the .
	 * @return The name of the XML attribute. The default is the member identifier.
	 */
	var AttributeName(default, default):String;
	/**
	 * Gets or sets the XML Schema definition language (XSD) data type of the SOAP
	 * attribute generated by the .
	 * @return An XML Schema data type.
	 */
	var DataType(default, default):String;
	/**
	 * Gets or sets the XML namespace of the XML attribute.
	 * @return The XML namespace of the XML attribute.
	 */
	var Namespace(default, default):String;
	@:overload(function():Void {})
	function new(attributeName:String):Void;
}
