// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_templo_EltDef
#define INCLUDED_templo_EltDef

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(templo,EltDef)
namespace templo{


class EltDef_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef EltDef_obj OBJ_;

	public:
		enum { _hx_ClassId = 0x076080cf };

		EltDef_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("templo.EltDef",af,96,61,e1); }
		::String __ToString() const { return HX_("EltDef.",76,c3,8e,5b) + _hx_tag; }
		bool _hx_isInstanceOf(int inClassId);

		static ::templo::EltDef XNode( ::Dynamic node);
		static ::Dynamic XNode_dyn();
		static ::templo::EltDef XMacroCall(::String s,::Array< ::Dynamic> cl);
		static ::Dynamic XMacroCall_dyn();
		static ::templo::EltDef XMacroDef( ::Dynamic m);
		static ::Dynamic XMacroDef_dyn();
		static ::templo::EltDef XComment(::String s);
		static ::Dynamic XComment_dyn();
		static ::templo::EltDef XData(::String d);
		static ::Dynamic XData_dyn();
		static ::templo::EltDef XCData(::Array< ::Dynamic> d);
		static ::Dynamic XCData_dyn();
		static ::templo::EltDef XConstr( ::Dynamic c);
		static ::Dynamic XConstr_dyn();
};

} // end namespace templo

#endif /* INCLUDED_templo_EltDef */ 
