// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_templo_ExprDef
#define INCLUDED_templo_ExprDef

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(templo,Constant)
HX_DECLARE_CLASS1(templo,ExprDef)
HX_DECLARE_CLASS1(templo,Op)
HX_DECLARE_CLASS1(templo,Unop)
namespace templo{


class ExprDef_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef ExprDef_obj OBJ_;

	public:
		enum { _hx_ClassId = 0x0a0cfc79 };

		ExprDef_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("templo.ExprDef",99,0a,ff,f0); }
		::String __ToString() const { return HX_("ExprDef.",be,76,8e,81) + _hx_tag; }
		bool _hx_isInstanceOf(int inClassId);

		static ::templo::ExprDef VConst( ::templo::Constant c);
		static ::Dynamic VConst_dyn();
		static ::templo::ExprDef VIdent(::String s);
		static ::Dynamic VIdent_dyn();
		static ::templo::ExprDef VVar(::String v);
		static ::Dynamic VVar_dyn();
		static ::templo::ExprDef VIf( ::Dynamic eif, ::Dynamic ethen, ::Dynamic eelse);
		static ::Dynamic VIf_dyn();
		static ::templo::ExprDef VBinop( ::templo::Op op, ::Dynamic e1, ::Dynamic e2);
		static ::Dynamic VBinop_dyn();
		static ::templo::ExprDef VUnop( ::templo::Unop op,bool postfix, ::Dynamic e1);
		static ::Dynamic VUnop_dyn();
		static ::templo::ExprDef VCall( ::Dynamic e1,::Array< ::Dynamic> el);
		static ::Dynamic VCall_dyn();
		static ::templo::ExprDef VParent( ::Dynamic e1);
		static ::Dynamic VParent_dyn();
		static ::templo::ExprDef VField( ::Dynamic e1,::String s);
		static ::Dynamic VField_dyn();
		static ::templo::ExprDef VArray( ::Dynamic e1, ::Dynamic e2);
		static ::Dynamic VArray_dyn();
		static ::templo::ExprDef VArrayDecl(::Array< ::Dynamic> el);
		static ::Dynamic VArrayDecl_dyn();
		static ::templo::ExprDef VBool( ::Dynamic e);
		static ::Dynamic VBool_dyn();
		static ::templo::ExprDef VLiteral( ::Dynamic e);
		static ::Dynamic VLiteral_dyn();
		static ::templo::ExprDef VObject(::Array< ::Dynamic> fl);
		static ::Dynamic VObject_dyn();
};

} // end namespace templo

#endif /* INCLUDED_templo_ExprDef */ 
