// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_templo_Keyword
#define INCLUDED_templo_Keyword

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(templo,Keyword)
namespace templo{


class Keyword_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef Keyword_obj OBJ_;

	public:
		enum { _hx_ClassId = 0x29ebcd26 };

		Keyword_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("templo.Keyword",f2,ed,c1,83); }
		::String __ToString() const { return HX_("Keyword.",45,81,52,59) + _hx_tag; }
		bool _hx_isInstanceOf(int inClassId);

		static ::templo::Keyword If;
		static inline ::templo::Keyword If_dyn() { return If; }
		static ::templo::Keyword Else;
		static inline ::templo::Keyword Else_dyn() { return Else; }
		static ::templo::Keyword Var;
		static inline ::templo::Keyword Var_dyn() { return Var; }
		static ::templo::Keyword While;
		static inline ::templo::Keyword While_dyn() { return While; }
		static ::templo::Keyword Do;
		static inline ::templo::Keyword Do_dyn() { return Do; }
		static ::templo::Keyword For;
		static inline ::templo::Keyword For_dyn() { return For; }
		static ::templo::Keyword Break;
		static inline ::templo::Keyword Break_dyn() { return Break; }
		static ::templo::Keyword Continue;
		static inline ::templo::Keyword Continue_dyn() { return Continue; }
		static ::templo::Keyword Function;
		static inline ::templo::Keyword Function_dyn() { return Function; }
		static ::templo::Keyword Return;
		static inline ::templo::Keyword Return_dyn() { return Return; }
		static ::templo::Keyword This;
		static inline ::templo::Keyword This_dyn() { return This; }
		static ::templo::Keyword Try;
		static inline ::templo::Keyword Try_dyn() { return Try; }
		static ::templo::Keyword Catch;
		static inline ::templo::Keyword Catch_dyn() { return Catch; }
		static ::templo::Keyword Default;
		static inline ::templo::Keyword Default_dyn() { return Default; }
		static ::templo::Keyword Switch;
		static inline ::templo::Keyword Switch_dyn() { return Switch; }
		static ::templo::Keyword Case;
		static inline ::templo::Keyword Case_dyn() { return Case; }
		static ::templo::Keyword Ignore;
		static inline ::templo::Keyword Ignore_dyn() { return Ignore; }
		static ::templo::Keyword Literal;
		static inline ::templo::Keyword Literal_dyn() { return Literal; }
};

} // end namespace templo

#endif /* INCLUDED_templo_Keyword */ 
