// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_templo_Node
#define INCLUDED_templo_Node

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(templo,Named)
HX_DECLARE_CLASS1(templo,Node)
HX_DECLARE_CLASS1(templo,Part)

namespace templo{


class HXCPP_CLASS_ATTRIBUTES Node_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Node_obj OBJ_;
		Node_obj();

	public:
		enum { _hx_ClassId = 0x0c318441 };

		void __construct(::String node,::Array< ::Dynamic> attributes,::Array< ::Dynamic> macros, ::Dynamic cond, ::templo::Named repeat,::Array< ::Dynamic> attrs, ::templo::Part content,bool ignore);
		inline void *operator new(size_t inSize, bool inContainer=true, const char* inName="templo.Node")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, true, "templo.Node"); }
		static ::hx::ObjectPtr< Node_obj > __new(::String node,::Array< ::Dynamic> attributes,::Array< ::Dynamic> macros, ::Dynamic cond, ::templo::Named repeat,::Array< ::Dynamic> attrs, ::templo::Part content,bool ignore);
		static ::hx::ObjectPtr< Node_obj > __alloc(::hx::Ctx *_hx_ctx,::String node,::Array< ::Dynamic> attributes,::Array< ::Dynamic> macros, ::Dynamic cond, ::templo::Named repeat,::Array< ::Dynamic> attrs, ::templo::Part content,bool ignore);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~Node_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(::Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Node",22,36,e3,33); }

		::String node;
		::Array< ::Dynamic> attributes;
		::Array< ::Dynamic> macros;
		 ::Dynamic cond;
		 ::templo::Named repeat;
		::Array< ::Dynamic> attrs;
		 ::templo::Part content;
		bool ignore;
};

} // end namespace templo

#endif /* INCLUDED_templo_Node */ 
