// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_templo_Op
#define INCLUDED_templo_Op

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(templo,Op)
namespace templo{


class Op_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef Op_obj OBJ_;

	public:
		enum { _hx_ClassId = 0x3d2670d8 };

		Op_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("templo.Op",b8,16,af,1b); }
		::String __ToString() const { return HX_("Op.",cd,53,3c,00) + _hx_tag; }
		bool _hx_isInstanceOf(int inClassId);

		static ::templo::Op OpAdd;
		static inline ::templo::Op OpAdd_dyn() { return OpAdd; }
		static ::templo::Op OpMult;
		static inline ::templo::Op OpMult_dyn() { return OpMult; }
		static ::templo::Op OpDiv;
		static inline ::templo::Op OpDiv_dyn() { return OpDiv; }
		static ::templo::Op OpSub;
		static inline ::templo::Op OpSub_dyn() { return OpSub; }
		static ::templo::Op OpAssign;
		static inline ::templo::Op OpAssign_dyn() { return OpAssign; }
		static ::templo::Op OpEq;
		static inline ::templo::Op OpEq_dyn() { return OpEq; }
		static ::templo::Op OpNotEq;
		static inline ::templo::Op OpNotEq_dyn() { return OpNotEq; }
		static ::templo::Op OpGt;
		static inline ::templo::Op OpGt_dyn() { return OpGt; }
		static ::templo::Op OpGte;
		static inline ::templo::Op OpGte_dyn() { return OpGte; }
		static ::templo::Op OpLt;
		static inline ::templo::Op OpLt_dyn() { return OpLt; }
		static ::templo::Op OpLte;
		static inline ::templo::Op OpLte_dyn() { return OpLte; }
		static ::templo::Op OpAnd;
		static inline ::templo::Op OpAnd_dyn() { return OpAnd; }
		static ::templo::Op OpOr;
		static inline ::templo::Op OpOr_dyn() { return OpOr; }
		static ::templo::Op OpXor;
		static inline ::templo::Op OpXor_dyn() { return OpXor; }
		static ::templo::Op OpBoolAnd;
		static inline ::templo::Op OpBoolAnd_dyn() { return OpBoolAnd; }
		static ::templo::Op OpBoolOr;
		static inline ::templo::Op OpBoolOr_dyn() { return OpBoolOr; }
		static ::templo::Op OpShl;
		static inline ::templo::Op OpShl_dyn() { return OpShl; }
		static ::templo::Op OpShr;
		static inline ::templo::Op OpShr_dyn() { return OpShr; }
		static ::templo::Op OpUShr;
		static inline ::templo::Op OpUShr_dyn() { return OpUShr; }
		static ::templo::Op OpMod;
		static inline ::templo::Op OpMod_dyn() { return OpMod; }
		static ::templo::Op OpCompare;
		static inline ::templo::Op OpCompare_dyn() { return OpCompare; }
};

} // end namespace templo

#endif /* INCLUDED_templo_Op */ 
