package flash.globalization;

@:fakeEnum(String) extern enum LastOperationStatus {
	BUFFER_OVERFLOW_ERROR;
	ERROR_CODE_UNKNOWN;
	ILLEGAL_ARGUMENT_ERROR;
	INDEX_OUT_OF_BOUNDS_ERROR;
	INVALID_ATTR_VALUE;
	INVALID_CHAR_FOUND;
	MEMORY_ALLOCATION_ERROR;
	NO_ERROR;
	NUMBER_OVERFLOW_ERROR;
	PARSE_ERROR;
	PATTERN_SYNTAX_ERROR;
	PLATFORM_API_FAILED;
	TRUNCATED_CHAR_FOUND;
	UNEXPECTED_TOKEN;
	UNSUPPORTED_ERROR;
	USING_DEFAULT_WARNING;
	USING_FALLBACK_WARNING;
}
