// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_markdown_HorizontalRuleSyntax
#define INCLUDED_markdown_HorizontalRuleSyntax

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_markdown_BlockSyntax
#include <markdown/BlockSyntax.h>
#endif
HX_DECLARE_CLASS0(EReg)
HX_DECLARE_CLASS1(markdown,BlockParser)
HX_DECLARE_CLASS1(markdown,BlockSyntax)
HX_DECLARE_CLASS1(markdown,HorizontalRuleSyntax)
HX_DECLARE_CLASS1(markdown,Node)

namespace markdown{


class HXCPP_CLASS_ATTRIBUTES HorizontalRuleSyntax_obj : public  ::markdown::BlockSyntax_obj
{
	public:
		typedef  ::markdown::BlockSyntax_obj super;
		typedef HorizontalRuleSyntax_obj OBJ_;
		HorizontalRuleSyntax_obj();

	public:
		enum { _hx_ClassId = 0x68a21ab6 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false, const char* inName="markdown.HorizontalRuleSyntax")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, false, "markdown.HorizontalRuleSyntax"); }
		static ::hx::ObjectPtr< HorizontalRuleSyntax_obj > __new();
		static ::hx::ObjectPtr< HorizontalRuleSyntax_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~HorizontalRuleSyntax_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("HorizontalRuleSyntax",a3,46,32,a0); }

		  ::EReg get_pattern();
		 ::Dynamic parse( ::markdown::BlockParser parser);
};

} // end namespace markdown

#endif /* INCLUDED_markdown_HorizontalRuleSyntax */ 
