// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_markdown_TextSyntax
#define INCLUDED_markdown_TextSyntax

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_markdown_InlineSyntax
#include <markdown/InlineSyntax.h>
#endif
HX_DECLARE_CLASS1(markdown,InlineParser)
HX_DECLARE_CLASS1(markdown,InlineSyntax)
HX_DECLARE_CLASS1(markdown,TextSyntax)

namespace markdown{


class HXCPP_CLASS_ATTRIBUTES TextSyntax_obj : public  ::markdown::InlineSyntax_obj
{
	public:
		typedef  ::markdown::InlineSyntax_obj super;
		typedef TextSyntax_obj OBJ_;
		TextSyntax_obj();

	public:
		enum { _hx_ClassId = 0x3df529ff };

		void __construct(::String pattern,::String substitute);
		inline void *operator new(size_t inSize, bool inContainer=true, const char* inName="markdown.TextSyntax")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, true, "markdown.TextSyntax"); }
		static ::hx::ObjectPtr< TextSyntax_obj > __new(::String pattern,::String substitute);
		static ::hx::ObjectPtr< TextSyntax_obj > __alloc(::hx::Ctx *_hx_ctx,::String pattern,::String substitute);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~TextSyntax_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(::Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TextSyntax",10,07,36,1d); }

		 bool onMatch( ::markdown::InlineParser parser);
		::String substitute;
};

} // end namespace markdown

#endif /* INCLUDED_markdown_TextSyntax */ 
