// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_38344beec7696400
#define INCLUDED_38344beec7696400
#include "cpp/Int64.h"
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_cpp_marshal_ViewExtensions
#include <cpp/marshal/ViewExtensions.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_exceptions_ArgumentException
#include <haxe/exceptions/ArgumentException.h>
#endif
#ifndef INCLUDED_haxe_exceptions_PosException
#include <haxe/exceptions/PosException.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_7de8773c9a509473_39_new,"haxe.io.Bytes","new",0x3938d57d,"haxe.io.Bytes.new","haxe/io/Bytes.hx",39,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_48_get,"haxe.io.Bytes","get",0x393385b3,"haxe.io.Bytes.get","haxe/io/Bytes.hx",48,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_55_set,"haxe.io.Bytes","set",0x393ca0bf,"haxe.io.Bytes.set","haxe/io/Bytes.hx",55,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_66_blit,"haxe.io.Bytes","blit",0xd098ac78,"haxe.io.Bytes.blit","haxe/io/Bytes.hx",66,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_78_fill,"haxe.io.Bytes","fill",0xd33b42c6,"haxe.io.Bytes.fill","haxe/io/Bytes.hx",78,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_86_sub,"haxe.io.Bytes","sub",0x393cae9d,"haxe.io.Bytes.sub","haxe/io/Bytes.hx",86,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_101_compare,"haxe.io.Bytes","compare",0x46537042,"haxe.io.Bytes.compare","haxe/io/Bytes.hx",101,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_114_getDouble,"haxe.io.Bytes","getDouble",0xc306ed24,"haxe.io.Bytes.getDouble","haxe/io/Bytes.hx",114,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_123_getFloat,"haxe.io.Bytes","getFloat",0x2c9026e9,"haxe.io.Bytes.getFloat","haxe/io/Bytes.hx",123,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_132_setDouble,"haxe.io.Bytes","setDouble",0xa657d930,"haxe.io.Bytes.setDouble","haxe/io/Bytes.hx",132,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_141_setFloat,"haxe.io.Bytes","setFloat",0xdaed805d,"haxe.io.Bytes.setFloat","haxe/io/Bytes.hx",141,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_149_getUInt16,"haxe.io.Bytes","getUInt16",0xa94afaf2,"haxe.io.Bytes.getUInt16","haxe/io/Bytes.hx",149,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_157_setUInt16,"haxe.io.Bytes","setUInt16",0x8c9be6fe,"haxe.io.Bytes.setUInt16","haxe/io/Bytes.hx",157,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_165_getInt32,"haxe.io.Bytes","getInt32",0xe819f49b,"haxe.io.Bytes.getInt32","haxe/io/Bytes.hx",165,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_173_getInt64,"haxe.io.Bytes","getInt64",0xe819f73a,"haxe.io.Bytes.getInt64","haxe/io/Bytes.hx",173,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_181_setInt32,"haxe.io.Bytes","setInt32",0x96774e0f,"haxe.io.Bytes.setInt32","haxe/io/Bytes.hx",181,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_189_setInt64,"haxe.io.Bytes","setInt64",0x967750ae,"haxe.io.Bytes.setInt64","haxe/io/Bytes.hx",189,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_197_getString,"haxe.io.Bytes","getString",0xa16beae4,"haxe.io.Bytes.getString","haxe/io/Bytes.hx",197,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_203_readString,"haxe.io.Bytes","readString",0x5f58954a,"haxe.io.Bytes.readString","haxe/io/Bytes.hx",203,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_210_toString,"haxe.io.Bytes","toString",0x0291226f,"haxe.io.Bytes.toString","haxe/io/Bytes.hx",210,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_217_toHex,"haxe.io.Bytes","toHex",0x14173a7d,"haxe.io.Bytes.toHex","haxe/io/Bytes.hx",217,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_235_getData,"haxe.io.Bytes","getData",0xd7d05d7d,"haxe.io.Bytes.getData","haxe/io/Bytes.hx",235,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_243_alloc,"haxe.io.Bytes","alloc",0x2199ead2,"haxe.io.Bytes.alloc","haxe/io/Bytes.hx",243,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_252_ofString,"haxe.io.Bytes","ofString",0x6e53bb0b,"haxe.io.Bytes.ofString","haxe/io/Bytes.hx",252,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_270_ofData,"haxe.io.Bytes","ofData",0x4f3005e4,"haxe.io.Bytes.ofData","haxe/io/Bytes.hx",270,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_278_ofHex,"haxe.io.Bytes","ofHex",0x2d236861,"haxe.io.Bytes.ofHex","haxe/io/Bytes.hx",278,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_302_fastGet,"haxe.io.Bytes","fastGet",0xa10d56f7,"haxe.io.Bytes.fastGet","haxe/io/Bytes.hx",302,0x68bfff33)
HX_LOCAL_STACK_FRAME(_hx_pos_7de8773c9a509473_218_boot,"haxe.io.Bytes","boot",0xd09af875,"haxe.io.Bytes.boot","haxe/io/Bytes.hx",218,0x68bfff33)

namespace {

struct __Bytes_objget final : public ::hx::AutoCallable_obj< int (int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objget(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objget*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	int HX_LOCAL_RUN(int pos) override {
		return __this->get(pos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objset final : public ::hx::AutoCallable_obj< void (int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objset(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objset*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,int v) override {
		__this->set(pos, v);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objblit final : public ::hx::AutoCallable_obj< void (int, ::haxe::io::Bytes,int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objblit(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objblit*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos, ::haxe::io::Bytes src,int srcpos,int len) override {
		__this->blit(pos, src, srcpos, len);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objfill final : public ::hx::AutoCallable_obj< void (int,int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objfill(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objfill*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,int len,int value) override {
		__this->fill(pos, len, value);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objsub final : public ::hx::AutoCallable_obj<  ::haxe::io::Bytes (int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objsub(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objsub*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	 ::haxe::io::Bytes HX_LOCAL_RUN(int pos,int len) override {
		return __this->sub(pos, len);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objcompare final : public ::hx::AutoCallable_obj< int ( ::haxe::io::Bytes) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objcompare(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objcompare*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	int HX_LOCAL_RUN( ::haxe::io::Bytes other) override {
		return __this->compare(other);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetDouble final : public ::hx::AutoCallable_obj< Float (int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetDouble(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetDouble*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	Float HX_LOCAL_RUN(int pos) override {
		return __this->getDouble(pos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetFloat final : public ::hx::AutoCallable_obj< Float (int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetFloat(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetFloat*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	Float HX_LOCAL_RUN(int pos) override {
		return __this->getFloat(pos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objsetDouble final : public ::hx::AutoCallable_obj< void (int,Float) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objsetDouble(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objsetDouble*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,Float v) override {
		__this->setDouble(pos, v);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objsetFloat final : public ::hx::AutoCallable_obj< void (int,Float) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objsetFloat(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objsetFloat*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,Float v) override {
		__this->setFloat(pos, v);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetUInt16 final : public ::hx::AutoCallable_obj< int (int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetUInt16(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetUInt16*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	int HX_LOCAL_RUN(int pos) override {
		return __this->getUInt16(pos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objsetUInt16 final : public ::hx::AutoCallable_obj< void (int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objsetUInt16(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objsetUInt16*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,int v) override {
		__this->setUInt16(pos, v);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetInt32 final : public ::hx::AutoCallable_obj< int (int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetInt32(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetInt32*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	int HX_LOCAL_RUN(int pos) override {
		return __this->getInt32(pos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetInt64 final : public ::hx::AutoCallable_obj< ::cpp::Int64 (int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetInt64(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetInt64*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::cpp::Int64 HX_LOCAL_RUN(int pos) override {
		return __this->getInt64(pos);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objsetInt32 final : public ::hx::AutoCallable_obj< void (int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objsetInt32(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objsetInt32*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,int v) override {
		__this->setInt32(pos, v);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objsetInt64 final : public ::hx::AutoCallable_obj< void (int,::cpp::Int64) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objsetInt64(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objsetInt64*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(int pos,::cpp::Int64 v) override {
		__this->setInt64(pos, v);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetString final : public ::hx::AutoCallable_obj< ::String (int,int, ::haxe::io::Encoding) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetString(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetString*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::String HX_LOCAL_RUN(int pos,int len, ::haxe::io::Encoding encoding) override {
		return __this->getString(pos, len, encoding);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objreadString final : public ::hx::AutoCallable_obj< ::String (int,int) > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objreadString(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objreadString*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::String HX_LOCAL_RUN(int pos,int len) override {
		return __this->readString(pos, len);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objtoString final : public ::hx::AutoCallable_obj< ::String () > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objtoString(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objtoString*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::String HX_LOCAL_RUN() override {
		return __this->toString();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objtoHex final : public ::hx::AutoCallable_obj< ::String () > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objtoHex(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objtoHex*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::String HX_LOCAL_RUN() override {
		return __this->toHex();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objgetData final : public ::hx::AutoCallable_obj< ::Array< unsigned char > () > {
	::hx::ObjectPtr<haxe::io::Bytes_obj> __this;
	__Bytes_objgetData(::hx::ObjectPtr<haxe::io::Bytes_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objgetData*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::Array< unsigned char > HX_LOCAL_RUN() override {
		return __this->getData();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __Bytes_objalloc final : public ::hx::AutoCallable_obj<  ::haxe::io::Bytes (int) > {
	__Bytes_objalloc() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objalloc*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::haxe::io::Bytes HX_LOCAL_RUN(int length) override {
		return haxe::io::Bytes_obj::alloc(length);
	}
};

::hx::Callable<  ::haxe::io::Bytes (int) > _hx_alloc__Bytes_objalloc;

struct __Bytes_objofString final : public ::hx::AutoCallable_obj<  ::haxe::io::Bytes (::String, ::haxe::io::Encoding) > {
	__Bytes_objofString() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objofString*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::haxe::io::Bytes HX_LOCAL_RUN(::String s, ::haxe::io::Encoding encoding) override {
		return haxe::io::Bytes_obj::ofString(s, encoding);
	}
};

::hx::Callable<  ::haxe::io::Bytes (::String, ::haxe::io::Encoding) > _hx_alloc__Bytes_objofString;

struct __Bytes_objofData final : public ::hx::AutoCallable_obj<  ::haxe::io::Bytes (::Array< unsigned char >) > {
	__Bytes_objofData() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objofData*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::haxe::io::Bytes HX_LOCAL_RUN(::Array< unsigned char > b) override {
		return haxe::io::Bytes_obj::ofData(b);
	}
};

::hx::Callable<  ::haxe::io::Bytes (::Array< unsigned char >) > _hx_alloc__Bytes_objofData;

struct __Bytes_objofHex final : public ::hx::AutoCallable_obj<  ::haxe::io::Bytes (::String) > {
	__Bytes_objofHex() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objofHex*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::haxe::io::Bytes HX_LOCAL_RUN(::String s) override {
		return haxe::io::Bytes_obj::ofHex(s);
	}
};

::hx::Callable<  ::haxe::io::Bytes (::String) > _hx_alloc__Bytes_objofHex;

struct __Bytes_objfastGet final : public ::hx::AutoCallable_obj< int (::Array< unsigned char >,int) > {
	__Bytes_objfastGet() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Bytes_objfastGet*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	int HX_LOCAL_RUN(::Array< unsigned char > b,int pos) override {
		return haxe::io::Bytes_obj::fastGet(b, pos);
	}
};

::hx::Callable< int (::Array< unsigned char >,int) > _hx_alloc__Bytes_objfastGet;

}

namespace haxe{
namespace io{

void Bytes_obj::__construct(int length,::Array< unsigned char > b){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_39_new)
HXLINE(  40)		this->length = length;
HXLINE(  41)		this->b = b;
            	}

::Dynamic Bytes_obj::__CreateEmpty() { return new Bytes_obj; }

void* Bytes_obj::_hx_vtable = 0;

::Dynamic Bytes_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Bytes_obj > _hx_result = new Bytes_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool Bytes_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x195c64b7;
}

int Bytes_obj::get(int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_48_get)
HXDLIN(  48)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN(  48)		return ( (int)(::cpp::marshal::Marshal::readUInt8(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ))) );
            	}


::hx::Callable< int (int) > Bytes_obj::get_dyn() { return new __Bytes_objget(this); }

void Bytes_obj::set(int pos,int v){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_55_set)
HXDLIN(  55)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN(  55)		::cpp::marshal::Marshal::writeUInt8(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ),( (unsigned char)(v) ));
            	}


::hx::Callable< void (int,int) > Bytes_obj::set_dyn() { return new __Bytes_objset(this); }

void Bytes_obj::blit(int pos, ::haxe::io::Bytes src,int srcpos,int len){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_66_blit)
HXLINE(  67)		::cpp::Pointer< unsigned char > srcView = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(src->getData())) );
HXDLIN(  67)		::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > > srcView1 = ( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(srcView,( (::cpp::Int64)(src->length) ))) )->slice(( (::cpp::Int64)(srcpos) ),( (::cpp::Int64)(len) ));
HXLINE(  68)		::cpp::Pointer< unsigned char > dstView = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN(  68)		::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > > dstView1 = ( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(dstView,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ));
HXLINE(  70)		( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(srcView1) )->copyTo(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(dstView1) ));
            	}


::hx::Callable< void (int, ::haxe::io::Bytes,int,int) > Bytes_obj::blit_dyn() { return new __Bytes_objblit(this); }

void Bytes_obj::fill(int pos,int len,int value){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_78_fill)
HXDLIN(  78)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN(  78)		( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ),( (::cpp::Int64)(len) ))) )->fill(value);
            	}


::hx::Callable< void (int,int,int) > Bytes_obj::fill_dyn() { return new __Bytes_objfill(this); }

 ::haxe::io::Bytes Bytes_obj::sub(int pos,int len){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_86_sub)
HXDLIN(  86)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN(  86)		return ::cpp::marshal::ViewExtensions_obj::toBytes_cpp_UInt8(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ),( (::cpp::Int64)(len) ))) ));
            	}


::hx::Callable<  ::haxe::io::Bytes (int,int) > Bytes_obj::sub_dyn() { return new __Bytes_objsub(this); }

int Bytes_obj::compare( ::haxe::io::Bytes other){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_101_compare)
HXLINE( 102)		::cpp::Pointer< unsigned char > fst = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 102)		::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > > fst1 = ::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(fst,( (::cpp::Int64)(this->length) ));
HXLINE( 103)		::cpp::Pointer< unsigned char > snd = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(other->getData())) );
HXDLIN( 103)		::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > > snd1 = ::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(snd,( (::cpp::Int64)(other->length) ));
HXLINE( 105)		return ( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(fst1) )->compare(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(snd1) ));
            	}


::hx::Callable< int ( ::haxe::io::Bytes) > Bytes_obj::compare_dyn() { return new __Bytes_objcompare(this); }

Float Bytes_obj::getDouble(int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_114_getDouble)
HXDLIN( 114)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 114)		return ( (Float)(::cpp::marshal::Marshal::readFloat64(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ))) );
            	}


::hx::Callable< Float (int) > Bytes_obj::getDouble_dyn() { return new __Bytes_objgetDouble(this); }

Float Bytes_obj::getFloat(int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_123_getFloat)
HXDLIN( 123)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 123)		return ( (Float)(::cpp::marshal::Marshal::readFloat32(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ))) );
            	}


::hx::Callable< Float (int) > Bytes_obj::getFloat_dyn() { return new __Bytes_objgetFloat(this); }

void Bytes_obj::setDouble(int pos,Float v){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_132_setDouble)
HXDLIN( 132)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 132)		::cpp::marshal::Marshal::writeFloat64(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ),( (double)(v) ));
            	}


::hx::Callable< void (int,Float) > Bytes_obj::setDouble_dyn() { return new __Bytes_objsetDouble(this); }

void Bytes_obj::setFloat(int pos,Float v){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_141_setFloat)
HXDLIN( 141)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 141)		::cpp::marshal::Marshal::writeFloat32(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ),( (float)(v) ));
            	}


::hx::Callable< void (int,Float) > Bytes_obj::setFloat_dyn() { return new __Bytes_objsetFloat(this); }

int Bytes_obj::getUInt16(int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_149_getUInt16)
HXDLIN( 149)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 149)		return ( (int)(::cpp::marshal::Marshal::readUInt16(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ))) );
            	}


::hx::Callable< int (int) > Bytes_obj::getUInt16_dyn() { return new __Bytes_objgetUInt16(this); }

void Bytes_obj::setUInt16(int pos,int v){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_157_setUInt16)
HXDLIN( 157)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 157)		::cpp::marshal::Marshal::writeUInt16(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ),( (unsigned short)(v) ));
            	}


::hx::Callable< void (int,int) > Bytes_obj::setUInt16_dyn() { return new __Bytes_objsetUInt16(this); }

int Bytes_obj::getInt32(int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_165_getInt32)
HXDLIN( 165)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 165)		return ::cpp::marshal::Marshal::readInt32(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ));
            	}


::hx::Callable< int (int) > Bytes_obj::getInt32_dyn() { return new __Bytes_objgetInt32(this); }

::cpp::Int64 Bytes_obj::getInt64(int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_173_getInt64)
HXDLIN( 173)		::cpp::Pointer< unsigned char > this1 = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 173)		return ::cpp::marshal::Marshal::readInt64(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(this1,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ));
            	}


::hx::Callable< ::cpp::Int64 (int) > Bytes_obj::getInt64_dyn() { return new __Bytes_objgetInt64(this); }

void Bytes_obj::setInt32(int pos,int v){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_181_setInt32)
HXDLIN( 181)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 181)		::cpp::marshal::Marshal::writeInt32(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ),v);
            	}


::hx::Callable< void (int,int) > Bytes_obj::setInt32_dyn() { return new __Bytes_objsetInt32(this); }

void Bytes_obj::setInt64(int pos,::cpp::Int64 v){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_189_setInt64)
HXDLIN( 189)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 189)		::cpp::marshal::Marshal::writeInt64(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ))) ),v);
            	}


::hx::Callable< void (int,::cpp::Int64) > Bytes_obj::setInt64_dyn() { return new __Bytes_objsetInt64(this); }

::String Bytes_obj::getString(int pos,int len, ::haxe::io::Encoding encoding){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_197_getString)
HXDLIN( 197)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(this->getData())) );
HXDLIN( 197)		return ::cpp::encoding::Utf8::decode(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(this->length) ))) )->slice(( (::cpp::Int64)(pos) ),( (::cpp::Int64)(len) ))) ));
            	}


::hx::Callable< ::String (int,int, ::haxe::io::Encoding) > Bytes_obj::getString_dyn() { return new __Bytes_objgetString(this); }

::String Bytes_obj::readString(int pos,int len){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_203_readString)
HXDLIN( 203)		return this->getString(pos,len,null());
            	}


::hx::Callable< ::String (int,int) > Bytes_obj::readString_dyn() { return new __Bytes_objreadString(this); }

::String Bytes_obj::toString(){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_210_toString)
HXDLIN( 210)		return this->getString(0,this->length,null());
            	}


::hx::Callable< ::String () > Bytes_obj::toString_dyn() { return new __Bytes_objtoString(this); }

::String Bytes_obj::toHex(){
            	HX_GC_STACKFRAME(&_hx_pos_7de8773c9a509473_217_toHex)
HXLINE( 220)		 ::StringBuf s =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 222)		{
HXLINE( 222)			int _g = 0;
HXDLIN( 222)			int _g1 = this->length;
HXDLIN( 222)			while((_g < _g1)){
HXLINE( 222)				int i = _g++;
HXLINE( 223)				int c = this->get(i);
HXLINE( 224)				{
HXLINE( 224)					int c1 = ::haxe::io::Bytes_obj::toHex_chars->__get((c >> 4));
HXDLIN( 224)					if ((c1 >= 127)) {
HXLINE( 224)						::String x = ::String::fromCharCode(c1);
HXDLIN( 224)						if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 224)							s->flush();
            						}
HXDLIN( 224)						if (::hx::IsNull( s->b )) {
HXLINE( 224)							s->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            						}
            						else {
HXLINE( 224)							::Array< ::String > s1 = s->b;
HXDLIN( 224)							s1->push(::Std_obj::string(x));
            						}
            					}
            					else {
HXLINE( 224)						if (::hx::IsNull( s->charBuf )) {
HXLINE( 224)							s->charBuf = ::Array_obj< char >::__new();
            						}
HXDLIN( 224)						s->charBuf->push(c1);
            					}
            				}
HXLINE( 225)				{
HXLINE( 225)					int c2 = ::haxe::io::Bytes_obj::toHex_chars->__get((c & 15));
HXDLIN( 225)					if ((c2 >= 127)) {
HXLINE( 225)						::String x1 = ::String::fromCharCode(c2);
HXDLIN( 225)						if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 225)							s->flush();
            						}
HXDLIN( 225)						if (::hx::IsNull( s->b )) {
HXLINE( 225)							s->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x1));
            						}
            						else {
HXLINE( 225)							::Array< ::String > s2 = s->b;
HXDLIN( 225)							s2->push(::Std_obj::string(x1));
            						}
            					}
            					else {
HXLINE( 225)						if (::hx::IsNull( s->charBuf )) {
HXLINE( 225)							s->charBuf = ::Array_obj< char >::__new();
            						}
HXDLIN( 225)						s->charBuf->push(c2);
            					}
            				}
            			}
            		}
HXLINE( 228)		return s->toString();
            	}


::hx::Callable< ::String () > Bytes_obj::toHex_dyn() { return new __Bytes_objtoHex(this); }

::Array< unsigned char > Bytes_obj::getData(){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_235_getData)
HXDLIN( 235)		return this->b;
            	}


::hx::Callable< ::Array< unsigned char > () > Bytes_obj::getData_dyn() { return new __Bytes_objgetData(this); }

 ::haxe::io::Bytes Bytes_obj::alloc(int length){
            	HX_GC_STACKFRAME(&_hx_pos_7de8773c9a509473_243_alloc)
HXDLIN( 243)		return  ::haxe::io::Bytes_obj::__alloc( HX_CTX ,length,::Array_obj< unsigned char >::__new(length));
            	}


::hx::Callable<  ::haxe::io::Bytes (int) > Bytes_obj::alloc_dyn() { return _hx_alloc__Bytes_objalloc; }

 ::haxe::io::Bytes Bytes_obj::ofString(::String s, ::haxe::io::Encoding encoding){
            	HX_GC_STACKFRAME(&_hx_pos_7de8773c9a509473_252_ofString)
HXDLIN( 252)		if (::cpp::encoding::Ascii::isEncoded(s)) {
HXLINE( 253)			return ::cpp::marshal::ViewExtensions_obj::toBytes_cpp_UInt8(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< char > >)(::cpp::marshal::Marshal::asCharView(s)) )->reinterpret< unsigned char >()) ));
            		}
            		else {
HXLINE( 255)			::cpp::Int64 count = ::cpp::encoding::Utf8::getByteCount(s);
HXLINE( 256)			int bytes = _hx_int64_high(count);
HXDLIN( 256)			if ((bytes != (_hx_int64_low(count) >> 31))) {
HXLINE( 256)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("Overflow",62,9f,ed,1a)));
            			}
HXDLIN( 256)			 ::haxe::io::Bytes bytes1 = ::haxe::io::Bytes_obj::alloc(_hx_int64_low(count));
HXLINE( 258)			::cpp::Pointer< unsigned char > a = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(bytes1->getData())) );
HXDLIN( 258)			if (_hx_int64_neq(::cpp::encoding::Utf8::encode(s,( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(a,( (::cpp::Int64)(bytes1->length) ))) )),count)) {
HXLINE( 259)				HX_STACK_DO_THROW( ::haxe::Exception_obj::__alloc( HX_CTX ,HX_("Failed to encode string to UTF8",cf,5c,84,d4),null(),null()));
            			}
            			else {
HXLINE( 261)				return bytes1;
            			}
            		}
HXLINE( 252)		return null();
            	}


::hx::Callable<  ::haxe::io::Bytes (::String, ::haxe::io::Encoding) > Bytes_obj::ofString_dyn() { return _hx_alloc__Bytes_objofString; }

 ::haxe::io::Bytes Bytes_obj::ofData(::Array< unsigned char > b){
            	HX_GC_STACKFRAME(&_hx_pos_7de8773c9a509473_270_ofData)
HXDLIN( 270)		return  ::haxe::io::Bytes_obj::__alloc( HX_CTX ,b->length,b);
            	}


::hx::Callable<  ::haxe::io::Bytes (::Array< unsigned char >) > Bytes_obj::ofData_dyn() { return _hx_alloc__Bytes_objofData; }

 ::haxe::io::Bytes Bytes_obj::ofHex(::String s){
            	HX_GC_STACKFRAME(&_hx_pos_7de8773c9a509473_278_ofHex)
HXLINE( 279)		if (((s.length & 1) != 0)) {
HXLINE( 280)			HX_STACK_DO_THROW( ::haxe::exceptions::ArgumentException_obj::__alloc( HX_CTX ,HX_("s",73,00,00,00),HX_("Not a hex string (odd number of digits)",96,4b,d1,a4),null(),::hx::SourceInfo(HX_("haxe/io/Bytes.hx",33,ff,bf,68),280,HX_("haxe.io.Bytes",0b,53,6f,9f),HX_("ofHex",04,22,1d,2d))));
            		}
HXLINE( 283)		 ::haxe::io::Bytes output = ::haxe::io::Bytes_obj::alloc((s.length >> 1));
HXLINE( 284)		{
HXLINE( 284)			int _g = 0;
HXDLIN( 284)			int _g1 = output->length;
HXDLIN( 284)			while((_g < _g1)){
HXLINE( 284)				int i = _g++;
HXLINE( 285)				int highCode = s.cca((i * 2));
HXLINE( 286)				int lowCode = s.cca(((i * 2) + 1));
HXLINE( 287)				int high = ((highCode & 15) + (((highCode & 64) >> 6) * 9));
HXLINE( 288)				int low = ((lowCode & 15) + (((lowCode & 64) >> 6) * 9));
HXLINE( 290)				output->set(i,(((high << 4) | low) & 255));
            			}
            		}
HXLINE( 293)		return output;
            	}


::hx::Callable<  ::haxe::io::Bytes (::String) > Bytes_obj::ofHex_dyn() { return _hx_alloc__Bytes_objofHex; }

int Bytes_obj::fastGet(::Array< unsigned char > b,int pos){
            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_302_fastGet)
HXDLIN( 302)		::cpp::Pointer< unsigned char > _hx_tmp = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::ofArray(b)) );
HXDLIN( 302)		return ( (int)(( (::cpp::marshal::ValueReference< ::cpp::marshal::View< unsigned char > >)(::cpp::marshal::ValueType< ::cpp::marshal::View< unsigned char > >(_hx_tmp,( (::cpp::Int64)(b->length) ))) )->ptr.ptr[pos]) );
            	}


::hx::Callable< int (::Array< unsigned char >,int) > Bytes_obj::fastGet_dyn() { return _hx_alloc__Bytes_objfastGet; }

::Array< int > Bytes_obj::toHex_chars;


::hx::ObjectPtr< Bytes_obj > Bytes_obj::__new(int length,::Array< unsigned char > b) {
	::hx::ObjectPtr< Bytes_obj > __this = new Bytes_obj();
	__this->__construct(length,b);
	return __this;
}

::hx::ObjectPtr< Bytes_obj > Bytes_obj::__alloc(::hx::Ctx *_hx_ctx,int length,::Array< unsigned char > b) {
	Bytes_obj* __this = (Bytes_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Bytes_obj), true, "haxe.io.Bytes"));
	*(void **)__this = Bytes_obj::_hx_vtable;
	__this->__construct(length,b);
	return __this;
}

Bytes_obj::Bytes_obj()
{
}

void Bytes_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Bytes);
	HX_MARK_MEMBER_NAME(length, "length");
	HX_MARK_MEMBER_NAME(b, "b");
	HX_MARK_END_CLASS();
}

void Bytes_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(length, "length");
	HX_VISIT_MEMBER_NAME(b, "b");
}

::hx::Val Bytes_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"b") ) { return ::hx::Val( b ); }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		if (HX_FIELD_EQ(inName,"set") ) { return ::hx::Val( set_dyn() ); }
		if (HX_FIELD_EQ(inName,"sub") ) { return ::hx::Val( sub_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"blit") ) { return ::hx::Val( blit_dyn() ); }
		if (HX_FIELD_EQ(inName,"fill") ) { return ::hx::Val( fill_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"toHex") ) { return ::hx::Val( toHex_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { return ::hx::Val( length ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"compare") ) { return ::hx::Val( compare_dyn() ); }
		if (HX_FIELD_EQ(inName,"getData") ) { return ::hx::Val( getData_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"getFloat") ) { return ::hx::Val( getFloat_dyn() ); }
		if (HX_FIELD_EQ(inName,"setFloat") ) { return ::hx::Val( setFloat_dyn() ); }
		if (HX_FIELD_EQ(inName,"getInt32") ) { return ::hx::Val( getInt32_dyn() ); }
		if (HX_FIELD_EQ(inName,"getInt64") ) { return ::hx::Val( getInt64_dyn() ); }
		if (HX_FIELD_EQ(inName,"setInt32") ) { return ::hx::Val( setInt32_dyn() ); }
		if (HX_FIELD_EQ(inName,"setInt64") ) { return ::hx::Val( setInt64_dyn() ); }
		if (HX_FIELD_EQ(inName,"toString") ) { return ::hx::Val( toString_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"getDouble") ) { return ::hx::Val( getDouble_dyn() ); }
		if (HX_FIELD_EQ(inName,"setDouble") ) { return ::hx::Val( setDouble_dyn() ); }
		if (HX_FIELD_EQ(inName,"getUInt16") ) { return ::hx::Val( getUInt16_dyn() ); }
		if (HX_FIELD_EQ(inName,"setUInt16") ) { return ::hx::Val( setUInt16_dyn() ); }
		if (HX_FIELD_EQ(inName,"getString") ) { return ::hx::Val( getString_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"readString") ) { return ::hx::Val( readString_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool Bytes_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"alloc") ) { outValue = alloc_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"ofHex") ) { outValue = ofHex_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"ofData") ) { outValue = ofData_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"fastGet") ) { outValue = fastGet_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"ofString") ) { outValue = ofString_dyn(); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"toHex_chars") ) { outValue = toHex_chars; return true; }
	}
	return false;
}

::hx::Val Bytes_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { length = inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

bool Bytes_obj::__SetStatic(const ::String& inName, ::Dynamic& ioValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 11:
		if (HX_FIELD_EQ(inName,"toHex_chars") ) { toHex_chars = ioValue.Cast< ::Array< int > >(); return true; }
	}
	return false;
}

void Bytes_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("length",e6,94,07,9f));
	outFields->push(HX_("b",62,00,00,00));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Bytes_obj_sMemberStorageInfo[] = {
	{ ::hx::fsInt, (int)offsetof(Bytes_obj, length), HX_("length",e6,94,07,9f) },
	{ ::hx::fsObject /* ::Array< unsigned char > */ , (int)offsetof(Bytes_obj, b), HX_("b",62,00,00,00) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo Bytes_obj_sStaticStorageInfo[] = {
	{ ::hx::fsObject /* ::Array< int > */ , (void*) &Bytes_obj::toHex_chars, HX_("toHex_chars",3e,b0,89,69) },
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static ::String Bytes_obj_sMemberFields[] = {
	HX_("get",96,80,4e,00),
	HX_("set",a2,9b,57,00),
	HX_("blit",35,38,19,41),
	HX_("fill",83,ce,bb,43),
	HX_("sub",80,a9,57,00),
	HX_("compare",a5,18,69,83),
	HX_("getDouble",47,b4,21,af),
	HX_("getFloat",26,d5,6d,62),
	HX_("setDouble",53,a0,72,92),
	HX_("setFloat",9a,2e,cb,10),
	HX_("getUInt16",15,c2,65,95),
	HX_("setUInt16",21,ae,b6,78),
	HX_("getInt32",d8,a2,f7,1d),
	HX_("getInt64",77,a5,f7,1d),
	HX_("setInt32",4c,fc,54,cc),
	HX_("setInt64",eb,fe,54,cc),
	HX_("getString",07,b2,86,8d),
	HX_("readString",c7,0c,ac,0a),
	HX_("toString",ac,d0,6e,38),
	HX_("toHex",20,f4,10,14),
	HX_("getData",e0,05,e6,14),
	HX_("length",e6,94,07,9f),
	HX_("b",62,00,00,00),
	::String(null())
};

static void Bytes_obj_sMarkStatics(HX_MARK_PARAMS) { 
	HX_MARK_MEMBER_NAME(Bytes_obj::toHex_chars, "toHex_chars");
 };

#ifdef HXCPP_VISIT_ALLOCS
static void Bytes_obj_sVisitStatics(HX_VISIT_PARAMS) { 
	HX_VISIT_MEMBER_NAME(Bytes_obj::toHex_chars, "toHex_chars");
 };

#endif

::hx::Class Bytes_obj::__mClass;

static ::String Bytes_obj_sStaticFields[] = {
	HX_("alloc",75,a4,93,21),
	HX_("ofString",48,69,31,a4),
	HX_("ofData",e1,ba,b8,49),
	HX_("ofHex",04,22,1d,2d),
	HX_("fastGet",5a,ff,22,de),
	HX_("toHex_chars",3e,b0,89,69),
	::String(null())
};

void Bytes_obj::__register()
{
	Bytes_obj _hx_dummy;
	Bytes_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.io.Bytes",0b,53,6f,9f);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Bytes_obj::__GetStatic;
	__mClass->mSetStaticField = &Bytes_obj::__SetStatic;
	__mClass->mMarkFunc = Bytes_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Bytes_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Bytes_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Bytes_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Bytes_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Bytes_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Bytes_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Bytes_obj::__boot()
{
_hx_alloc__Bytes_objalloc = new (::hx::NewObjectType::NewObjConst) __Bytes_objalloc();

_hx_alloc__Bytes_objofString = new (::hx::NewObjectType::NewObjConst) __Bytes_objofString();

_hx_alloc__Bytes_objofData = new (::hx::NewObjectType::NewObjConst) __Bytes_objofData();

_hx_alloc__Bytes_objofHex = new (::hx::NewObjectType::NewObjConst) __Bytes_objofHex();

_hx_alloc__Bytes_objfastGet = new (::hx::NewObjectType::NewObjConst) __Bytes_objfastGet();

{
HX_BEGIN_LOCAL_FUNC_S0(::hx::AutoCallable_obj< ::Array< int >() >, _hx_Closure_0)
            		::Array< int > HX_LOCAL_RUN(  ){
            			HX_STACKFRAME(&_hx_pos_7de8773c9a509473_218_boot)
HXDLIN( 218)			::Array< int > _g = ::Array_obj< int >::__new(0);
HXDLIN( 218)			{
HXDLIN( 218)				int _g_offset = 0;
HXDLIN( 218)				::String _g_s = HX_("0123456789abcdef",68,7e,d5,ef);
HXDLIN( 218)				while((_g_offset < _g_s.length)){
HXDLIN( 218)					int c = _g_s.cca(_g_offset++);
HXDLIN( 218)					_g->push(c);
            				}
            			}
HXDLIN( 218)			return _g;
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_7de8773c9a509473_218_boot)
HXDLIN( 218)		::haxe::io::Bytes_obj::toHex_chars = ::hx::Callable< ::Array< int >() >(new _hx_Closure_0())();
            	}
}

} // end namespace haxe
} // end namespace io
