// Generated by Haxe
using System;

namespace haxe.lang
{
    /// <summary>
    /// Runtime helpers for Haxe dynamic operations.
    /// </summary>
    public static class Runtime
    {
        /// <summary>
        /// Converts a dynamic value to int, handling null and type conversions.
        /// </summary>
        public static int toInt(object d)
        {
            if (d == null) return 0;
            if (d is int i) return i;
            if (d is double dbl) return (int)dbl;
            if (d is float f) return (int)f;
            if (d is long l) return (int)l;
            if (d is IConvertible c) return c.ToInt32(null);
            return 0;
        }

        /// <summary>
        /// Converts a dynamic value to double, handling null and type conversions.
        /// </summary>
        public static double toDouble(object d)
        {
            if (d == null) return 0.0;
            if (d is double dbl) return dbl;
            if (d is float f) return (double)f;
            if (d is int i) return (double)i;
            if (d is long l) return (double)l;
            if (d is IConvertible c) return c.ToDouble(null);
            return 0.0;
        }

        /// <summary>
        /// Converts a dynamic value to bool, handling null.
        /// </summary>
        public static bool toBool(object d)
        {
            if (d == null) return false;
            if (d is bool b) return b;
            return false;
        }
    }
}
