package flash.ui;

extern class Keyboard {
	@:require(flash10_1) static var A(default,never) : UInt;
	@:require(flash10_1) static var ALTERNATE(default,never) : UInt;
	@:require(flash10_2) static var AUDIO(default,never) : UInt;
	@:require(flash10_1) static var B(default,never) : UInt;
	@:require(flash10_2) static var BACK(default,never) : UInt;
	@:require(flash10_1) static var BACKQUOTE(default,never) : UInt;
	@:require(flash10_1) static var BACKSLASH(default,never) : UInt;
	static var BACKSPACE(default,never) : UInt;
	@:require(flash10_2) static var BLUE(default,never) : UInt;
	@:require(flash10_1) static var C(default,never) : UInt;
	static var CAPS_LOCK(default,never) : UInt;
	@:require(flash10_2) static var CHANNEL_DOWN(default,never) : UInt;
	@:require(flash10_2) static var CHANNEL_UP(default,never) : UInt;
	@:require(flash10_1) static var COMMA(default,never) : UInt;
	@:require(flash10_1) static var COMMAND(default,never) : UInt;
	static var CONTROL(default,never) : UInt;
	@:require(flash10_1) static var CharCodeStrings(default,never) : Array<Dynamic>;
	@:require(flash10_1) static var D(default,never) : UInt;
	static var DELETE(default,never) : UInt;
	static var DOWN(default,never) : UInt;
	@:require(flash10_2) static var DVR(default,never) : UInt;
	@:require(flash10_1) static var E(default,never) : UInt;
	static var END(default,never) : UInt;
	static var ENTER(default,never) : UInt;
	@:require(flash10_1) static var EQUAL(default,never) : UInt;
	static var ESCAPE(default,never) : UInt;
	@:require(flash10_2) static var EXIT(default,never) : UInt;
	@:require(flash10_1) static var F(default,never) : UInt;
	static var F1(default,never) : UInt;
	static var F10(default,never) : UInt;
	static var F11(default,never) : UInt;
	static var F12(default,never) : UInt;
	static var F13(default,never) : UInt;
	static var F14(default,never) : UInt;
	static var F15(default,never) : UInt;
	static var F2(default,never) : UInt;
	static var F3(default,never) : UInt;
	static var F4(default,never) : UInt;
	static var F5(default,never) : UInt;
	static var F6(default,never) : UInt;
	static var F7(default,never) : UInt;
	static var F8(default,never) : UInt;
	static var F9(default,never) : UInt;
	@:require(flash10_2) static var FAST_FORWARD(default,never) : UInt;
	@:require(flash10_1) static var G(default,never) : UInt;
	@:require(flash10_2) static var GREEN(default,never) : UInt;
	@:require(flash10_2) static var GUIDE(default,never) : UInt;
	@:require(flash10_1) static var H(default,never) : UInt;
	@:require(flash10_2) static var HELP(default,never) : UInt;
	static var HOME(default,never) : UInt;
	@:require(flash10_1) static var I(default,never) : UInt;
	@:require(flash10_2) static var INFO(default,never) : UInt;
	@:require(flash10_2) static var INPUT(default,never) : UInt;
	static var INSERT(default,never) : UInt;
	@:require(flash10_1) static var J(default,never) : UInt;
	@:require(flash10_1) static var K(default,never) : UInt;
	@:require(flash10_1) static var KEYNAME_BEGIN(default,never) : String;
	@:require(flash10_1) static var KEYNAME_BREAK(default,never) : String;
	@:require(flash10_1) static var KEYNAME_CLEARDISPLAY(default,never) : String;
	@:require(flash10_1) static var KEYNAME_CLEARLINE(default,never) : String;
	@:require(flash10_1) static var KEYNAME_DELETE(default,never) : String;
	@:require(flash10_1) static var KEYNAME_DELETECHAR(default,never) : String;
	@:require(flash10_1) static var KEYNAME_DELETELINE(default,never) : String;
	@:require(flash10_1) static var KEYNAME_DOWNARROW(default,never) : String;
	@:require(flash10_1) static var KEYNAME_END(default,never) : String;
	@:require(flash10_1) static var KEYNAME_EXECUTE(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F1(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F10(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F11(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F12(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F13(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F14(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F15(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F16(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F17(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F18(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F19(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F2(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F20(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F21(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F22(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F23(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F24(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F25(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F26(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F27(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F28(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F29(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F3(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F30(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F31(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F32(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F33(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F34(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F35(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F4(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F5(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F6(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F7(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F8(default,never) : String;
	@:require(flash10_1) static var KEYNAME_F9(default,never) : String;
	@:require(flash10_1) static var KEYNAME_FIND(default,never) : String;
	@:require(flash10_1) static var KEYNAME_HELP(default,never) : String;
	@:require(flash10_1) static var KEYNAME_HOME(default,never) : String;
	@:require(flash10_1) static var KEYNAME_INSERT(default,never) : String;
	@:require(flash10_1) static var KEYNAME_INSERTCHAR(default,never) : String;
	@:require(flash10_1) static var KEYNAME_INSERTLINE(default,never) : String;
	@:require(flash10_1) static var KEYNAME_LEFTARROW(default,never) : String;
	@:require(flash10_1) static var KEYNAME_MENU(default,never) : String;
	@:require(flash10_1) static var KEYNAME_MODESWITCH(default,never) : String;
	@:require(flash10_1) static var KEYNAME_NEXT(default,never) : String;
	@:require(flash10_1) static var KEYNAME_PAGEDOWN(default,never) : String;
	@:require(flash10_1) static var KEYNAME_PAGEUP(default,never) : String;
	@:require(flash10_1) static var KEYNAME_PAUSE(default,never) : String;
	@:require(flash10_1) static var KEYNAME_PREV(default,never) : String;
	@:require(flash10_1) static var KEYNAME_PRINT(default,never) : String;
	@:require(flash10_1) static var KEYNAME_PRINTSCREEN(default,never) : String;
	@:require(flash10_1) static var KEYNAME_REDO(default,never) : String;
	@:require(flash10_1) static var KEYNAME_RESET(default,never) : String;
	@:require(flash10_1) static var KEYNAME_RIGHTARROW(default,never) : String;
	@:require(flash10_1) static var KEYNAME_SCROLLLOCK(default,never) : String;
	@:require(flash10_1) static var KEYNAME_SELECT(default,never) : String;
	@:require(flash10_1) static var KEYNAME_STOP(default,never) : String;
	@:require(flash10_1) static var KEYNAME_SYSREQ(default,never) : String;
	@:require(flash10_1) static var KEYNAME_SYSTEM(default,never) : String;
	@:require(flash10_1) static var KEYNAME_UNDO(default,never) : String;
	@:require(flash10_1) static var KEYNAME_UPARROW(default,never) : String;
	@:require(flash10_1) static var KEYNAME_USER(default,never) : String;
	@:require(flash10_1) static var L(default,never) : UInt;
	@:require(flash10_2) static var LAST(default,never) : UInt;
	static var LEFT(default,never) : UInt;
	@:require(flash10_1) static var LEFTBRACKET(default,never) : UInt;
	@:require(flash10_2) static var LIVE(default,never) : UInt;
	@:require(flash10_1) static var M(default,never) : UInt;
	@:require(flash10_2) static var MASTER_SHELL(default,never) : UInt;
	@:require(flash10_2) static var MENU(default,never) : UInt;
	@:require(flash10_1) static var MINUS(default,never) : UInt;
	@:require(flash10_1) static var N(default,never) : UInt;
	@:require(flash10_2) static var NEXT(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_0(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_1(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_2(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_3(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_4(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_5(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_6(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_7(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_8(default,never) : UInt;
	@:require(flash10_1) static var NUMBER_9(default,never) : UInt;
	@:require(flash10_1) static var NUMPAD(default,never) : UInt;
	static var NUMPAD_0(default,never) : UInt;
	static var NUMPAD_1(default,never) : UInt;
	static var NUMPAD_2(default,never) : UInt;
	static var NUMPAD_3(default,never) : UInt;
	static var NUMPAD_4(default,never) : UInt;
	static var NUMPAD_5(default,never) : UInt;
	static var NUMPAD_6(default,never) : UInt;
	static var NUMPAD_7(default,never) : UInt;
	static var NUMPAD_8(default,never) : UInt;
	static var NUMPAD_9(default,never) : UInt;
	static var NUMPAD_ADD(default,never) : UInt;
	static var NUMPAD_DECIMAL(default,never) : UInt;
	static var NUMPAD_DIVIDE(default,never) : UInt;
	static var NUMPAD_ENTER(default,never) : UInt;
	static var NUMPAD_MULTIPLY(default,never) : UInt;
	static var NUMPAD_SUBTRACT(default,never) : UInt;
	@:require(flash10_1) static var O(default,never) : UInt;
	@:require(flash10_1) static var P(default,never) : UInt;
	static var PAGE_DOWN(default,never) : UInt;
	static var PAGE_UP(default,never) : UInt;
	@:require(flash10_2) static var PAUSE(default,never) : UInt;
	@:require(flash10_1) static var PERIOD(default,never) : UInt;
	@:require(flash10_2) static var PLAY(default,never) : UInt;
	@:require(flash10_2) static var PREVIOUS(default,never) : UInt;
	@:require(flash10_1) static var Q(default,never) : UInt;
	@:require(flash10_1) static var QUOTE(default,never) : UInt;
	@:require(flash10_1) static var R(default,never) : UInt;
	@:require(flash10_2) static var RECORD(default,never) : UInt;
	@:require(flash10_2) static var RED(default,never) : UInt;
	@:require(flash10_2) static var REWIND(default,never) : UInt;
	static var RIGHT(default,never) : UInt;
	@:require(flash10_1) static var RIGHTBRACKET(default,never) : UInt;
	@:require(flash10_1) static var S(default,never) : UInt;
	@:require(flash10_2) static var SEARCH(default,never) : UInt;
	@:require(flash10_1) static var SEMICOLON(default,never) : UInt;
	@:require(flash10_2) static var SETUP(default,never) : UInt;
	static var SHIFT(default,never) : UInt;
	@:require(flash10_2) static var SKIP_BACKWARD(default,never) : UInt;
	@:require(flash10_2) static var SKIP_FORWARD(default,never) : UInt;
	@:require(flash10_1) static var SLASH(default,never) : UInt;
	static var SPACE(default,never) : UInt;
	@:require(flash10_2) static var STOP(default,never) : UInt;
	@:require(flash10_1) static var STRING_BEGIN(default,never) : String;
	@:require(flash10_1) static var STRING_BREAK(default,never) : String;
	@:require(flash10_1) static var STRING_CLEARDISPLAY(default,never) : String;
	@:require(flash10_1) static var STRING_CLEARLINE(default,never) : String;
	@:require(flash10_1) static var STRING_DELETE(default,never) : String;
	@:require(flash10_1) static var STRING_DELETECHAR(default,never) : String;
	@:require(flash10_1) static var STRING_DELETELINE(default,never) : String;
	@:require(flash10_1) static var STRING_DOWNARROW(default,never) : String;
	@:require(flash10_1) static var STRING_END(default,never) : String;
	@:require(flash10_1) static var STRING_EXECUTE(default,never) : String;
	@:require(flash10_1) static var STRING_F1(default,never) : String;
	@:require(flash10_1) static var STRING_F10(default,never) : String;
	@:require(flash10_1) static var STRING_F11(default,never) : String;
	@:require(flash10_1) static var STRING_F12(default,never) : String;
	@:require(flash10_1) static var STRING_F13(default,never) : String;
	@:require(flash10_1) static var STRING_F14(default,never) : String;
	@:require(flash10_1) static var STRING_F15(default,never) : String;
	@:require(flash10_1) static var STRING_F16(default,never) : String;
	@:require(flash10_1) static var STRING_F17(default,never) : String;
	@:require(flash10_1) static var STRING_F18(default,never) : String;
	@:require(flash10_1) static var STRING_F19(default,never) : String;
	@:require(flash10_1) static var STRING_F2(default,never) : String;
	@:require(flash10_1) static var STRING_F20(default,never) : String;
	@:require(flash10_1) static var STRING_F21(default,never) : String;
	@:require(flash10_1) static var STRING_F22(default,never) : String;
	@:require(flash10_1) static var STRING_F23(default,never) : String;
	@:require(flash10_1) static var STRING_F24(default,never) : String;
	@:require(flash10_1) static var STRING_F25(default,never) : String;
	@:require(flash10_1) static var STRING_F26(default,never) : String;
	@:require(flash10_1) static var STRING_F27(default,never) : String;
	@:require(flash10_1) static var STRING_F28(default,never) : String;
	@:require(flash10_1) static var STRING_F29(default,never) : String;
	@:require(flash10_1) static var STRING_F3(default,never) : String;
	@:require(flash10_1) static var STRING_F30(default,never) : String;
	@:require(flash10_1) static var STRING_F31(default,never) : String;
	@:require(flash10_1) static var STRING_F32(default,never) : String;
	@:require(flash10_1) static var STRING_F33(default,never) : String;
	@:require(flash10_1) static var STRING_F34(default,never) : String;
	@:require(flash10_1) static var STRING_F35(default,never) : String;
	@:require(flash10_1) static var STRING_F4(default,never) : String;
	@:require(flash10_1) static var STRING_F5(default,never) : String;
	@:require(flash10_1) static var STRING_F6(default,never) : String;
	@:require(flash10_1) static var STRING_F7(default,never) : String;
	@:require(flash10_1) static var STRING_F8(default,never) : String;
	@:require(flash10_1) static var STRING_F9(default,never) : String;
	@:require(flash10_1) static var STRING_FIND(default,never) : String;
	@:require(flash10_1) static var STRING_HELP(default,never) : String;
	@:require(flash10_1) static var STRING_HOME(default,never) : String;
	@:require(flash10_1) static var STRING_INSERT(default,never) : String;
	@:require(flash10_1) static var STRING_INSERTCHAR(default,never) : String;
	@:require(flash10_1) static var STRING_INSERTLINE(default,never) : String;
	@:require(flash10_1) static var STRING_LEFTARROW(default,never) : String;
	@:require(flash10_1) static var STRING_MENU(default,never) : String;
	@:require(flash10_1) static var STRING_MODESWITCH(default,never) : String;
	@:require(flash10_1) static var STRING_NEXT(default,never) : String;
	@:require(flash10_1) static var STRING_PAGEDOWN(default,never) : String;
	@:require(flash10_1) static var STRING_PAGEUP(default,never) : String;
	@:require(flash10_1) static var STRING_PAUSE(default,never) : String;
	@:require(flash10_1) static var STRING_PREV(default,never) : String;
	@:require(flash10_1) static var STRING_PRINT(default,never) : String;
	@:require(flash10_1) static var STRING_PRINTSCREEN(default,never) : String;
	@:require(flash10_1) static var STRING_REDO(default,never) : String;
	@:require(flash10_1) static var STRING_RESET(default,never) : String;
	@:require(flash10_1) static var STRING_RIGHTARROW(default,never) : String;
	@:require(flash10_1) static var STRING_SCROLLLOCK(default,never) : String;
	@:require(flash10_1) static var STRING_SELECT(default,never) : String;
	@:require(flash10_1) static var STRING_STOP(default,never) : String;
	@:require(flash10_1) static var STRING_SYSREQ(default,never) : String;
	@:require(flash10_1) static var STRING_SYSTEM(default,never) : String;
	@:require(flash10_1) static var STRING_UNDO(default,never) : String;
	@:require(flash10_1) static var STRING_UPARROW(default,never) : String;
	@:require(flash10_1) static var STRING_USER(default,never) : String;
	@:require(flash10_2) static var SUBTITLE(default,never) : UInt;
	@:require(flash10_1) static var T(default,never) : UInt;
	static var TAB(default,never) : UInt;
	@:require(flash10_1) static var U(default,never) : UInt;
	static var UP(default,never) : UInt;
	@:require(flash10_1) static var V(default,never) : UInt;
	@:require(flash10_2) static var VOD(default,never) : UInt;
	@:require(flash10_1) static var W(default,never) : UInt;
	@:require(flash10_1) static var X(default,never) : UInt;
	@:require(flash10_1) static var Y(default,never) : UInt;
	@:require(flash10_2) static var YELLOW(default,never) : UInt;
	@:require(flash10_1) static var Z(default,never) : UInt;
	static var capsLock(default,never) : Bool;
	@:require(flash10_1) static var hasVirtualKeyboard(default,never) : Bool;
	static var numLock(default,never) : Bool;
	@:require(flash10_1) static var physicalKeyboardType(default,never) : KeyboardType;
	static function isAccessible() : Bool;
}
