// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_templo_Constant
#include <templo/Constant.h>
#endif
namespace templo{

::templo::Constant Constant_obj::CInt(int c)
{
	return ::hx::CreateEnum<Constant_obj>(HX_("CInt",6c,10,81,2c),0,1)->_hx_init(0,c);
}

::templo::Constant Constant_obj::CString(::String c)
{
	return ::hx::CreateEnum<Constant_obj>(HX_("CString",74,b1,e2,27),1,1)->_hx_init(0,c);
}

::templo::Constant Constant_obj::CFloat(::String c)
{
	return ::hx::CreateEnum<Constant_obj>(HX_("CFloat",59,62,ad,5f),2,1)->_hx_init(0,c);
}

bool Constant_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("CInt",6c,10,81,2c)) { outValue = Constant_obj::CInt_dyn(); return true; }
	if (inName==HX_("CString",74,b1,e2,27)) { outValue = Constant_obj::CString_dyn(); return true; }
	if (inName==HX_("CFloat",59,62,ad,5f)) { outValue = Constant_obj::CFloat_dyn(); return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(Constant_obj)

bool Constant_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId == (int)0x00000001 || inClassId == ::hx::EnumBase_obj::_hx_ClassId || inClassId == _hx_ClassId;
}
int Constant_obj::__FindIndex(::String inName)
{
	if (inName==HX_("CInt",6c,10,81,2c)) return 0;
	if (inName==HX_("CString",74,b1,e2,27)) return 1;
	if (inName==HX_("CFloat",59,62,ad,5f)) return 2;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Constant_obj, CInt, return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Constant_obj, CString, return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Constant_obj, CFloat, return)

int Constant_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("CInt",6c,10,81,2c)) return 1;
	if (inName==HX_("CString",74,b1,e2,27)) return 1;
	if (inName==HX_("CFloat",59,62,ad,5f)) return 1;
	return super::__FindArgCount(inName);
}

::hx::Val Constant_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("CInt",6c,10,81,2c)) return CInt_dyn();
	if (inName==HX_("CString",74,b1,e2,27)) return CString_dyn();
	if (inName==HX_("CFloat",59,62,ad,5f)) return CFloat_dyn();
	return super::__Field(inName,inCallProp);
}

static ::String Constant_obj_sStaticFields[] = {
	HX_("CInt",6c,10,81,2c),
	HX_("CString",74,b1,e2,27),
	HX_("CFloat",59,62,ad,5f),
	::String(null())
};

::hx::Class Constant_obj::__mClass;

::Dynamic __Create_Constant_obj() { return new Constant_obj; }

void Constant_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("templo.Constant",3b,42,eb,eb), ::hx::TCanCast< Constant_obj >,Constant_obj_sStaticFields,0,
	&__Create_Constant_obj, &__Create,
	&super::__SGetClass(), &CreateConstant_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &Constant_obj::__GetStatic;
}

void Constant_obj::__boot()
{
}


} // end namespace templo
