// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_hxparse_Position
#include <hxparse/Position.h>
#endif
#ifndef INCLUDED_templo_Token
#include <templo/Token.h>
#endif
#ifndef INCLUDED_templo_TokenDef
#include <templo/TokenDef.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_f96a882f1b125e8a_38_new,"templo.Token","new",0xd819cfb4,"templo.Token.new","templo/Token.hx",38,0x446a0b3d)

namespace {

}

namespace templo{

void Token_obj::__construct( ::templo::TokenDef tok, ::hxparse::Position pos){
            	HX_STACKFRAME(&_hx_pos_f96a882f1b125e8a_38_new)
HXLINE(  39)		this->tok = tok;
HXLINE(  40)		this->pos = pos;
            	}

::Dynamic Token_obj::__CreateEmpty() { return new Token_obj; }

void* Token_obj::_hx_vtable = 0;

::Dynamic Token_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Token_obj > _hx_result = new Token_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool Token_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x75eedfa2;
}


::hx::ObjectPtr< Token_obj > Token_obj::__new( ::templo::TokenDef tok, ::hxparse::Position pos) {
	::hx::ObjectPtr< Token_obj > __this = new Token_obj();
	__this->__construct(tok,pos);
	return __this;
}

::hx::ObjectPtr< Token_obj > Token_obj::__alloc(::hx::Ctx *_hx_ctx, ::templo::TokenDef tok, ::hxparse::Position pos) {
	Token_obj* __this = (Token_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Token_obj), true, "templo.Token"));
	*(void **)__this = Token_obj::_hx_vtable;
	__this->__construct(tok,pos);
	return __this;
}

Token_obj::Token_obj()
{
}

void Token_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Token);
	HX_MARK_MEMBER_NAME(tok, "tok");
	HX_MARK_MEMBER_NAME(pos, "pos");
	HX_MARK_END_CLASS();
}

void Token_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(tok, "tok");
	HX_VISIT_MEMBER_NAME(pos, "pos");
}

::hx::Val Token_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"tok") ) { return ::hx::Val( tok ); }
		if (HX_FIELD_EQ(inName,"pos") ) { return ::hx::Val( pos ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Token_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"tok") ) { tok = inValue.Cast<  ::templo::TokenDef >(); return inValue; }
		if (HX_FIELD_EQ(inName,"pos") ) { pos = inValue.Cast<  ::hxparse::Position >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Token_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("tok",90,66,58,00));
	outFields->push(HX_("pos",94,5d,55,00));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Token_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /*  ::templo::TokenDef */ , (int)offsetof(Token_obj, tok), HX_("tok",90,66,58,00) },
	{ ::hx::fsObject /*  ::hxparse::Position */ , (int)offsetof(Token_obj, pos), HX_("pos",94,5d,55,00) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo* Token_obj_sStaticStorageInfo = 0;
#endif

static ::String Token_obj_sMemberFields[] = {
	HX_("tok",90,66,58,00),
	HX_("pos",94,5d,55,00),
	::String(null())
};

::hx::Class Token_obj::__mClass;

static ::String* Token_obj_sStaticFields = 0;

void Token_obj::__register()
{
	Token_obj _hx_dummy;
	Token_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("templo.Token",c2,25,ab,00);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Token_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Token_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Token_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Token_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Token_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace templo
