// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_haxe_macro_QuoteStatus
#define INCLUDED_haxe_macro_QuoteStatus

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(haxe,macro,QuoteStatus)
namespace haxe{
namespace macro{


class QuoteStatus_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef QuoteStatus_obj OBJ_;

	public:
		enum { _hx_ClassId = 0x4b39a9c8 };

		QuoteStatus_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("haxe.macro.QuoteStatus",c4,51,ee,21); }
		::String __ToString() const { return HX_("QuoteStatus.",00,d5,8c,3d) + _hx_tag; }
		bool _hx_isInstanceOf(int inClassId);

		static ::haxe::macro::QuoteStatus Unquoted;
		static inline ::haxe::macro::QuoteStatus Unquoted_dyn() { return Unquoted; }
		static ::haxe::macro::QuoteStatus Quoted;
		static inline ::haxe::macro::QuoteStatus Quoted_dyn() { return Quoted; }
};

} // end namespace haxe
} // end namespace macro

#endif /* INCLUDED_haxe_macro_QuoteStatus */ 
