// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_Xml
#include <Xml.h>
#endif
#ifndef INCLUDED__Xml_XmlType_Impl_
#include <_Xml/XmlType_Impl_.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_xml_Printer
#include <haxe/xml/Printer.h>
#endif
#ifndef INCLUDED_haxe_xml__Access_Access_Impl_
#include <haxe/xml/_Access/Access_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_91_get_x,"haxe.xml._Access.Access_Impl_","get_x",0x2622b76f,"haxe.xml._Access.Access_Impl_.get_x","haxe/xml/Access.hx",91,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_99_get_name,"haxe.xml._Access.Access_Impl_","get_name",0x14362fb4,"haxe.xml._Access.Access_Impl_.get_name","haxe/xml/Access.hx",99,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_134_get_node,"haxe.xml._Access.Access_Impl_","get_node",0x1440c76b,"haxe.xml._Access.Access_Impl_.get_node","haxe/xml/Access.hx",134,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_156_get_nodes,"haxe.xml._Access.Access_Impl_","get_nodes",0xa46db6a8,"haxe.xml._Access.Access_Impl_.get_nodes","haxe/xml/Access.hx",156,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_175_get_att,"haxe.xml._Access.Access_Impl_","get_att",0xfdc1a2d8,"haxe.xml._Access.Access_Impl_.get_att","haxe/xml/Access.hx",175,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_183_get_has,"haxe.xml._Access.Access_Impl_","get_has",0xfdc6e211,"haxe.xml._Access.Access_Impl_.get_has","haxe/xml/Access.hx",183,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_199_get_hasNode,"haxe.xml._Access.Access_Impl_","get_hasNode",0xe592f4b3,"haxe.xml._Access.Access_Impl_.get_hasNode","haxe/xml/Access.hx",199,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_207_get_elements,"haxe.xml._Access.Access_Impl_","get_elements",0x52b05c20,"haxe.xml._Access.Access_Impl_.get_elements","haxe/xml/Access.hx",207,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_209__hx_new,"haxe.xml._Access.Access_Impl_","_hx_new",0x31cc2430,"haxe.xml._Access.Access_Impl_._hx_new","haxe/xml/Access.hx",209,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_215_get_innerData,"haxe.xml._Access.Access_Impl_","get_innerData",0x69953cd7,"haxe.xml._Access.Access_Impl_.get_innerData","haxe/xml/Access.hx",215,0xfec6a719)
HX_LOCAL_STACK_FRAME(_hx_pos_ce095b8da2973312_237_get_innerHTML,"haxe.xml._Access.Access_Impl_","get_innerHTML",0x6c3017f8,"haxe.xml._Access.Access_Impl_.get_innerHTML","haxe/xml/Access.hx",237,0xfec6a719)

namespace {

struct __Access_Impl__objget_x final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__objget_x() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_x*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_x(this1);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__objget_x;

struct __Access_Impl__objget_name final : public ::hx::AutoCallable_obj< ::String ( ::Xml) > {
	__Access_Impl__objget_name() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_name*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::String HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_name(this1);
	}
};

::hx::Callable< ::String ( ::Xml) > _hx_alloc__Access_Impl__objget_name;

struct __Access_Impl__objget_node final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__objget_node() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_node*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_node(this1);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__objget_node;

struct __Access_Impl__objget_nodes final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__objget_nodes() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_nodes*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_nodes(this1);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__objget_nodes;

struct __Access_Impl__objget_att final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__objget_att() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_att*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_att(this1);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__objget_att;

struct __Access_Impl__objget_has final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__objget_has() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_has*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_has(this1);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__objget_has;

struct __Access_Impl__objget_hasNode final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__objget_hasNode() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_hasNode*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_hasNode(this1);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__objget_hasNode;

struct __Access_Impl__objget_elements final : public ::hx::AutoCallable_obj<  ::Dynamic ( ::Xml) > {
	__Access_Impl__objget_elements() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_elements*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Dynamic HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_elements(this1);
	}
};

::hx::Callable<  ::Dynamic ( ::Xml) > _hx_alloc__Access_Impl__objget_elements;

struct __Access_Impl__obj_hx_new final : public ::hx::AutoCallable_obj<  ::Xml ( ::Xml) > {
	__Access_Impl__obj_hx_new() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__obj_hx_new*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN( ::Xml x) override {
		return haxe::xml::_Access::Access_Impl__obj::_hx_new(x);
	}
};

::hx::Callable<  ::Xml ( ::Xml) > _hx_alloc__Access_Impl__obj_hx_new;

struct __Access_Impl__objget_innerData final : public ::hx::AutoCallable_obj< ::String ( ::Xml) > {
	__Access_Impl__objget_innerData() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_innerData*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::String HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_innerData(this1);
	}
};

::hx::Callable< ::String ( ::Xml) > _hx_alloc__Access_Impl__objget_innerData;

struct __Access_Impl__objget_innerHTML final : public ::hx::AutoCallable_obj< ::String ( ::Xml) > {
	__Access_Impl__objget_innerHTML() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Access_Impl__objget_innerHTML*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::String HX_LOCAL_RUN( ::Xml this1) override {
		return haxe::xml::_Access::Access_Impl__obj::get_innerHTML(this1);
	}
};

::hx::Callable< ::String ( ::Xml) > _hx_alloc__Access_Impl__objget_innerHTML;

}

namespace haxe{
namespace xml{
namespace _Access{

void Access_Impl__obj::__construct() { }

::Dynamic Access_Impl__obj::__CreateEmpty() { return new Access_Impl__obj; }

void* Access_Impl__obj::_hx_vtable = 0;

::Dynamic Access_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Access_Impl__obj > _hx_result = new Access_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Access_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x2733f11a;
}

 ::Xml Access_Impl__obj::get_x( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_91_get_x)
HXDLIN(  91)		return this1;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::get_x_dyn() { return _hx_alloc__Access_Impl__objget_x; }

::String Access_Impl__obj::get_name( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_99_get_name)
HXDLIN(  99)		if ((this1->nodeType == ::Xml_obj::Document)) {
HXDLIN(  99)			return HX_("Document",3b,ab,c4,74);
            		}
            		else {
HXDLIN(  99)			if ((this1->nodeType != ::Xml_obj::Element)) {
HXDLIN(  99)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(this1->nodeType))));
            			}
HXDLIN(  99)			return this1->nodeName;
            		}
HXDLIN(  99)		return null();
            	}


::hx::Callable< ::String ( ::Xml) > Access_Impl__obj::get_name_dyn() { return _hx_alloc__Access_Impl__objget_name; }

 ::Xml Access_Impl__obj::get_node( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_134_get_node)
HXDLIN( 134)		return this1;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::get_node_dyn() { return _hx_alloc__Access_Impl__objget_node; }

 ::Xml Access_Impl__obj::get_nodes( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_156_get_nodes)
HXDLIN( 156)		return this1;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::get_nodes_dyn() { return _hx_alloc__Access_Impl__objget_nodes; }

 ::Xml Access_Impl__obj::get_att( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_175_get_att)
HXDLIN( 175)		return this1;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::get_att_dyn() { return _hx_alloc__Access_Impl__objget_att; }

 ::Xml Access_Impl__obj::get_has( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_183_get_has)
HXDLIN( 183)		return this1;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::get_has_dyn() { return _hx_alloc__Access_Impl__objget_has; }

 ::Xml Access_Impl__obj::get_hasNode( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_199_get_hasNode)
HXDLIN( 199)		return this1;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::get_hasNode_dyn() { return _hx_alloc__Access_Impl__objget_hasNode; }

 ::Dynamic Access_Impl__obj::get_elements( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_207_get_elements)
HXDLIN( 207)		return this1->elements();
            	}


::hx::Callable<  ::Dynamic ( ::Xml) > Access_Impl__obj::get_elements_dyn() { return _hx_alloc__Access_Impl__objget_elements; }

 ::Xml Access_Impl__obj::_hx_new( ::Xml x){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_209__hx_new)
HXLINE( 210)		bool _hx_tmp;
HXDLIN( 210)		if ((x->nodeType != ::Xml_obj::Document)) {
HXLINE( 210)			_hx_tmp = (x->nodeType != ::Xml_obj::Element);
            		}
            		else {
HXLINE( 210)			_hx_tmp = false;
            		}
HXDLIN( 210)		if (_hx_tmp) {
HXLINE( 211)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Invalid nodeType ",3b,e0,cb,e1) + ::_Xml::XmlType_Impl__obj::toString(x->nodeType))));
            		}
HXLINE( 209)		return x;
            	}


::hx::Callable<  ::Xml ( ::Xml) > Access_Impl__obj::_hx_new_dyn() { return _hx_alloc__Access_Impl__obj_hx_new; }

::String Access_Impl__obj::get_innerData( ::Xml this1){
            	HX_STACKFRAME(&_hx_pos_ce095b8da2973312_215_get_innerData)
HXLINE( 216)		bool _hx_tmp;
HXDLIN( 216)		if ((this1->nodeType != ::Xml_obj::Document)) {
HXLINE( 216)			_hx_tmp = (this1->nodeType != ::Xml_obj::Element);
            		}
            		else {
HXLINE( 216)			_hx_tmp = false;
            		}
HXDLIN( 216)		if (_hx_tmp) {
HXLINE( 216)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element or Document but found ",a0,d6,ba,79) + ::_Xml::XmlType_Impl__obj::toString(this1->nodeType))));
            		}
HXDLIN( 216)		int it_current = 0;
HXDLIN( 216)		::Array< ::Dynamic> it_array = this1->children;
HXLINE( 217)		if ((it_current >= it_array->length)) {
HXLINE( 218)			::String _hx_tmp1;
HXDLIN( 218)			if ((this1->nodeType == ::Xml_obj::Document)) {
HXLINE( 218)				_hx_tmp1 = HX_("Document",3b,ab,c4,74);
            			}
            			else {
HXLINE( 218)				if ((this1->nodeType != ::Xml_obj::Element)) {
HXLINE( 218)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(this1->nodeType))));
            				}
HXDLIN( 218)				_hx_tmp1 = this1->nodeName;
            			}
HXDLIN( 218)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((_hx_tmp1 + HX_(" does not have data",0e,54,3b,f4))));
            		}
HXLINE( 219)		 ::Xml v = it_array->__get(it_current++).StaticCast<  ::Xml >();
HXLINE( 220)		if ((it_current < it_array->length)) {
HXLINE( 221)			 ::Xml n = it_array->__get(it_current++).StaticCast<  ::Xml >();
HXLINE( 223)			bool _hx_tmp2;
HXDLIN( 223)			bool _hx_tmp3;
HXDLIN( 223)			if ((v->nodeType == ::Xml_obj::PCData)) {
HXLINE( 223)				_hx_tmp3 = (n->nodeType == ::Xml_obj::CData);
            			}
            			else {
HXLINE( 223)				_hx_tmp3 = false;
            			}
HXDLIN( 223)			if (_hx_tmp3) {
HXLINE( 223)				bool _hx_tmp4;
HXDLIN( 223)				if ((v->nodeType != ::Xml_obj::Document)) {
HXLINE( 223)					_hx_tmp4 = (v->nodeType == ::Xml_obj::Element);
            				}
            				else {
HXLINE( 223)					_hx_tmp4 = true;
            				}
HXDLIN( 223)				if (_hx_tmp4) {
HXLINE( 223)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, unexpected ",be,79,d5,11) + ::_Xml::XmlType_Impl__obj::toString(v->nodeType))));
            				}
HXDLIN( 223)				_hx_tmp2 = (::StringTools_obj::trim(v->nodeValue) == HX_("",00,00,00,00));
            			}
            			else {
HXLINE( 223)				_hx_tmp2 = false;
            			}
HXDLIN( 223)			if (_hx_tmp2) {
HXLINE( 224)				if ((it_current >= it_array->length)) {
HXLINE( 225)					bool _hx_tmp5;
HXDLIN( 225)					if ((n->nodeType != ::Xml_obj::Document)) {
HXLINE( 225)						_hx_tmp5 = (n->nodeType == ::Xml_obj::Element);
            					}
            					else {
HXLINE( 225)						_hx_tmp5 = true;
            					}
HXDLIN( 225)					if (_hx_tmp5) {
HXLINE( 225)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, unexpected ",be,79,d5,11) + ::_Xml::XmlType_Impl__obj::toString(n->nodeType))));
            					}
HXDLIN( 225)					return n->nodeValue;
            				}
HXLINE( 226)				 ::Xml n2 = it_array->__get(it_current++).StaticCast<  ::Xml >();
HXLINE( 227)				bool _hx_tmp6;
HXDLIN( 227)				bool _hx_tmp7;
HXDLIN( 227)				if ((n2->nodeType == ::Xml_obj::PCData)) {
HXLINE( 227)					bool _hx_tmp8;
HXDLIN( 227)					if ((n2->nodeType != ::Xml_obj::Document)) {
HXLINE( 227)						_hx_tmp8 = (n2->nodeType == ::Xml_obj::Element);
            					}
            					else {
HXLINE( 227)						_hx_tmp8 = true;
            					}
HXDLIN( 227)					if (_hx_tmp8) {
HXLINE( 227)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, unexpected ",be,79,d5,11) + ::_Xml::XmlType_Impl__obj::toString(n2->nodeType))));
            					}
HXDLIN( 227)					_hx_tmp7 = (::StringTools_obj::trim(n2->nodeValue) == HX_("",00,00,00,00));
            				}
            				else {
HXLINE( 227)					_hx_tmp7 = false;
            				}
HXDLIN( 227)				if (_hx_tmp7) {
HXLINE( 227)					_hx_tmp6 = (it_current >= it_array->length);
            				}
            				else {
HXLINE( 227)					_hx_tmp6 = false;
            				}
HXDLIN( 227)				if (_hx_tmp6) {
HXLINE( 228)					bool _hx_tmp9;
HXDLIN( 228)					if ((n->nodeType != ::Xml_obj::Document)) {
HXLINE( 228)						_hx_tmp9 = (n->nodeType == ::Xml_obj::Element);
            					}
            					else {
HXLINE( 228)						_hx_tmp9 = true;
            					}
HXDLIN( 228)					if (_hx_tmp9) {
HXLINE( 228)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, unexpected ",be,79,d5,11) + ::_Xml::XmlType_Impl__obj::toString(n->nodeType))));
            					}
HXDLIN( 228)					return n->nodeValue;
            				}
            			}
HXLINE( 230)			::String _hx_tmp10;
HXDLIN( 230)			if ((this1->nodeType == ::Xml_obj::Document)) {
HXLINE( 230)				_hx_tmp10 = HX_("Document",3b,ab,c4,74);
            			}
            			else {
HXLINE( 230)				if ((this1->nodeType != ::Xml_obj::Element)) {
HXLINE( 230)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(this1->nodeType))));
            				}
HXDLIN( 230)				_hx_tmp10 = this1->nodeName;
            			}
HXDLIN( 230)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((_hx_tmp10 + HX_(" does not only have data",82,e2,30,ae))));
            		}
HXLINE( 232)		bool _hx_tmp11;
HXDLIN( 232)		if ((v->nodeType != ::Xml_obj::PCData)) {
HXLINE( 232)			_hx_tmp11 = (v->nodeType != ::Xml_obj::CData);
            		}
            		else {
HXLINE( 232)			_hx_tmp11 = false;
            		}
HXDLIN( 232)		if (_hx_tmp11) {
HXLINE( 233)			::String _hx_tmp12;
HXDLIN( 233)			if ((this1->nodeType == ::Xml_obj::Document)) {
HXLINE( 233)				_hx_tmp12 = HX_("Document",3b,ab,c4,74);
            			}
            			else {
HXLINE( 233)				if ((this1->nodeType != ::Xml_obj::Element)) {
HXLINE( 233)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(this1->nodeType))));
            				}
HXDLIN( 233)				_hx_tmp12 = this1->nodeName;
            			}
HXDLIN( 233)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((_hx_tmp12 + HX_(" does not have data",0e,54,3b,f4))));
            		}
HXLINE( 234)		bool _hx_tmp13;
HXDLIN( 234)		if ((v->nodeType != ::Xml_obj::Document)) {
HXLINE( 234)			_hx_tmp13 = (v->nodeType == ::Xml_obj::Element);
            		}
            		else {
HXLINE( 234)			_hx_tmp13 = true;
            		}
HXDLIN( 234)		if (_hx_tmp13) {
HXLINE( 234)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, unexpected ",be,79,d5,11) + ::_Xml::XmlType_Impl__obj::toString(v->nodeType))));
            		}
HXDLIN( 234)		return v->nodeValue;
            	}


::hx::Callable< ::String ( ::Xml) > Access_Impl__obj::get_innerData_dyn() { return _hx_alloc__Access_Impl__objget_innerData; }

::String Access_Impl__obj::get_innerHTML( ::Xml this1){
            	HX_GC_STACKFRAME(&_hx_pos_ce095b8da2973312_237_get_innerHTML)
HXLINE( 238)		 ::StringBuf s =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 239)		{
HXLINE( 239)			bool _hx_tmp;
HXDLIN( 239)			if ((this1->nodeType != ::Xml_obj::Document)) {
HXLINE( 239)				_hx_tmp = (this1->nodeType != ::Xml_obj::Element);
            			}
            			else {
HXLINE( 239)				_hx_tmp = false;
            			}
HXDLIN( 239)			if (_hx_tmp) {
HXLINE( 239)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element or Document but found ",a0,d6,ba,79) + ::_Xml::XmlType_Impl__obj::toString(this1->nodeType))));
            			}
HXDLIN( 239)			int _g_current = 0;
HXDLIN( 239)			::Array< ::Dynamic> _g_array = this1->children;
HXDLIN( 239)			while((_g_current < _g_array->length)){
HXLINE( 239)				 ::Xml x = _g_array->__get(_g_current++).StaticCast<  ::Xml >();
HXLINE( 240)				{
HXLINE( 240)					::String x1 = ::haxe::xml::Printer_obj::print(x,null());
HXDLIN( 240)					if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 240)						s->flush();
            					}
HXDLIN( 240)					if (::hx::IsNull( s->b )) {
HXLINE( 240)						s->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x1));
            					}
            					else {
HXLINE( 240)						::Array< ::String > s1 = s->b;
HXDLIN( 240)						s1->push(::Std_obj::string(x1));
            					}
            				}
            			}
            		}
HXLINE( 241)		return s->toString();
            	}


::hx::Callable< ::String ( ::Xml) > Access_Impl__obj::get_innerHTML_dyn() { return _hx_alloc__Access_Impl__objget_innerHTML; }


Access_Impl__obj::Access_Impl__obj()
{
}

bool Access_Impl__obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"get_x") ) { outValue = get_x_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"get_att") ) { outValue = get_att_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_has") ) { outValue = get_has_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"_hx_new") ) { outValue = _hx_new_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"get_name") ) { outValue = get_name_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_node") ) { outValue = get_node_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"get_nodes") ) { outValue = get_nodes_dyn(); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"get_hasNode") ) { outValue = get_hasNode_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"get_elements") ) { outValue = get_elements_dyn(); return true; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"get_innerData") ) { outValue = get_innerData_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_innerHTML") ) { outValue = get_innerHTML_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo* Access_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo* Access_Impl__obj_sStaticStorageInfo = 0;
#endif

static ::String* Access_Impl__obj_sMemberFields = 0;

::hx::Class Access_Impl__obj::__mClass;

static ::String Access_Impl__obj_sStaticFields[] = {
	HX_("get_x",4f,a5,60,91),
	HX_("get_name",d4,2d,ba,c8),
	HX_("get_node",8b,c5,c4,c8),
	HX_("get_nodes",88,14,68,e3),
	HX_("get_att",b8,c8,be,26),
	HX_("get_has",f1,07,c4,26),
	HX_("get_hasNode",93,8a,48,9e),
	HX_("get_elements",40,ea,dd,38),
	HX_("_hx_new",10,4a,c9,5a),
	HX_("get_innerData",b7,0a,44,eb),
	HX_("get_innerHTML",d8,e5,de,ed),
	::String(null())
};

void Access_Impl__obj::__register()
{
	Access_Impl__obj _hx_dummy;
	Access_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.xml._Access.Access_Impl_",8e,1a,60,a9);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Access_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Access_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Access_Impl__obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Access_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Access_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Access_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Access_Impl__obj::__boot()
{
_hx_alloc__Access_Impl__objget_x = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_x();

_hx_alloc__Access_Impl__objget_name = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_name();

_hx_alloc__Access_Impl__objget_node = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_node();

_hx_alloc__Access_Impl__objget_nodes = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_nodes();

_hx_alloc__Access_Impl__objget_att = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_att();

_hx_alloc__Access_Impl__objget_has = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_has();

_hx_alloc__Access_Impl__objget_hasNode = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_hasNode();

_hx_alloc__Access_Impl__objget_elements = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_elements();

_hx_alloc__Access_Impl__obj_hx_new = new (::hx::NewObjectType::NewObjConst) __Access_Impl__obj_hx_new();

_hx_alloc__Access_Impl__objget_innerData = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_innerData();

_hx_alloc__Access_Impl__objget_innerHTML = new (::hx::NewObjectType::NewObjConst) __Access_Impl__objget_innerHTML();

}

} // end namespace haxe
} // end namespace xml
} // end namespace _Access
