package cs.system;

@:native("System.Environment.SpecialFolder")
extern enum abstract Environment_SpecialFolder(Int) {
	var AdminTools = 48;
	var ApplicationData = 26;
	var CDBurning = 59;
	var CommonAdminTools = 47;
	var CommonApplicationData = 35;
	var CommonDesktopDirectory = 25;
	var CommonDocuments = 46;
	var CommonMusic = 53;
	var CommonOemLinks = 58;
	var CommonPictures = 54;
	var CommonProgramFiles = 43;
	var CommonProgramFilesX86 = 44;
	var CommonPrograms = 23;
	var CommonStartMenu = 22;
	var CommonStartup = 24;
	var CommonTemplates = 45;
	var CommonVideos = 55;
	var Cookies = 33;
	var Desktop = 0;
	var DesktopDirectory = 16;
	var Favorites = 6;
	var Fonts = 20;
	var History = 34;
	var InternetCache = 32;
	var LocalApplicationData = 28;
	var LocalizedResources = 57;
	var MyComputer = 17;
	var MyDocuments = 5;
	var MyMusic = 13;
	var MyPictures = 39;
	var MyVideos = 14;
	var NetworkShortcuts = 19;
	var Personal = 5;
	var PrinterShortcuts = 27;
	var ProgramFiles = 38;
	var ProgramFilesX86 = 42;
	var Programs = 2;
	var Recent = 8;
	var Resources = 56;
	var SendTo = 9;
	var StartMenu = 11;
	var Startup = 7;
	var System = 37;
	var SystemX86 = 41;
	var Templates = 21;
	var UserProfile = 40;
	var Windows = 36;
}
