// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_List
#include <haxe/ds/List.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds__List_ListNode
#include <haxe/ds/_List/ListNode.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_hxparse_LexEngine
#include <hxparse/LexEngine.h>
#endif
#ifndef INCLUDED_hxparse_State
#include <hxparse/State.h>
#endif
#ifndef INCLUDED_hxparse__LexEngine_CharRange
#include <hxparse/_LexEngine/CharRange.h>
#endif
#ifndef INCLUDED_hxparse__LexEngine_Node
#include <hxparse/_LexEngine/Node.h>
#endif
#ifndef INCLUDED_hxparse__LexEngine_Pattern
#include <hxparse/_LexEngine/Pattern.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_c89ea2fff599559e_30_new,"hxparse.LexEngine","new",0xc0d0ebc8,"hxparse.LexEngine.new","hxparse/LexEngine.hx",30,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_52_firstState,"hxparse.LexEngine","firstState",0x49946159,"hxparse.LexEngine.firstState","hxparse/LexEngine.hx",52,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_82_makeState,"hxparse.LexEngine","makeState",0xbc1f86ab,"hxparse.LexEngine.makeState","hxparse/LexEngine.hx",82,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_55_makeState,"hxparse.LexEngine","makeState",0xbc1f86ab,"hxparse.LexEngine.makeState","hxparse/LexEngine.hx",55,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_101_getTransitions,"hxparse.LexEngine","getTransitions",0x7581f5e0,"hxparse.LexEngine.getTransitions","hxparse/LexEngine.hx",101,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_140_getTransitions,"hxparse.LexEngine","getTransitions",0x7581f5e0,"hxparse.LexEngine.getTransitions","hxparse/LexEngine.hx",140,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_94_getTransitions,"hxparse.LexEngine","getTransitions",0x7581f5e0,"hxparse.LexEngine.getTransitions","hxparse/LexEngine.hx",94,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_158_addNode,"hxparse.LexEngine","addNode",0x7b9a3c2b,"hxparse.LexEngine.addNode","hxparse/LexEngine.hx",158,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_166_addNodes,"hxparse.LexEngine","addNodes",0xab5a69e8,"hxparse.LexEngine.addNodes","hxparse/LexEngine.hx",166,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_173_node,"hxparse.LexEngine","node",0xf604e99a,"hxparse.LexEngine.node","hxparse/LexEngine.hx",173,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_177_initNode,"hxparse.LexEngine","initNode",0xdfffc4ca,"hxparse.LexEngine.initNode","hxparse/LexEngine.hx",177,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_215_single,"hxparse.LexEngine","single",0xc2455c20,"hxparse.LexEngine.single","hxparse/LexEngine.hx",215,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_239_parse,"hxparse.LexEngine","parse",0x6bde559b,"hxparse.LexEngine.parse","hxparse/LexEngine.hx",239,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_246_next,"hxparse.LexEngine","next",0xf5fd648b,"hxparse.LexEngine.next","hxparse/LexEngine.hx",246,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_250_plus,"hxparse.LexEngine","plus",0xf7551ef2,"hxparse.LexEngine.plus","hxparse/LexEngine.hx",250,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_257_star,"hxparse.LexEngine","star",0xf956c36a,"hxparse.LexEngine.star","hxparse/LexEngine.hx",257,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_264_opt,"hxparse.LexEngine","opt",0xc0d1b79b,"hxparse.LexEngine.opt","hxparse/LexEngine.hx",264,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_271_cinter,"hxparse.LexEngine","cinter",0x5c996d71,"hxparse.LexEngine.cinter","hxparse/LexEngine.hx",271,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_275_cdiff,"hxparse.LexEngine","cdiff",0xf19d8f50,"hxparse.LexEngine.cdiff","hxparse/LexEngine.hx",275,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_278_ccomplement,"hxparse.LexEngine","ccomplement",0x015a8071,"hxparse.LexEngine.ccomplement","hxparse/LexEngine.hx",278,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_291_cunion,"hxparse.LexEngine","cunion",0x45601364,"hxparse.LexEngine.cunion","hxparse/LexEngine.hx",291,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_334_parseInner,"hxparse.LexEngine","parseInner",0x6fa819fb,"hxparse.LexEngine.parseInner","hxparse/LexEngine.hx",334,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_333_parseInner,"hxparse.LexEngine","parseInner",0x6fa819fb,"hxparse.LexEngine.parseInner","hxparse/LexEngine.hx",333,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_210_boot,"hxparse.LexEngine","boot",0xee1663ca,"hxparse.LexEngine.boot","hxparse/LexEngine.hx",210,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_211_boot,"hxparse.LexEngine","boot",0xee1663ca,"hxparse.LexEngine.boot","hxparse/LexEngine.hx",211,0x1c242229)
HX_LOCAL_STACK_FRAME(_hx_pos_c89ea2fff599559e_212_boot,"hxparse.LexEngine","boot",0xee1663ca,"hxparse.LexEngine.boot","hxparse/LexEngine.hx",212,0x1c242229)

namespace {

struct __LexEngine_objfirstState final : public ::hx::AutoCallable_obj<  ::hxparse::State () > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objfirstState(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objfirstState*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	 ::hxparse::State HX_LOCAL_RUN() override {
		return __this->firstState();
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objmakeState final : public ::hx::AutoCallable_obj<  ::hxparse::State (::Array< ::Dynamic>) > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objmakeState(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objmakeState*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	 ::hxparse::State HX_LOCAL_RUN(::Array< ::Dynamic> nodes) override {
		return __this->makeState(nodes);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objgetTransitions final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (::Array< ::Dynamic>) > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objgetTransitions(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objgetTransitions*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(::Array< ::Dynamic> nodes) override {
		return __this->getTransitions(nodes);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objaddNode final : public ::hx::AutoCallable_obj< void (::Array< ::Dynamic>, ::hxparse::_LexEngine::Node) > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objaddNode(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objaddNode*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	void HX_LOCAL_RUN(::Array< ::Dynamic> nodes, ::hxparse::_LexEngine::Node n) override {
		__this->addNode(nodes, n);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objaddNodes final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objaddNodes(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objaddNodes*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(::Array< ::Dynamic> nodes,::Array< ::Dynamic> add) override {
		return __this->addNodes(nodes, add);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objnode final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Node (int) > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objnode(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objnode*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	 ::hxparse::_LexEngine::Node HX_LOCAL_RUN(int pid) override {
		return __this->node(pid);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objinitNode final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Node ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Node,int) > {
	::hx::ObjectPtr<hxparse::LexEngine_obj> __this;
	__LexEngine_objinitNode(::hx::ObjectPtr<hxparse::LexEngine_obj> obj = null()) : __this(obj) {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objinitNode*>(inRhs);
		if (!casted) { return -1; }
		if (__this != casted->__this) return 1;
		return 0;
	}
	 ::hxparse::_LexEngine::Node HX_LOCAL_RUN( ::hxparse::_LexEngine::Pattern p, ::hxparse::_LexEngine::Node finalId,int pid) override {
		return __this->initNode(p, finalId, pid);
	}
	void __Mark(hx::MarkContext* __inCtx) override { HX_MARK_MEMBER(__this); }
#ifdef HXCPP_VISIT_ALLOCS
	void __Visit(hx::VisitContext* __inCtx) override { HX_VISIT_MEMBER(__this); }
#endif
};

struct __LexEngine_objsingle final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (int) > {
	__LexEngine_objsingle() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objsingle*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(int c) override {
		return hxparse::LexEngine_obj::single(c);
	}
};

::hx::Callable< ::Array< ::Dynamic> (int) > _hx_alloc__LexEngine_objsingle;

struct __LexEngine_objparse final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Pattern (::String) > {
	__LexEngine_objparse() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objparse*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::hxparse::_LexEngine::Pattern HX_LOCAL_RUN(::String pattern) override {
		return hxparse::LexEngine_obj::parse(pattern);
	}
};

::hx::Callable<  ::hxparse::_LexEngine::Pattern (::String) > _hx_alloc__LexEngine_objparse;

struct __LexEngine_objnext final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Pattern) > {
	__LexEngine_objnext() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objnext*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::hxparse::_LexEngine::Pattern HX_LOCAL_RUN( ::hxparse::_LexEngine::Pattern a, ::hxparse::_LexEngine::Pattern b) override {
		return hxparse::LexEngine_obj::next(a, b);
	}
};

::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Pattern) > _hx_alloc__LexEngine_objnext;

struct __LexEngine_objplus final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > {
	__LexEngine_objplus() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objplus*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::hxparse::_LexEngine::Pattern HX_LOCAL_RUN( ::hxparse::_LexEngine::Pattern r) override {
		return hxparse::LexEngine_obj::plus(r);
	}
};

::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > _hx_alloc__LexEngine_objplus;

struct __LexEngine_objstar final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > {
	__LexEngine_objstar() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objstar*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::hxparse::_LexEngine::Pattern HX_LOCAL_RUN( ::hxparse::_LexEngine::Pattern r) override {
		return hxparse::LexEngine_obj::star(r);
	}
};

::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > _hx_alloc__LexEngine_objstar;

struct __LexEngine_objopt final : public ::hx::AutoCallable_obj<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > {
	__LexEngine_objopt() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objopt*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::hxparse::_LexEngine::Pattern HX_LOCAL_RUN( ::hxparse::_LexEngine::Pattern r) override {
		return hxparse::LexEngine_obj::opt(r);
	}
};

::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > _hx_alloc__LexEngine_objopt;

struct __LexEngine_objcinter final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > {
	__LexEngine_objcinter() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objcinter*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(::Array< ::Dynamic> c1,::Array< ::Dynamic> c2) override {
		return hxparse::LexEngine_obj::cinter(c1, c2);
	}
};

::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > _hx_alloc__LexEngine_objcinter;

struct __LexEngine_objcdiff final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > {
	__LexEngine_objcdiff() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objcdiff*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(::Array< ::Dynamic> c1,::Array< ::Dynamic> c2) override {
		return hxparse::LexEngine_obj::cdiff(c1, c2);
	}
};

::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > _hx_alloc__LexEngine_objcdiff;

struct __LexEngine_objccomplement final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (::Array< ::Dynamic>) > {
	__LexEngine_objccomplement() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objccomplement*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(::Array< ::Dynamic> c) override {
		return hxparse::LexEngine_obj::ccomplement(c);
	}
};

::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>) > _hx_alloc__LexEngine_objccomplement;

struct __LexEngine_objcunion final : public ::hx::AutoCallable_obj< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > {
	__LexEngine_objcunion() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objcunion*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	::Array< ::Dynamic> HX_LOCAL_RUN(::Array< ::Dynamic> ca,::Array< ::Dynamic> cb) override {
		return hxparse::LexEngine_obj::cunion(ca, cb);
	}
};

::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > _hx_alloc__LexEngine_objcunion;

struct __LexEngine_objparseInner final : public ::hx::AutoCallable_obj<  ::Dynamic ( ::haxe::io::Bytes, ::Dynamic, ::Dynamic) > {
	__LexEngine_objparseInner() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __LexEngine_objparseInner*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Dynamic HX_LOCAL_RUN( ::haxe::io::Bytes pattern, ::Dynamic i, ::Dynamic pDepth) override {
		return hxparse::LexEngine_obj::parseInner(pattern, i, pDepth);
	}
};

::hx::Callable<  ::Dynamic ( ::haxe::io::Bytes, ::Dynamic, ::Dynamic) > _hx_alloc__LexEngine_objparseInner;

}

namespace hxparse{

void LexEngine_obj::__construct(::Array< ::Dynamic> patterns){
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_30_new)
HXLINE(  31)		this->nodes = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  32)		this->finals = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  33)		this->states = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  34)		this->hstates =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  35)		this->uid = 0;
HXLINE(  36)		int pid = 0;
HXLINE(  37)		{
HXLINE(  37)			int _g = 0;
HXDLIN(  37)			while((_g < patterns->length)){
HXLINE(  37)				 ::hxparse::_LexEngine::Pattern p = patterns->__get(_g).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN(  37)				++_g;
HXLINE(  38)				int id = pid++;
HXLINE(  39)				 ::hxparse::_LexEngine::Node f =  ::hxparse::_LexEngine::Node_obj::__alloc( HX_CTX ,this->uid++,id);
HXLINE(  40)				 ::hxparse::_LexEngine::Node n = this->initNode(p,f,id);
HXLINE(  41)				this->nodes->push(n);
HXLINE(  42)				this->finals->push(f);
            			}
            		}
HXLINE(  44)		this->makeState(this->addNodes(::Array_obj< ::Dynamic>::__new(0),this->nodes));
            	}

::Dynamic LexEngine_obj::__CreateEmpty() { return new LexEngine_obj; }

void* LexEngine_obj::_hx_vtable = 0;

::Dynamic LexEngine_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< LexEngine_obj > _hx_result = new LexEngine_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool LexEngine_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x653cb29e;
}

 ::hxparse::State LexEngine_obj::firstState(){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_52_firstState)
HXDLIN(  52)		return this->states->__get(0).StaticCast<  ::hxparse::State >();
            	}


::hx::Callable<  ::hxparse::State () > LexEngine_obj::firstState_dyn() { return new __LexEngine_objfirstState(this); }

 ::hxparse::State LexEngine_obj::makeState(::Array< ::Dynamic> nodes){
HX_BEGIN_LOCAL_FUNC_S3(::hx::AutoCallable_obj< void() >, _hx_Closure_0,  ::hxparse::LexEngine,_gthis, ::hxparse::State,s,::Array< ::Dynamic>,nodes)
            		void HX_LOCAL_RUN(  ){
            			HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_82_makeState)
HXLINE(  82)			int _g = 0;
HXDLIN(  82)			::Array< ::Dynamic> _g1 = _gthis->finals;
HXDLIN(  82)			while((_g < _g1->length)){
HXLINE(  82)				 ::hxparse::_LexEngine::Node f = _g1->__get(_g).StaticCast<  ::hxparse::_LexEngine::Node >();
HXDLIN(  82)				++_g;
HXLINE(  83)				{
HXLINE(  83)					int _g2 = 0;
HXDLIN(  83)					while((_g2 < nodes->length)){
HXLINE(  83)						 ::hxparse::_LexEngine::Node n = nodes->__get(_g2).StaticCast<  ::hxparse::_LexEngine::Node >();
HXDLIN(  83)						++_g2;
HXLINE(  84)						if (::hx::IsInstanceEq( n,f )) {
HXLINE(  85)							s->finalId = n->pid;
HXLINE(  86)							return;
            						}
            					}
            				}
            			}
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC0((void))

            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_55_makeState)
HXDLIN(  55)		 ::hxparse::LexEngine _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE(  56)		 ::StringBuf buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE(  57)		{
HXLINE(  57)			int _g = 0;
HXDLIN(  57)			while((_g < nodes->length)){
HXLINE(  57)				 ::hxparse::_LexEngine::Node n = nodes->__get(_g).StaticCast<  ::hxparse::_LexEngine::Node >();
HXDLIN(  57)				++_g;
HXLINE(  58)				{
HXLINE(  58)					int x = n->id;
HXDLIN(  58)					if (::hx::IsNotNull( buf->charBuf )) {
HXLINE(  58)						buf->flush();
            					}
HXDLIN(  58)					if (::hx::IsNull( buf->b )) {
HXLINE(  58)						buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            					}
            					else {
HXLINE(  58)						::Array< ::String > buf1 = buf->b;
HXDLIN(  58)						buf1->push(::Std_obj::string(x));
            					}
            				}
HXLINE(  59)				{
HXLINE(  59)					if (::hx::IsNull( buf->charBuf )) {
HXLINE(  59)						buf->charBuf = ::Array_obj< char >::__new();
            					}
HXDLIN(  59)					buf->charBuf->push(45);
            				}
            			}
            		}
HXLINE(  61)		::String key = buf->toString();
HXLINE(  62)		 ::hxparse::State s = ( ( ::hxparse::State)(this->hstates->get(key)) );
HXLINE(  63)		if (::hx::IsNotNull( s )) {
HXLINE(  64)			return s;
            		}
HXLINE(  66)		s =  ::hxparse::State_obj::__alloc( HX_CTX );
HXLINE(  67)		this->states->push(s);
HXLINE(  68)		this->hstates->set(key,s);
HXLINE(  70)		::Array< ::Dynamic> trans = this->getTransitions(nodes);
HXLINE(  72)		{
HXLINE(  72)			int _g1 = 0;
HXDLIN(  72)			while((_g1 < trans->length)){
HXLINE(  72)				 ::Dynamic t = trans->__get(_g1);
HXDLIN(  72)				++_g1;
HXLINE(  73)				 ::hxparse::State target = this->makeState(( (::Array< ::Dynamic>)(t->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) ));
HXLINE(  74)				{
HXLINE(  74)					int _g2 = 0;
HXDLIN(  74)					::Array< ::Dynamic> _g3 = ( (::Array< ::Dynamic>)(t->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) );
HXDLIN(  74)					while((_g2 < _g3->length)){
HXLINE(  74)						 ::hxparse::_LexEngine::CharRange chr = _g3->__get(_g2).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXDLIN(  74)						++_g2;
HXLINE(  75)						{
HXLINE(  75)							int _g4 = chr->min;
HXDLIN(  75)							int _g5 = (chr->max + 1);
HXDLIN(  75)							while((_g4 < _g5)){
HXLINE(  75)								int i = _g4++;
HXLINE(  76)								s->trans->__unsafe_set(i,target);
            							}
            						}
            					}
            				}
            			}
            		}
HXLINE(  81)		::hx::Callable< void () > setFinal = ::hx::Callable< void() >(new _hx_Closure_0(_gthis,s,nodes));
HXLINE(  89)		if ((s->finalId == -1)) {
HXLINE(  90)			setFinal();
            		}
HXLINE(  91)		return s;
            	}


::hx::Callable<  ::hxparse::State (::Array< ::Dynamic>) > LexEngine_obj::makeState_dyn() { return new __LexEngine_objmakeState(this); }

::Array< ::Dynamic> LexEngine_obj::getTransitions(::Array< ::Dynamic> nodes){
HX_BEGIN_LOCAL_FUNC_S0(::hx::AutoCallable_obj< int( ::Dynamic t1, ::Dynamic t2) >, _hx_Closure_0)
            		int HX_LOCAL_RUN(  ::Dynamic t1, ::Dynamic t2 ){
            			HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_101_getTransitions)
HXLINE( 101)			return (( ( ::hxparse::_LexEngine::Node)(t1->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) )->id - ( ( ::hxparse::_LexEngine::Node)(t2->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) )->id);
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC2(return)

HX_BEGIN_LOCAL_FUNC_S0(::hx::AutoCallable_obj< int( ::Dynamic s1, ::Dynamic s2) >, _hx_Closure_1)
            		int HX_LOCAL_RUN(  ::Dynamic s1, ::Dynamic s2 ){
            			HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_140_getTransitions)
HXLINE( 141)			int a = ( (::Array< ::Dynamic>)(s1->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) )->length;
HXLINE( 142)			int b = ( (::Array< ::Dynamic>)(s2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) )->length;
HXLINE( 143)			{
HXLINE( 143)				int _g = 0;
HXDLIN( 143)				int _g1;
HXDLIN( 143)				if ((a < b)) {
HXLINE( 143)					_g1 = a;
            				}
            				else {
HXLINE( 143)					_g1 = b;
            				}
HXDLIN( 143)				while((_g < _g1)){
HXLINE( 143)					int i = _g++;
HXLINE( 144)					 ::hxparse::_LexEngine::CharRange a1 = Dynamic(  ::Dynamic(s1->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic))->__GetItem(i)).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXLINE( 145)					 ::hxparse::_LexEngine::CharRange b1 = Dynamic(  ::Dynamic(s2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic))->__GetItem(i)).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXLINE( 146)					if ((a1->min != b1->min)) {
HXLINE( 147)						return (b1->min - a1->min);
            					}
HXLINE( 148)					if ((a1->max != b1->max)) {
HXLINE( 149)						return (b1->max - a1->max);
            					}
            				}
            			}
HXLINE( 151)			if ((a < b)) {
HXLINE( 152)				return (b - a);
            			}
HXLINE( 153)			return 0;
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_1*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_1) };
            		}
            		HX_END_LOCAL_FUNC2(return)

            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_94_getTransitions)
HXLINE(  95)		::Array< ::Dynamic> tl = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  96)		{
HXLINE(  96)			int _g = 0;
HXDLIN(  96)			while((_g < nodes->length)){
HXLINE(  96)				 ::hxparse::_LexEngine::Node n = nodes->__get(_g).StaticCast<  ::hxparse::_LexEngine::Node >();
HXDLIN(  96)				++_g;
HXLINE(  97)				{
HXLINE(  97)					int _g1 = 0;
HXDLIN(  97)					::Array< ::Dynamic> _g2 = n->trans;
HXDLIN(  97)					while((_g1 < _g2->length)){
HXLINE(  97)						 ::Dynamic t = _g2->__get(_g1);
HXDLIN(  97)						++_g1;
HXLINE(  98)						tl->push(t);
            					}
            				}
            			}
            		}
HXLINE( 101)		tl->sort(::hx::Callable< int( ::Dynamic t1, ::Dynamic t2) >(new _hx_Closure_0()));
HXLINE( 102)		 ::Dynamic t0 = tl->__get(0);
HXLINE( 103)		{
HXLINE( 103)			int _g3 = 1;
HXDLIN( 103)			int _g4 = tl->length;
HXDLIN( 103)			while((_g3 < _g4)){
HXLINE( 103)				int i = _g3++;
HXLINE( 104)				 ::Dynamic t1 = tl->__get(i);
HXLINE( 105)				if (::hx::IsInstanceEq( ( ( ::hxparse::_LexEngine::Node)(t0->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) ),( ( ::hxparse::_LexEngine::Node)(t1->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) ) )) {
HXLINE( 106)					tl[(i - 1)] = null();
HXLINE( 107)					::Array< ::Dynamic> t11 = ::hxparse::LexEngine_obj::cunion(( (::Array< ::Dynamic>)(t0->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ),( (::Array< ::Dynamic>)(t1->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ));
HXDLIN( 107)					t1 =  ::Dynamic(::hx::Anon_obj::Create(2)
            						->setFixed(0,HX_("n",6e,00,00,00),( ( ::hxparse::_LexEngine::Node)(t1->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) ))
            						->setFixed(1,HX_("chars",dd,9c,b3,45),t11));
HXLINE( 108)					tl[i] = t1;
            				}
HXLINE( 110)				t0 = t1;
            			}
            		}
HXLINE( 112)		while(tl->remove(null())){
            		}
HXLINE( 116)		::Array< ::Dynamic> allChars = ::hxparse::LexEngine_obj::EMPTY;
HXLINE( 117)		 ::haxe::ds::List allStates =  ::haxe::ds::List_obj::__alloc( HX_CTX );
HXLINE( 118)		{
HXLINE( 118)			int _g5 = 0;
HXDLIN( 118)			while((_g5 < tl->length)){
HXLINE( 118)				 ::Dynamic t2 = tl->__get(_g5);
HXDLIN( 118)				++_g5;
HXLINE( 119)				 ::haxe::ds::List states =  ::haxe::ds::List_obj::__alloc( HX_CTX );
HXLINE( 120)				::Array< ::Dynamic> _hx_tmp = ::hxparse::LexEngine_obj::cdiff(( (::Array< ::Dynamic>)(t2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ),allChars);
HXDLIN( 120)				states->push( ::Dynamic(::hx::Anon_obj::Create(2)
            					->setFixed(0,HX_("n",6e,00,00,00),::Array_obj< ::Dynamic>::__new(1)->init(0,( ( ::hxparse::_LexEngine::Node)(t2->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) )))
            					->setFixed(1,HX_("chars",dd,9c,b3,45),_hx_tmp)));
HXLINE( 121)				{
HXLINE( 121)					 ::haxe::ds::_List::ListNode _g_head = allStates->h;
HXDLIN( 121)					while(::hx::IsNotNull( _g_head )){
HXLINE( 121)						 ::Dynamic val = _g_head->item;
HXDLIN( 121)						_g_head = _g_head->next;
HXDLIN( 121)						 ::Dynamic s = val;
HXLINE( 122)						::Array< ::Dynamic> nodes1 = ( (::Array< ::Dynamic>)(s->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) )->copy();
HXLINE( 123)						nodes1->push( ::Dynamic(t2->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)));
HXLINE( 124)						states->push( ::Dynamic(::hx::Anon_obj::Create(2)
            							->setFixed(0,HX_("n",6e,00,00,00),nodes1)
            							->setFixed(1,HX_("chars",dd,9c,b3,45),::hxparse::LexEngine_obj::cinter(( (::Array< ::Dynamic>)(s->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ),( (::Array< ::Dynamic>)(t2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) )))));
HXLINE( 125)						::Array< ::Dynamic> _hx_tmp1 = ::hxparse::LexEngine_obj::cdiff(( (::Array< ::Dynamic>)(s->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ),( (::Array< ::Dynamic>)(t2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ));
HXDLIN( 125)						states->push( ::Dynamic(::hx::Anon_obj::Create(2)
            							->setFixed(0,HX_("n",6e,00,00,00),( (::Array< ::Dynamic>)(s->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) ))
            							->setFixed(1,HX_("chars",dd,9c,b3,45),_hx_tmp1)));
            					}
            				}
HXLINE( 127)				{
HXLINE( 127)					 ::haxe::ds::_List::ListNode _g_head1 = states->h;
HXDLIN( 127)					while(::hx::IsNotNull( _g_head1 )){
HXLINE( 127)						 ::Dynamic val1 = _g_head1->item;
HXDLIN( 127)						_g_head1 = _g_head1->next;
HXDLIN( 127)						 ::Dynamic s1 = val1;
HXLINE( 128)						if ((( (::Array< ::Dynamic>)(s1->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) )->length == 0)) {
HXLINE( 129)							states->remove(s1);
            						}
            					}
            				}
HXLINE( 130)				allChars = ::hxparse::LexEngine_obj::cunion(allChars,( (::Array< ::Dynamic>)(t2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) ));
HXLINE( 131)				allStates = states;
            			}
            		}
HXLINE( 135)		::Array< ::Dynamic> states1 = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 136)		{
HXLINE( 136)			 ::haxe::ds::_List::ListNode _g_head2 = allStates->h;
HXDLIN( 136)			while(::hx::IsNotNull( _g_head2 )){
HXLINE( 136)				 ::Dynamic val2 = _g_head2->item;
HXDLIN( 136)				_g_head2 = _g_head2->next;
HXDLIN( 136)				 ::Dynamic s2 = val2;
HXLINE( 137)				::Array< ::Dynamic> s3 = ( (::Array< ::Dynamic>)(s2->__Field(HX_("chars",dd,9c,b3,45),::hx::paccDynamic)) );
HXDLIN( 137)				states1->push( ::Dynamic(::hx::Anon_obj::Create(2)
            					->setFixed(0,HX_("n",6e,00,00,00),this->addNodes(::Array_obj< ::Dynamic>::__new(0),( (::Array< ::Dynamic>)(s2->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) )))
            					->setFixed(1,HX_("chars",dd,9c,b3,45),s3)));
            			}
            		}
HXLINE( 140)		states1->sort(::hx::Callable< int( ::Dynamic s1, ::Dynamic s2) >(new _hx_Closure_1()));
HXLINE( 155)		return states1;
            	}


::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>) > LexEngine_obj::getTransitions_dyn() { return new __LexEngine_objgetTransitions(this); }

void LexEngine_obj::addNode(::Array< ::Dynamic> nodes, ::hxparse::_LexEngine::Node n){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_158_addNode)
HXLINE( 159)		{
HXLINE( 159)			int _g = 0;
HXDLIN( 159)			while((_g < nodes->length)){
HXLINE( 159)				 ::hxparse::_LexEngine::Node n2 = nodes->__get(_g).StaticCast<  ::hxparse::_LexEngine::Node >();
HXDLIN( 159)				++_g;
HXLINE( 160)				if (::hx::IsInstanceEq( n,n2 )) {
HXLINE( 161)					return;
            				}
            			}
            		}
HXLINE( 162)		nodes->push(n);
HXLINE( 163)		this->addNodes(nodes,n->epsilon);
            	}


::hx::Callable< void (::Array< ::Dynamic>, ::hxparse::_LexEngine::Node) > LexEngine_obj::addNode_dyn() { return new __LexEngine_objaddNode(this); }

::Array< ::Dynamic> LexEngine_obj::addNodes(::Array< ::Dynamic> nodes,::Array< ::Dynamic> add){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_166_addNodes)
HXLINE( 167)		{
HXLINE( 167)			int _g = 0;
HXDLIN( 167)			while((_g < add->length)){
HXLINE( 167)				 ::hxparse::_LexEngine::Node n = add->__get(_g).StaticCast<  ::hxparse::_LexEngine::Node >();
HXDLIN( 167)				++_g;
HXLINE( 168)				this->addNode(nodes,n);
            			}
            		}
HXLINE( 169)		return nodes;
            	}


::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > LexEngine_obj::addNodes_dyn() { return new __LexEngine_objaddNodes(this); }

 ::hxparse::_LexEngine::Node LexEngine_obj::node(int pid){
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_173_node)
HXDLIN( 173)		return  ::hxparse::_LexEngine::Node_obj::__alloc( HX_CTX ,this->uid++,pid);
            	}


::hx::Callable<  ::hxparse::_LexEngine::Node (int) > LexEngine_obj::node_dyn() { return new __LexEngine_objnode(this); }

 ::hxparse::_LexEngine::Node LexEngine_obj::initNode( ::hxparse::_LexEngine::Pattern p, ::hxparse::_LexEngine::Node finalId,int pid){
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_177_initNode)
HXDLIN( 177)		switch((int)(p->_hx_getIndex())){
            			case (int)0: {
HXLINE( 179)				return finalId;
            			}
            			break;
            			case (int)1: {
HXLINE( 180)				::Array< ::Dynamic> c = p->_hx_getObject(0).StaticCast< ::Array< ::Dynamic> >();
HXLINE( 181)				 ::hxparse::_LexEngine::Node n =  ::hxparse::_LexEngine::Node_obj::__alloc( HX_CTX ,this->uid++,pid);
HXLINE( 182)				n->trans->push( ::Dynamic(::hx::Anon_obj::Create(2)
            					->setFixed(0,HX_("n",6e,00,00,00),finalId)
            					->setFixed(1,HX_("chars",dd,9c,b3,45),c)));
HXLINE( 183)				return n;
            			}
            			break;
            			case (int)2: {
HXLINE( 184)				 ::hxparse::_LexEngine::Pattern p1 = p->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXLINE( 185)				 ::hxparse::_LexEngine::Node n1 =  ::hxparse::_LexEngine::Node_obj::__alloc( HX_CTX ,this->uid++,pid);
HXLINE( 186)				 ::hxparse::_LexEngine::Node an = this->initNode(p1,n1,pid);
HXLINE( 187)				n1->epsilon->push(an);
HXLINE( 188)				n1->epsilon->push(finalId);
HXLINE( 189)				return n1;
            			}
            			break;
            			case (int)3: {
HXLINE( 190)				 ::hxparse::_LexEngine::Pattern p2 = p->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXLINE( 191)				 ::hxparse::_LexEngine::Node n2 =  ::hxparse::_LexEngine::Node_obj::__alloc( HX_CTX ,this->uid++,pid);
HXLINE( 192)				 ::hxparse::_LexEngine::Node an1 = this->initNode(p2,n2,pid);
HXLINE( 193)				n2->epsilon->push(an1);
HXLINE( 194)				n2->epsilon->push(finalId);
HXLINE( 195)				return an1;
            			}
            			break;
            			case (int)4: {
HXLINE( 196)				 ::hxparse::_LexEngine::Pattern a = p->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 196)				 ::hxparse::_LexEngine::Pattern b = p->_hx_getObject(1).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXLINE( 197)				return this->initNode(a,this->initNode(b,finalId,pid),pid);
            			}
            			break;
            			case (int)5: {
HXLINE( 198)				 ::hxparse::_LexEngine::Pattern a1 = p->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 198)				 ::hxparse::_LexEngine::Pattern b1 = p->_hx_getObject(1).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXLINE( 199)				 ::hxparse::_LexEngine::Node n3 =  ::hxparse::_LexEngine::Node_obj::__alloc( HX_CTX ,this->uid++,pid);
HXLINE( 200)				::Array< ::Dynamic> n4 = n3->epsilon;
HXDLIN( 200)				n4->push(this->initNode(a1,finalId,pid));
HXLINE( 201)				::Array< ::Dynamic> n5 = n3->epsilon;
HXDLIN( 201)				n5->push(this->initNode(b1,finalId,pid));
HXLINE( 202)				return n3;
            			}
            			break;
            			case (int)6: {
HXLINE( 203)				 ::hxparse::_LexEngine::Pattern p3 = p->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXLINE( 204)				return this->initNode(p3,finalId,pid);
            			}
            			break;
            		}
HXLINE( 177)		return null();
            	}


::hx::Callable<  ::hxparse::_LexEngine::Node ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Node,int) > LexEngine_obj::initNode_dyn() { return new __LexEngine_objinitNode(this); }

::Array< ::Dynamic> LexEngine_obj::single(int c){
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_215_single)
HXDLIN( 215)		return ::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c));
            	}


::hx::Callable< ::Array< ::Dynamic> (int) > LexEngine_obj::single_dyn() { return _hx_alloc__LexEngine_objsingle; }

 ::hxparse::_LexEngine::Pattern LexEngine_obj::parse(::String pattern){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_239_parse)
HXLINE( 240)		 ::Dynamic p = ::hxparse::LexEngine_obj::parseInner(::haxe::io::Bytes_obj::ofString(pattern,null()),null(),null());
HXLINE( 241)		if (::hx::IsNull( p )) {
HXLINE( 241)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(((HX_("Invalid pattern '",ce,e7,cb,c4) + pattern) + HX_("'",27,00,00,00))));
            		}
HXLINE( 242)		return p->__Field(HX_("pattern",50,06,77,11),::hx::paccDynamic);
            	}


::hx::Callable<  ::hxparse::_LexEngine::Pattern (::String) > LexEngine_obj::parse_dyn() { return _hx_alloc__LexEngine_objparse; }

 ::hxparse::_LexEngine::Pattern LexEngine_obj::next( ::hxparse::_LexEngine::Pattern a, ::hxparse::_LexEngine::Pattern b){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_246_next)
HXDLIN( 246)		if (::hx::IsPointerEq( a,::hxparse::_LexEngine::Pattern_obj::Empty_dyn() )) {
HXDLIN( 246)			return b;
            		}
            		else {
HXDLIN( 246)			return ::hxparse::_LexEngine::Pattern_obj::Next(a,b);
            		}
HXDLIN( 246)		return null();
            	}


::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern, ::hxparse::_LexEngine::Pattern) > LexEngine_obj::next_dyn() { return _hx_alloc__LexEngine_objnext; }

 ::hxparse::_LexEngine::Pattern LexEngine_obj::plus( ::hxparse::_LexEngine::Pattern r){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_250_plus)
HXDLIN( 250)		if ((r->_hx_getIndex() == 4)) {
HXLINE( 251)			 ::hxparse::_LexEngine::Pattern r1 = r->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 251)			 ::hxparse::_LexEngine::Pattern r2 = r->_hx_getObject(1).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 251)			return ::hxparse::_LexEngine::Pattern_obj::Next(r1,::hxparse::LexEngine_obj::plus(r2));
            		}
            		else {
HXLINE( 252)			return ::hxparse::_LexEngine::Pattern_obj::Plus(r);
            		}
HXLINE( 250)		return null();
            	}


::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > LexEngine_obj::plus_dyn() { return _hx_alloc__LexEngine_objplus; }

 ::hxparse::_LexEngine::Pattern LexEngine_obj::star( ::hxparse::_LexEngine::Pattern r){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_257_star)
HXDLIN( 257)		if ((r->_hx_getIndex() == 4)) {
HXLINE( 258)			 ::hxparse::_LexEngine::Pattern r1 = r->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 258)			 ::hxparse::_LexEngine::Pattern r2 = r->_hx_getObject(1).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 258)			return ::hxparse::_LexEngine::Pattern_obj::Next(r1,::hxparse::LexEngine_obj::star(r2));
            		}
            		else {
HXLINE( 259)			return ::hxparse::_LexEngine::Pattern_obj::Star(r);
            		}
HXLINE( 257)		return null();
            	}


::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > LexEngine_obj::star_dyn() { return _hx_alloc__LexEngine_objstar; }

 ::hxparse::_LexEngine::Pattern LexEngine_obj::opt( ::hxparse::_LexEngine::Pattern r){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_264_opt)
HXDLIN( 264)		if ((r->_hx_getIndex() == 4)) {
HXLINE( 265)			 ::hxparse::_LexEngine::Pattern r1 = r->_hx_getObject(0).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 265)			 ::hxparse::_LexEngine::Pattern r2 = r->_hx_getObject(1).StaticCast<  ::hxparse::_LexEngine::Pattern >();
HXDLIN( 265)			return ::hxparse::_LexEngine::Pattern_obj::Next(r1,::hxparse::LexEngine_obj::opt(r2));
            		}
            		else {
HXLINE( 266)			return ::hxparse::_LexEngine::Pattern_obj::Choice(r,::hxparse::_LexEngine::Pattern_obj::Empty_dyn());
            		}
HXLINE( 264)		return null();
            	}


::hx::Callable<  ::hxparse::_LexEngine::Pattern ( ::hxparse::_LexEngine::Pattern) > LexEngine_obj::opt_dyn() { return _hx_alloc__LexEngine_objopt; }

::Array< ::Dynamic> LexEngine_obj::cinter(::Array< ::Dynamic> c1,::Array< ::Dynamic> c2){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_271_cinter)
HXDLIN( 271)		::Array< ::Dynamic> _hx_tmp = ::hxparse::LexEngine_obj::ccomplement(c1);
HXDLIN( 271)		return ::hxparse::LexEngine_obj::ccomplement(::hxparse::LexEngine_obj::cunion(_hx_tmp,::hxparse::LexEngine_obj::ccomplement(c2)));
            	}


::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > LexEngine_obj::cinter_dyn() { return _hx_alloc__LexEngine_objcinter; }

::Array< ::Dynamic> LexEngine_obj::cdiff(::Array< ::Dynamic> c1,::Array< ::Dynamic> c2){
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_275_cdiff)
HXDLIN( 275)		return ::hxparse::LexEngine_obj::ccomplement(::hxparse::LexEngine_obj::cunion(::hxparse::LexEngine_obj::ccomplement(c1),c2));
            	}


::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > LexEngine_obj::cdiff_dyn() { return _hx_alloc__LexEngine_objcdiff; }

::Array< ::Dynamic> LexEngine_obj::ccomplement(::Array< ::Dynamic> c){
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_278_ccomplement)
HXLINE( 279)		 ::hxparse::_LexEngine::CharRange first = c->__get(0).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXLINE( 280)		int start;
HXDLIN( 280)		bool start1;
HXDLIN( 280)		if (::hx::IsNotNull( first )) {
HXLINE( 280)			start1 = (first->min == -1);
            		}
            		else {
HXLINE( 280)			start1 = false;
            		}
HXDLIN( 280)		if (start1) {
HXLINE( 280)			start = (c->shift().StaticCast<  ::hxparse::_LexEngine::CharRange >()->max + 1);
            		}
            		else {
HXLINE( 280)			start = -1;
            		}
HXLINE( 281)		::Array< ::Dynamic> out = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 282)		{
HXLINE( 282)			int _g = 0;
HXDLIN( 282)			while((_g < c->length)){
HXLINE( 282)				 ::hxparse::_LexEngine::CharRange k = c->__get(_g).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXDLIN( 282)				++_g;
HXLINE( 283)				out->push( ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,start,(k->min - 1)));
HXLINE( 284)				start = (k->max + 1);
            			}
            		}
HXLINE( 286)		if ((start <= 255)) {
HXLINE( 287)			out->push( ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,start,255));
            		}
HXLINE( 288)		return out;
            	}


::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>) > LexEngine_obj::ccomplement_dyn() { return _hx_alloc__LexEngine_objccomplement; }

::Array< ::Dynamic> LexEngine_obj::cunion(::Array< ::Dynamic> ca,::Array< ::Dynamic> cb){
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_291_cunion)
HXLINE( 292)		int i = 0;
HXDLIN( 292)		int j = 0;
HXLINE( 293)		::Array< ::Dynamic> out = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 294)		 ::hxparse::_LexEngine::CharRange a = ca->__get(i++).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXDLIN( 294)		 ::hxparse::_LexEngine::CharRange b = cb->__get(j++).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXLINE( 295)		while(true){
HXLINE( 296)			if (::hx::IsNull( a )) {
HXLINE( 297)				out->push(b);
HXLINE( 298)				while((j < cb->length)){
HXLINE( 299)					out->push(cb->__get(j++).StaticCast<  ::hxparse::_LexEngine::CharRange >());
            				}
HXLINE( 300)				goto _hx_goto_1;
            			}
HXLINE( 302)			if (::hx::IsNull( b )) {
HXLINE( 303)				out->push(a);
HXLINE( 304)				while((i < ca->length)){
HXLINE( 305)					out->push(ca->__get(i++).StaticCast<  ::hxparse::_LexEngine::CharRange >());
            				}
HXLINE( 306)				goto _hx_goto_1;
            			}
HXLINE( 308)			if ((a->min <= b->min)) {
HXLINE( 309)				if (((a->max + 1) < b->min)) {
HXLINE( 310)					out->push(a);
HXLINE( 311)					a = ca->__get(i++).StaticCast<  ::hxparse::_LexEngine::CharRange >();
            				}
            				else {
HXLINE( 312)					if ((a->max < b->max)) {
HXLINE( 313)						b =  ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,a->min,b->max);
HXLINE( 314)						a = ca->__get(i++).StaticCast<  ::hxparse::_LexEngine::CharRange >();
            					}
            					else {
HXLINE( 316)						b = cb->__get(j++).StaticCast<  ::hxparse::_LexEngine::CharRange >();
            					}
            				}
            			}
            			else {
HXLINE( 319)				::Array< ::Dynamic> tmp = ca;
HXLINE( 320)				ca = cb;
HXLINE( 321)				cb = tmp;
HXLINE( 322)				int tmp1 = j;
HXLINE( 323)				j = i;
HXLINE( 324)				i = tmp1;
HXLINE( 325)				 ::hxparse::_LexEngine::CharRange tmp2 = a;
HXLINE( 326)				a = b;
HXLINE( 327)				b = tmp2;
            			}
            		}
            		_hx_goto_1:;
HXLINE( 330)		return out;
            	}


::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>,::Array< ::Dynamic>) > LexEngine_obj::cunion_dyn() { return _hx_alloc__LexEngine_objcunion; }

 ::Dynamic LexEngine_obj::parseInner( ::haxe::io::Bytes pattern, ::Dynamic __o_i, ::Dynamic __o_pDepth){
HX_BEGIN_LOCAL_FUNC_S2(::hx::AutoCallable_obj< int() >, _hx_Closure_0, ::Array< int >,i1, ::haxe::io::Bytes,pattern)
            		int HX_LOCAL_RUN(  ){
            			HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_334_parseInner)
HXLINE( 335)			int i = i1[0]++;
HXDLIN( 335)			int c = pattern->get(i);
HXLINE( 336)			if ((c == 0)) {
HXLINE( 337)				c = 92;
            			}
            			else {
HXLINE( 338)				if ((c == 120)) {
HXLINE( 339)					c = ( (int)(::Std_obj::parseInt((HX_("0x",48,2a,00,00) + pattern->getString(i1->__get(0),2,null())))) );
HXLINE( 340)					::hx::AddEq(i1[0],2);
            				}
            				else {
HXLINE( 341)					bool readChar;
HXDLIN( 341)					if ((c >= 48)) {
HXLINE( 341)						readChar = (c <= 57);
            					}
            					else {
HXLINE( 341)						readChar = false;
            					}
HXDLIN( 341)					if (readChar) {
HXLINE( 342)						int v = (c - 48);
HXLINE( 343)						while(true){
HXLINE( 344)							int cNext = pattern->get(i1->__get(0));
HXLINE( 345)							bool readChar1;
HXDLIN( 345)							if ((cNext >= 48)) {
HXLINE( 345)								readChar1 = (cNext <= 57);
            							}
            							else {
HXLINE( 345)								readChar1 = false;
            							}
HXDLIN( 345)							if (readChar1) {
HXLINE( 346)								v = ((v * 10) + (cNext - 48));
HXLINE( 347)								++i1[0];
            							}
            							else {
HXLINE( 349)								goto _hx_goto_1;
            							}
            						}
            						_hx_goto_1:;
HXLINE( 352)						c = v;
            					}
            				}
            			}
HXLINE( 354)			return c;
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC0(return)

            		 ::Dynamic i = __o_i;
            		if (::hx::IsNull(__o_i)) i = 0;
            		 ::Dynamic pDepth = __o_pDepth;
            		if (::hx::IsNull(__o_pDepth)) pDepth = 0;
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_333_parseInner)
HXDLIN( 333)		::Array< int > i1 = ::Array_obj< int >::__new(1)->init(0,( (int)(i) ));
HXLINE( 334)		::hx::Callable< int () > readChar = ::hx::Callable< int() >(new _hx_Closure_0(i1,pattern));
HXLINE( 357)		 ::hxparse::_LexEngine::Pattern r = ::hxparse::_LexEngine::Pattern_obj::Empty_dyn();
HXLINE( 358)		int l = pattern->length;
HXLINE( 359)		while((i1->__get(0) < l)){
HXLINE( 360)			int i2 = i1[0]++;
HXDLIN( 360)			int c = pattern->get(i2);
HXLINE( 361)			if ((c > 255)) {
HXLINE( 361)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(c));
            			}
HXLINE( 362)			switch((int)(c)){
            				case (int)40: {
HXLINE( 375)					 ::Dynamic r2 = ::hxparse::LexEngine_obj::parseInner(pattern,i1->__get(0),(( (int)(pDepth) ) + 1));
HXLINE( 376)					i1[0] = ( (int)(r2->__Field(HX_("pos",94,5d,55,00),::hx::paccDynamic)) );
HXLINE( 377)					r = ::hxparse::LexEngine_obj::next(r,r2->__Field(HX_("pattern",50,06,77,11),::hx::paccDynamic));
            				}
            				break;
            				case (int)41: {
HXLINE( 379)					if (::hx::IsPointerEq( r,::hxparse::_LexEngine::Pattern_obj::Empty_dyn() )) {
HXLINE( 379)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("Empty group",4c,f9,26,dd)));
            					}
HXLINE( 380)					return  ::Dynamic(::hx::Anon_obj::Create(2)
            						->setFixed(0,HX_("pos",94,5d,55,00),i1->__get(0))
            						->setFixed(1,HX_("pattern",50,06,77,11),::hxparse::_LexEngine::Pattern_obj::Group(r)));
            				}
            				break;
            				case (int)42: {
HXLINE( 365)					if (::hx::IsPointerNotEq( r,::hxparse::_LexEngine::Pattern_obj::Empty_dyn() )) {
HXLINE( 366)						r = ::hxparse::LexEngine_obj::star(r);
            					}
            					else {
HXLINE( 422)						r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            					}
            				}
            				break;
            				case (int)43: {
HXLINE( 363)					if (::hx::IsPointerNotEq( r,::hxparse::_LexEngine::Pattern_obj::Empty_dyn() )) {
HXLINE( 364)						r = ::hxparse::LexEngine_obj::plus(r);
            					}
            					else {
HXLINE( 422)						r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            					}
            				}
            				break;
            				case (int)46: {
HXLINE( 373)					r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::hxparse::LexEngine_obj::ALL_CHARS));
            				}
            				break;
            				case (int)63: {
HXLINE( 367)					if (::hx::IsPointerNotEq( r,::hxparse::_LexEngine::Pattern_obj::Empty_dyn() )) {
HXLINE( 368)						r = ::hxparse::LexEngine_obj::opt(r);
            					}
            					else {
HXLINE( 422)						r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            					}
            				}
            				break;
            				case (int)91: {
HXLINE( 381)					if ((pattern->length > 1)) {
HXLINE( 382)						int range = 0;
HXLINE( 383)						::Array< ::Dynamic> acc = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 384)						bool _hx_not = (pattern->get(i1->__get(0)) == 94);
HXLINE( 385)						if (_hx_not) {
HXLINE( 385)							i1[0]++;
            						}
HXLINE( 386)						while(true){
HXLINE( 387)							int i3 = i1[0]++;
HXDLIN( 387)							int c1 = pattern->get(i3);
HXLINE( 388)							if ((c1 == 93)) {
HXLINE( 389)								if ((range != 0)) {
HXLINE( 389)									return null();
            								}
HXLINE( 390)								goto _hx_goto_2;
            							}
            							else {
HXLINE( 391)								if ((c1 == 45)) {
HXLINE( 392)									if ((range != 0)) {
HXLINE( 392)										return null();
            									}
HXLINE( 393)									 ::hxparse::_LexEngine::CharRange last = acc->pop().StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXLINE( 394)									if (::hx::IsNull( last )) {
HXLINE( 395)										acc->push( ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c1,c1));
            									}
            									else {
HXLINE( 397)										if ((last->min != last->max)) {
HXLINE( 397)											return null();
            										}
HXLINE( 398)										range = last->min;
            									}
            								}
            								else {
HXLINE( 401)									if ((c1 == 92)) {
HXLINE( 402)										c1 = ( (int)(readChar()) );
            									}
HXLINE( 404)									if ((range == 0)) {
HXLINE( 405)										acc->push( ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c1,c1));
            									}
            									else {
HXLINE( 407)										acc->push( ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,range,c1));
HXLINE( 408)										range = 0;
            									}
            								}
            							}
            						}
            						_hx_goto_2:;
HXLINE( 412)						::Array< ::Dynamic> g = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 413)						{
HXLINE( 413)							int _g = 0;
HXDLIN( 413)							while((_g < acc->length)){
HXLINE( 413)								 ::hxparse::_LexEngine::CharRange k = acc->__get(_g).StaticCast<  ::hxparse::_LexEngine::CharRange >();
HXDLIN( 413)								++_g;
HXLINE( 414)								g = ::hxparse::LexEngine_obj::cunion(g,::Array_obj< ::Dynamic>::__new(1)->init(0,k));
            							}
            						}
HXLINE( 415)						if (_hx_not) {
HXLINE( 416)							g = ::hxparse::LexEngine_obj::cdiff(::hxparse::LexEngine_obj::ALL_CHARS,g);
            						}
HXLINE( 417)						r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(g));
            					}
            					else {
HXLINE( 422)						r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            					}
            				}
            				break;
            				case (int)92: {
HXLINE( 419)					c = ( (int)(readChar()) );
HXLINE( 420)					r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            				}
            				break;
            				case (int)124: {
HXLINE( 369)					if (::hx::IsPointerNotEq( r,::hxparse::_LexEngine::Pattern_obj::Empty_dyn() )) {
HXLINE( 370)						 ::Dynamic r21 = ::hxparse::LexEngine_obj::parseInner(pattern,i1->__get(0),null());
HXLINE( 371)						return  ::Dynamic(::hx::Anon_obj::Create(2)
            							->setFixed(0,HX_("pos",94,5d,55,00),( (int)(r21->__Field(HX_("pos",94,5d,55,00),::hx::paccDynamic)) ))
            							->setFixed(1,HX_("pattern",50,06,77,11),::hxparse::_LexEngine::Pattern_obj::Choice(r,r21->__Field(HX_("pattern",50,06,77,11),::hx::paccDynamic))));
            					}
            					else {
HXLINE( 422)						r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            					}
            				}
            				break;
            				default:{
HXLINE( 422)					r = ::hxparse::LexEngine_obj::next(r,::hxparse::_LexEngine::Pattern_obj::Match(::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,c,c))));
            				}
            			}
            		}
HXLINE( 425)		if ((( (int)(pDepth) ) != 0)) {
HXLINE( 425)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(((HX_("Found unclosed parenthesis while parsing \"",9c,e2,66,ce) + ::Std_obj::string(pattern)) + HX_("\"",22,00,00,00))));
            		}
HXLINE( 426)		return  ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("pos",94,5d,55,00),i1->__get(0))
            			->setFixed(1,HX_("pattern",50,06,77,11),r));
            	}


::hx::Callable<  ::Dynamic ( ::haxe::io::Bytes, ::Dynamic, ::Dynamic) > LexEngine_obj::parseInner_dyn() { return _hx_alloc__LexEngine_objparseInner; }

int LexEngine_obj::MAX_CODE;

::Array< ::Dynamic> LexEngine_obj::EMPTY;

::Array< ::Dynamic> LexEngine_obj::ALL_CHARS;


::hx::ObjectPtr< LexEngine_obj > LexEngine_obj::__new(::Array< ::Dynamic> patterns) {
	::hx::ObjectPtr< LexEngine_obj > __this = new LexEngine_obj();
	__this->__construct(patterns);
	return __this;
}

::hx::ObjectPtr< LexEngine_obj > LexEngine_obj::__alloc(::hx::Ctx *_hx_ctx,::Array< ::Dynamic> patterns) {
	LexEngine_obj* __this = (LexEngine_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(LexEngine_obj), true, "hxparse.LexEngine"));
	*(void **)__this = LexEngine_obj::_hx_vtable;
	__this->__construct(patterns);
	return __this;
}

LexEngine_obj::LexEngine_obj()
{
}

void LexEngine_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(LexEngine);
	HX_MARK_MEMBER_NAME(uid, "uid");
	HX_MARK_MEMBER_NAME(nodes, "nodes");
	HX_MARK_MEMBER_NAME(finals, "finals");
	HX_MARK_MEMBER_NAME(states, "states");
	HX_MARK_MEMBER_NAME(hstates, "hstates");
	HX_MARK_END_CLASS();
}

void LexEngine_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(uid, "uid");
	HX_VISIT_MEMBER_NAME(nodes, "nodes");
	HX_VISIT_MEMBER_NAME(finals, "finals");
	HX_VISIT_MEMBER_NAME(states, "states");
	HX_VISIT_MEMBER_NAME(hstates, "hstates");
}

::hx::Val LexEngine_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"uid") ) { return ::hx::Val( uid ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"node") ) { return ::hx::Val( node_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"nodes") ) { return ::hx::Val( nodes ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"finals") ) { return ::hx::Val( finals ); }
		if (HX_FIELD_EQ(inName,"states") ) { return ::hx::Val( states ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"addNode") ) { return ::hx::Val( addNode_dyn() ); }
		if (HX_FIELD_EQ(inName,"hstates") ) { return ::hx::Val( hstates ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"addNodes") ) { return ::hx::Val( addNodes_dyn() ); }
		if (HX_FIELD_EQ(inName,"initNode") ) { return ::hx::Val( initNode_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"makeState") ) { return ::hx::Val( makeState_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"firstState") ) { return ::hx::Val( firstState_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"getTransitions") ) { return ::hx::Val( getTransitions_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool LexEngine_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"opt") ) { outValue = opt_dyn(); return true; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"next") ) { outValue = next_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"plus") ) { outValue = plus_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"star") ) { outValue = star_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"parse") ) { outValue = parse_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"cdiff") ) { outValue = cdiff_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"EMPTY") ) { outValue = EMPTY; return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"single") ) { outValue = single_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"cinter") ) { outValue = cinter_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"cunion") ) { outValue = cunion_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"MAX_CODE") ) { outValue = MAX_CODE; return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"ALL_CHARS") ) { outValue = ALL_CHARS; return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"parseInner") ) { outValue = parseInner_dyn(); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"ccomplement") ) { outValue = ccomplement_dyn(); return true; }
	}
	return false;
}

::hx::Val LexEngine_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"uid") ) { uid = inValue.Cast< int >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"nodes") ) { nodes = inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"finals") ) { finals = inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		if (HX_FIELD_EQ(inName,"states") ) { states = inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"hstates") ) { hstates = inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

bool LexEngine_obj::__SetStatic(const ::String& inName, ::Dynamic& ioValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"EMPTY") ) { EMPTY = ioValue.Cast< ::Array< ::Dynamic> >(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"ALL_CHARS") ) { ALL_CHARS = ioValue.Cast< ::Array< ::Dynamic> >(); return true; }
	}
	return false;
}

void LexEngine_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("uid",90,23,59,00));
	outFields->push(HX_("nodes",31,b8,be,9f));
	outFields->push(HX_("finals",3d,28,79,86));
	outFields->push(HX_("states",42,d9,fb,05));
	outFields->push(HX_("hstates",aa,17,b4,ea));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo LexEngine_obj_sMemberStorageInfo[] = {
	{ ::hx::fsInt, (int)offsetof(LexEngine_obj, uid), HX_("uid",90,23,59,00) },
	{ ::hx::fsObject /* ::Array< ::Dynamic> */ , (int)offsetof(LexEngine_obj, nodes), HX_("nodes",31,b8,be,9f) },
	{ ::hx::fsObject /* ::Array< ::Dynamic> */ , (int)offsetof(LexEngine_obj, finals), HX_("finals",3d,28,79,86) },
	{ ::hx::fsObject /* ::Array< ::Dynamic> */ , (int)offsetof(LexEngine_obj, states), HX_("states",42,d9,fb,05) },
	{ ::hx::fsObject /*  ::haxe::ds::StringMap */ , (int)offsetof(LexEngine_obj, hstates), HX_("hstates",aa,17,b4,ea) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo LexEngine_obj_sStaticStorageInfo[] = {
	{ ::hx::fsInt, (void*) &LexEngine_obj::MAX_CODE, HX_("MAX_CODE",08,d0,1d,d2) },
	{ ::hx::fsObject /* ::Array< ::Dynamic> */ , (void*) &LexEngine_obj::EMPTY, HX_("EMPTY",6d,72,c8,ed) },
	{ ::hx::fsObject /* ::Array< ::Dynamic> */ , (void*) &LexEngine_obj::ALL_CHARS, HX_("ALL_CHARS",bf,e7,2d,a2) },
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static ::String LexEngine_obj_sMemberFields[] = {
	HX_("firstState",c1,bf,e9,c1),
	HX_("makeState",43,ed,a3,57),
	HX_("getTransitions",48,a8,8a,c8),
	HX_("addNode",c3,4c,47,85),
	HX_("addNodes",50,de,1b,19),
	HX_("node",02,0a,0a,49),
	HX_("initNode",32,39,c1,4d),
	HX_("uid",90,23,59,00),
	HX_("nodes",31,b8,be,9f),
	HX_("finals",3d,28,79,86),
	HX_("states",42,d9,fb,05),
	HX_("hstates",aa,17,b4,ea),
	::String(null())
};

static void LexEngine_obj_sMarkStatics(HX_MARK_PARAMS) { 
	HX_MARK_MEMBER_NAME(LexEngine_obj::MAX_CODE, "MAX_CODE");
	HX_MARK_MEMBER_NAME(LexEngine_obj::EMPTY, "EMPTY");
	HX_MARK_MEMBER_NAME(LexEngine_obj::ALL_CHARS, "ALL_CHARS");
 };

#ifdef HXCPP_VISIT_ALLOCS
static void LexEngine_obj_sVisitStatics(HX_VISIT_PARAMS) { 
	HX_VISIT_MEMBER_NAME(LexEngine_obj::MAX_CODE, "MAX_CODE");
	HX_VISIT_MEMBER_NAME(LexEngine_obj::EMPTY, "EMPTY");
	HX_VISIT_MEMBER_NAME(LexEngine_obj::ALL_CHARS, "ALL_CHARS");
 };

#endif

::hx::Class LexEngine_obj::__mClass;

static ::String LexEngine_obj_sStaticFields[] = {
	HX_("single",88,66,21,b9),
	HX_("parse",33,90,55,bd),
	HX_("next",f3,84,02,49),
	HX_("plus",5a,3f,5a,4a),
	HX_("star",d2,e3,5b,4c),
	HX_("opt",33,9c,54,00),
	HX_("cinter",d9,77,75,53),
	HX_("cdiff",e8,c9,14,43),
	HX_("ccomplement",09,bd,b7,d3),
	HX_("cunion",cc,1d,3c,3c),
	HX_("parseInner",63,78,fd,e7),
	HX_("MAX_CODE",08,d0,1d,d2),
	HX_("EMPTY",6d,72,c8,ed),
	HX_("ALL_CHARS",bf,e7,2d,a2),
	::String(null())
};

void LexEngine_obj::__register()
{
	LexEngine_obj _hx_dummy;
	LexEngine_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("hxparse.LexEngine",d6,a7,f5,60);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &LexEngine_obj::__GetStatic;
	__mClass->mSetStaticField = &LexEngine_obj::__SetStatic;
	__mClass->mMarkFunc = LexEngine_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(LexEngine_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(LexEngine_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< LexEngine_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = LexEngine_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = LexEngine_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = LexEngine_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void LexEngine_obj::__boot()
{
_hx_alloc__LexEngine_objsingle = new (::hx::NewObjectType::NewObjConst) __LexEngine_objsingle();

_hx_alloc__LexEngine_objparse = new (::hx::NewObjectType::NewObjConst) __LexEngine_objparse();

_hx_alloc__LexEngine_objnext = new (::hx::NewObjectType::NewObjConst) __LexEngine_objnext();

_hx_alloc__LexEngine_objplus = new (::hx::NewObjectType::NewObjConst) __LexEngine_objplus();

_hx_alloc__LexEngine_objstar = new (::hx::NewObjectType::NewObjConst) __LexEngine_objstar();

_hx_alloc__LexEngine_objopt = new (::hx::NewObjectType::NewObjConst) __LexEngine_objopt();

_hx_alloc__LexEngine_objcinter = new (::hx::NewObjectType::NewObjConst) __LexEngine_objcinter();

_hx_alloc__LexEngine_objcdiff = new (::hx::NewObjectType::NewObjConst) __LexEngine_objcdiff();

_hx_alloc__LexEngine_objccomplement = new (::hx::NewObjectType::NewObjConst) __LexEngine_objccomplement();

_hx_alloc__LexEngine_objcunion = new (::hx::NewObjectType::NewObjConst) __LexEngine_objcunion();

_hx_alloc__LexEngine_objparseInner = new (::hx::NewObjectType::NewObjConst) __LexEngine_objparseInner();

{
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_210_boot)
HXDLIN( 210)		::hxparse::LexEngine_obj::MAX_CODE = 255;
            	}
{
            	HX_STACKFRAME(&_hx_pos_c89ea2fff599559e_211_boot)
HXDLIN( 211)		::hxparse::LexEngine_obj::EMPTY = ::Array_obj< ::Dynamic>::__new(0);
            	}
{
            	HX_GC_STACKFRAME(&_hx_pos_c89ea2fff599559e_212_boot)
HXDLIN( 212)		::hxparse::LexEngine_obj::ALL_CHARS = ::Array_obj< ::Dynamic>::__new(1)->init(0, ::hxparse::_LexEngine::CharRange_obj::__alloc( HX_CTX ,0,255));
            	}
}

} // end namespace hxparse
