// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_hxparse_NoMatch
#include <hxparse/NoMatch.h>
#endif
#ifndef INCLUDED_hxparse_ParserError
#include <hxparse/ParserError.h>
#endif
#ifndef INCLUDED_hxparse_Position
#include <hxparse/Position.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_ba314220fea0ce6c_18_new,"hxparse.NoMatch","new",0xc1936e4b,"hxparse.NoMatch.new","hxparse/NoMatch.hx",18,0xbd6e8ec6)
HX_LOCAL_STACK_FRAME(_hx_pos_ba314220fea0ce6c_24_toString,"hxparse.NoMatch","toString",0x9053dee1,"hxparse.NoMatch.toString","hxparse/NoMatch.hx",24,0xbd6e8ec6)

namespace {

}

namespace hxparse{

void NoMatch_obj::__construct( ::hxparse::Position pos, ::Dynamic token){
            	HX_STACKFRAME(&_hx_pos_ba314220fea0ce6c_18_new)
HXLINE(  19)		super::__construct(pos);
HXLINE(  20)		this->token = token;
            	}

::Dynamic NoMatch_obj::__CreateEmpty() { return new NoMatch_obj; }

void* NoMatch_obj::_hx_vtable = 0;

::Dynamic NoMatch_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< NoMatch_obj > _hx_result = new NoMatch_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool NoMatch_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x436af146) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x436af146;
	} else {
		return inClassId==(int)0x7ad6c495;
	}
}

::String NoMatch_obj::toString(){
            	HX_STACKFRAME(&_hx_pos_ba314220fea0ce6c_24_toString)
HXDLIN(  24)		return (HX_("No match: ",6c,68,27,bd) + ::Std_obj::string(this->token));
            	}



::hx::ObjectPtr< NoMatch_obj > NoMatch_obj::__new( ::hxparse::Position pos, ::Dynamic token) {
	::hx::ObjectPtr< NoMatch_obj > __this = new NoMatch_obj();
	__this->__construct(pos,token);
	return __this;
}

::hx::ObjectPtr< NoMatch_obj > NoMatch_obj::__alloc(::hx::Ctx *_hx_ctx, ::hxparse::Position pos, ::Dynamic token) {
	NoMatch_obj* __this = (NoMatch_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(NoMatch_obj), true, "hxparse.NoMatch"));
	*(void **)__this = NoMatch_obj::_hx_vtable;
	__this->__construct(pos,token);
	return __this;
}

NoMatch_obj::NoMatch_obj()
{
}

void NoMatch_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(NoMatch);
	HX_MARK_MEMBER_NAME(token, "token");
	 ::hxparse::ParserError_obj::__Mark(HX_MARK_ARG);
	HX_MARK_END_CLASS();
}

void NoMatch_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(token, "token");
	 ::hxparse::ParserError_obj::__Visit(HX_VISIT_ARG);
}

::hx::Val NoMatch_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"token") ) { return ::hx::Val( token ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"toString") ) { return ::hx::Val( toString_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val NoMatch_obj::__SetField(const ::String& inName, const ::hx::Val& inValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"token") ) { token = inValue.Cast<  ::Dynamic >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void NoMatch_obj::__GetFields(::Array< ::String >& outFields)
{
	outFields->push(HX_("token",f9,82,2b,14));
	super::__GetFields(outFields);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo NoMatch_obj_sMemberStorageInfo[] = {
	{ ::hx::fsObject /*  ::Dynamic */ , (int)offsetof(NoMatch_obj, token), HX_("token",f9,82,2b,14) },
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo* NoMatch_obj_sStaticStorageInfo = 0;
#endif

static ::String NoMatch_obj_sMemberFields[] = {
	HX_("toString",ac,d0,6e,38),
	HX_("token",f9,82,2b,14),
	::String(null())
};

::hx::Class NoMatch_obj::__mClass;

static ::String* NoMatch_obj_sStaticFields = 0;

void NoMatch_obj::__register()
{
	NoMatch_obj _hx_dummy;
	NoMatch_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("hxparse.NoMatch",d9,ec,7d,1d);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(NoMatch_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(NoMatch_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< NoMatch_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = NoMatch_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = NoMatch_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace hxparse
