// Generated by Haxe 5.0.0-preview.1
#ifndef INCLUDED_haxe_Exception
#define INCLUDED_haxe_Exception

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(haxe,Exception)
HX_DECLARE_CLASS1(haxe,StackItem)

namespace haxe{


class HXCPP_CLASS_ATTRIBUTES Exception_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Exception_obj OBJ_;
		Exception_obj();

	public:
		enum { _hx_ClassId = 0x677ddc49 };

		void __construct(::String message, ::haxe::Exception previous, ::Dynamic native);
		inline void *operator new(size_t inSize, bool inContainer=true, const char* inName="haxe.Exception")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize + extra, true, "haxe.Exception"); }
		static ::hx::ObjectPtr< Exception_obj > __new(::String message, ::haxe::Exception previous, ::Dynamic native);
		static ::hx::ObjectPtr< Exception_obj > __alloc(::hx::Ctx *_hx_ctx,::String message, ::haxe::Exception previous, ::Dynamic native);
		static void * _hx_vtable;
		static ::Dynamic __CreateEmpty();
		static ::Dynamic __Create(::hx::DynamicArray inArgs);
		//~Exception_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(::Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Exception",2f,f0,6c,eb); }

		static void __boot();
		static  ::haxe::Exception caught( ::Dynamic value);
		static ::hx::Callable<  ::haxe::Exception ( ::Dynamic) > caught_dyn();

		static  ::Dynamic thrown( ::Dynamic value);
		static ::hx::Callable<  ::Dynamic ( ::Dynamic) > thrown_dyn();

		virtual   ::Dynamic unwrap();
		::hx::Callable<  ::Dynamic () > unwrap_dyn();

		virtual ::String toString();
		::hx::Callable< ::String () > toString_dyn();

		 ::String details();
		::hx::Callable< ::String () > details_dyn();

		 void _hx___shiftStack();
		::hx::Callable< void () > _hx___shiftStack_dyn();

		 void _hx___unshiftStack();
		::hx::Callable< void () > _hx___unshiftStack_dyn();

		 ::String get_message();
		::hx::Callable< ::String () > get_message_dyn();

		  ::haxe::Exception get_previous();
		::hx::Callable<  ::haxe::Exception () > get_previous_dyn();

		  ::Dynamic get_native();
		::hx::Callable<  ::Dynamic () > get_native_dyn();

		 ::Array< ::Dynamic> get_stack();
		::hx::Callable< ::Array< ::Dynamic> () > get_stack_dyn();

		 ::Array< ::Dynamic> set_stack(::Array< ::Dynamic> stack);
		::hx::Callable< ::Array< ::Dynamic> (::Array< ::Dynamic>) > set_stack_dyn();

		::String _hx___exceptionMessage;
		::Array< ::Dynamic> _hx___exceptionStack;
		::Array< ::String > _hx___nativeStack;
		int _hx___skipStack;
		 ::Dynamic _hx___nativeException;
		 ::haxe::Exception _hx___previousException;
		::String _hx_customStack;
};

} // end namespace haxe

#endif /* INCLUDED_haxe_Exception */ 
