package cs.system.xml.xsl;

/** Transforms XML data using an XSLT style sheet. */
@:native("System.Xml.Xsl.XslCompiledTransform")
extern class XslCompiledTransform {
	/**
	 * Gets an  object that contains the output information derived from the xsl:output
	 * element of the style sheet.
	 * @return A read-only  object that contains the output information derived from
	 * the xsl:output element of the style sheet. This value can be .
	 */
	var OutputSettings(default, never):cs.system.xml.XmlWriterSettings;
	@:overload(function():Void {})
	function new(enableDebug:Bool):Void;
	@:overload(function(stylesheetUri:String):Void {})
	@:overload(function(compiledStylesheet:cs.system.Type):Void {})
	@:overload(function(stylesheet:cs.system.xml.XmlReader):Void {})
	@:overload(function(stylesheet:cs.system.xml.xpath.IXPathNavigable):Void {})
	@:overload(function(executeMethod:cs.system.reflection.MethodInfo, queryData:cs.NativeArray<cs.UInt8>, earlyBoundTypes:cs.NativeArray<cs.system.Type>):Void {})
	@:overload(function(stylesheetUri:String, settings:cs.system.xml.xsl.XsltSettings, stylesheetResolver:cs.system.xml.XmlResolver):Void {})
	@:overload(function(stylesheet:cs.system.xml.XmlReader, settings:cs.system.xml.xsl.XsltSettings, stylesheetResolver:cs.system.xml.XmlResolver):Void {})
	/**
	 * Loads a method from a style sheet compiled using the  utility.
	 * @param executeMethod A  object representing the compiler-generated execute
	 * method of the compiled style sheet.
	 * @param queryData A byte array of serialized data structures in the staticData
	 * field of the compiled style sheet as generated by the  method.
	 * @param earlyBoundTypes An array of types stored in the compiler-generated
	 * ebTypes field of the compiled style sheet.
	 */
	function Load(stylesheet:cs.system.xml.xpath.IXPathNavigable, settings:cs.system.xml.xsl.XsltSettings, stylesheetResolver:cs.system.xml.XmlResolver):Void;
	@:overload(function(inputUri:String, resultsFile:String):Void {})
	@:overload(function(inputUri:String, results:cs.system.xml.XmlWriter):Void {})
	@:overload(function(input:cs.system.xml.XmlReader, results:cs.system.xml.XmlWriter):Void {})
	@:overload(function(input:cs.system.xml.xpath.IXPathNavigable, results:cs.system.xml.XmlWriter):Void {})
	@:overload(function(inputUri:String, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.io.Stream):Void {})
	@:overload(function(inputUri:String, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.io.TextWriter):Void {})
	@:overload(function(inputUri:String, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.xml.XmlWriter):Void {})
	@:overload(function(input:cs.system.xml.XmlReader, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.io.Stream):Void {})
	@:overload(function(input:cs.system.xml.XmlReader, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.io.TextWriter):Void {})
	@:overload(function(input:cs.system.xml.XmlReader, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.xml.XmlWriter):Void {})
	@:overload(function(input:cs.system.xml.xpath.IXPathNavigable, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.io.Stream):Void {})
	@:overload(function(input:cs.system.xml.xpath.IXPathNavigable, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.io.TextWriter):Void {})
	@:overload(function(input:cs.system.xml.xpath.IXPathNavigable, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.xml.XmlWriter):Void {})
	@:overload(function(input:cs.system.xml.XmlReader, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.xml.XmlWriter, documentResolver:cs.system.xml.XmlResolver):Void {})
	/**
	 * Executes the transform using the input document specified by the URI and outputs
	 * the results to a file.
	 * @param inputUri The URI of the input document.
	 * @param resultsFile The URI of the output file.
	 */
	function Transform(input:cs.system.xml.xpath.IXPathNavigable, arguments:cs.system.xml.xsl.XsltArgumentList, results:cs.system.xml.XmlWriter, documentResolver:cs.system.xml.XmlResolver):Void;
}
