package flash.ui;

extern class Keyboard {
	function new() : Void;
	static var BACKSPACE : UInt;
	static var CAPS_LOCK : UInt;
	static var CONTROL : UInt;
	static var DELETE : UInt;
	static var DOWN : UInt;
	static var END : UInt;
	static var ENTER : UInt;
	static var ESCAPE : UInt;
	static var F1 : UInt;
	static var F10 : UInt;
	static var F11 : UInt;
	static var F12 : UInt;
	static var F13 : UInt;
	static var F14 : UInt;
	static var F15 : UInt;
	static var F2 : UInt;
	static var F3 : UInt;
	static var F4 : UInt;
	static var F5 : UInt;
	static var F6 : UInt;
	static var F7 : UInt;
	static var F8 : UInt;
	static var F9 : UInt;
	static var HOME : UInt;
	static var INSERT : UInt;
	static var LEFT : UInt;
	static var NUMPAD_0 : UInt;
	static var NUMPAD_1 : UInt;
	static var NUMPAD_2 : UInt;
	static var NUMPAD_3 : UInt;
	static var NUMPAD_4 : UInt;
	static var NUMPAD_5 : UInt;
	static var NUMPAD_6 : UInt;
	static var NUMPAD_7 : UInt;
	static var NUMPAD_8 : UInt;
	static var NUMPAD_9 : UInt;
	static var NUMPAD_ADD : UInt;
	static var NUMPAD_DECIMAL : UInt;
	static var NUMPAD_DIVIDE : UInt;
	static var NUMPAD_ENTER : UInt;
	static var NUMPAD_MULTIPLY : UInt;
	static var NUMPAD_SUBTRACT : UInt;
	static var PAGE_DOWN : UInt;
	static var PAGE_UP : UInt;
	static var RIGHT : UInt;
	static var SHIFT : UInt;
	static var SPACE : UInt;
	static var TAB : UInt;
	static var UP : UInt;
	static var capsLock(default,null) : Bool;
	static function isAccessible() : Bool;
	static var numLock(default,null) : Bool;
}
