package flash.ui;

extern class Keyboard {
	@:require(flash10_1) static var A : UInt;
	@:require(flash10_1) static var ALTERNATE : UInt;
	@:require(flash10_1) static var B : UInt;
	@:require(flash10_1) static var BACKQUOTE : UInt;
	@:require(flash10_1) static var BACKSLASH : UInt;
	static var BACKSPACE : UInt;
	@:require(flash10_1) static var C : UInt;
	static var CAPS_LOCK : UInt;
	@:require(flash10_1) static var COMMA : UInt;
	@:require(flash10_1) static var COMMAND : UInt;
	static var CONTROL : UInt;
	@:require(flash10_1) static var CharCodeStrings : Array<Dynamic>;
	@:require(flash10_1) static var D : UInt;
	static var DELETE : UInt;
	static var DOWN : UInt;
	@:require(flash10_1) static var E : UInt;
	static var END : UInt;
	static var ENTER : UInt;
	@:require(flash10_1) static var EQUAL : UInt;
	static var ESCAPE : UInt;
	@:require(flash10_1) static var F : UInt;
	static var F1 : UInt;
	static var F10 : UInt;
	static var F11 : UInt;
	static var F12 : UInt;
	static var F13 : UInt;
	static var F14 : UInt;
	static var F15 : UInt;
	static var F2 : UInt;
	static var F3 : UInt;
	static var F4 : UInt;
	static var F5 : UInt;
	static var F6 : UInt;
	static var F7 : UInt;
	static var F8 : UInt;
	static var F9 : UInt;
	@:require(flash10_1) static var G : UInt;
	@:require(flash10_1) static var H : UInt;
	static var HOME : UInt;
	@:require(flash10_1) static var I : UInt;
	static var INSERT : UInt;
	@:require(flash10_1) static var J : UInt;
	@:require(flash10_1) static var K : UInt;
	@:require(flash10_1) static var KEYNAME_BEGIN : String;
	@:require(flash10_1) static var KEYNAME_BREAK : String;
	@:require(flash10_1) static var KEYNAME_CLEARDISPLAY : String;
	@:require(flash10_1) static var KEYNAME_CLEARLINE : String;
	@:require(flash10_1) static var KEYNAME_DELETE : String;
	@:require(flash10_1) static var KEYNAME_DELETECHAR : String;
	@:require(flash10_1) static var KEYNAME_DELETELINE : String;
	@:require(flash10_1) static var KEYNAME_DOWNARROW : String;
	@:require(flash10_1) static var KEYNAME_END : String;
	@:require(flash10_1) static var KEYNAME_EXECUTE : String;
	@:require(flash10_1) static var KEYNAME_F1 : String;
	@:require(flash10_1) static var KEYNAME_F10 : String;
	@:require(flash10_1) static var KEYNAME_F11 : String;
	@:require(flash10_1) static var KEYNAME_F12 : String;
	@:require(flash10_1) static var KEYNAME_F13 : String;
	@:require(flash10_1) static var KEYNAME_F14 : String;
	@:require(flash10_1) static var KEYNAME_F15 : String;
	@:require(flash10_1) static var KEYNAME_F16 : String;
	@:require(flash10_1) static var KEYNAME_F17 : String;
	@:require(flash10_1) static var KEYNAME_F18 : String;
	@:require(flash10_1) static var KEYNAME_F19 : String;
	@:require(flash10_1) static var KEYNAME_F2 : String;
	@:require(flash10_1) static var KEYNAME_F20 : String;
	@:require(flash10_1) static var KEYNAME_F21 : String;
	@:require(flash10_1) static var KEYNAME_F22 : String;
	@:require(flash10_1) static var KEYNAME_F23 : String;
	@:require(flash10_1) static var KEYNAME_F24 : String;
	@:require(flash10_1) static var KEYNAME_F25 : String;
	@:require(flash10_1) static var KEYNAME_F26 : String;
	@:require(flash10_1) static var KEYNAME_F27 : String;
	@:require(flash10_1) static var KEYNAME_F28 : String;
	@:require(flash10_1) static var KEYNAME_F29 : String;
	@:require(flash10_1) static var KEYNAME_F3 : String;
	@:require(flash10_1) static var KEYNAME_F30 : String;
	@:require(flash10_1) static var KEYNAME_F31 : String;
	@:require(flash10_1) static var KEYNAME_F32 : String;
	@:require(flash10_1) static var KEYNAME_F33 : String;
	@:require(flash10_1) static var KEYNAME_F34 : String;
	@:require(flash10_1) static var KEYNAME_F35 : String;
	@:require(flash10_1) static var KEYNAME_F4 : String;
	@:require(flash10_1) static var KEYNAME_F5 : String;
	@:require(flash10_1) static var KEYNAME_F6 : String;
	@:require(flash10_1) static var KEYNAME_F7 : String;
	@:require(flash10_1) static var KEYNAME_F8 : String;
	@:require(flash10_1) static var KEYNAME_F9 : String;
	@:require(flash10_1) static var KEYNAME_FIND : String;
	@:require(flash10_1) static var KEYNAME_HELP : String;
	@:require(flash10_1) static var KEYNAME_HOME : String;
	@:require(flash10_1) static var KEYNAME_INSERT : String;
	@:require(flash10_1) static var KEYNAME_INSERTCHAR : String;
	@:require(flash10_1) static var KEYNAME_INSERTLINE : String;
	@:require(flash10_1) static var KEYNAME_LEFTARROW : String;
	@:require(flash10_1) static var KEYNAME_MENU : String;
	@:require(flash10_1) static var KEYNAME_MODESWITCH : String;
	@:require(flash10_1) static var KEYNAME_NEXT : String;
	@:require(flash10_1) static var KEYNAME_PAGEDOWN : String;
	@:require(flash10_1) static var KEYNAME_PAGEUP : String;
	@:require(flash10_1) static var KEYNAME_PAUSE : String;
	@:require(flash10_1) static var KEYNAME_PREV : String;
	@:require(flash10_1) static var KEYNAME_PRINT : String;
	@:require(flash10_1) static var KEYNAME_PRINTSCREEN : String;
	@:require(flash10_1) static var KEYNAME_REDO : String;
	@:require(flash10_1) static var KEYNAME_RESET : String;
	@:require(flash10_1) static var KEYNAME_RIGHTARROW : String;
	@:require(flash10_1) static var KEYNAME_SCROLLLOCK : String;
	@:require(flash10_1) static var KEYNAME_SELECT : String;
	@:require(flash10_1) static var KEYNAME_STOP : String;
	@:require(flash10_1) static var KEYNAME_SYSREQ : String;
	@:require(flash10_1) static var KEYNAME_SYSTEM : String;
	@:require(flash10_1) static var KEYNAME_UNDO : String;
	@:require(flash10_1) static var KEYNAME_UPARROW : String;
	@:require(flash10_1) static var KEYNAME_USER : String;
	@:require(flash10_1) static var L : UInt;
	static var LEFT : UInt;
	@:require(flash10_1) static var LEFTBRACKET : UInt;
	@:require(flash10_1) static var M : UInt;
	@:require(flash10_1) static var MINUS : UInt;
	@:require(flash10_1) static var N : UInt;
	@:require(flash10_1) static var NUMBER_0 : UInt;
	@:require(flash10_1) static var NUMBER_1 : UInt;
	@:require(flash10_1) static var NUMBER_2 : UInt;
	@:require(flash10_1) static var NUMBER_3 : UInt;
	@:require(flash10_1) static var NUMBER_4 : UInt;
	@:require(flash10_1) static var NUMBER_5 : UInt;
	@:require(flash10_1) static var NUMBER_6 : UInt;
	@:require(flash10_1) static var NUMBER_7 : UInt;
	@:require(flash10_1) static var NUMBER_8 : UInt;
	@:require(flash10_1) static var NUMBER_9 : UInt;
	@:require(flash10_1) static var NUMPAD : UInt;
	static var NUMPAD_0 : UInt;
	static var NUMPAD_1 : UInt;
	static var NUMPAD_2 : UInt;
	static var NUMPAD_3 : UInt;
	static var NUMPAD_4 : UInt;
	static var NUMPAD_5 : UInt;
	static var NUMPAD_6 : UInt;
	static var NUMPAD_7 : UInt;
	static var NUMPAD_8 : UInt;
	static var NUMPAD_9 : UInt;
	static var NUMPAD_ADD : UInt;
	static var NUMPAD_DECIMAL : UInt;
	static var NUMPAD_DIVIDE : UInt;
	static var NUMPAD_ENTER : UInt;
	static var NUMPAD_MULTIPLY : UInt;
	static var NUMPAD_SUBTRACT : UInt;
	@:require(flash10_1) static var O : UInt;
	@:require(flash10_1) static var P : UInt;
	static var PAGE_DOWN : UInt;
	static var PAGE_UP : UInt;
	@:require(flash10_1) static var PERIOD : UInt;
	@:require(flash10_1) static var Q : UInt;
	@:require(flash10_1) static var QUOTE : UInt;
	@:require(flash10_1) static var R : UInt;
	static var RIGHT : UInt;
	@:require(flash10_1) static var RIGHTBRACKET : UInt;
	@:require(flash10_1) static var S : UInt;
	@:require(flash10_1) static var SEMICOLON : UInt;
	static var SHIFT : UInt;
	@:require(flash10_1) static var SLASH : UInt;
	static var SPACE : UInt;
	@:require(flash10_1) static var STRING_BEGIN : String;
	@:require(flash10_1) static var STRING_BREAK : String;
	@:require(flash10_1) static var STRING_CLEARDISPLAY : String;
	@:require(flash10_1) static var STRING_CLEARLINE : String;
	@:require(flash10_1) static var STRING_DELETE : String;
	@:require(flash10_1) static var STRING_DELETECHAR : String;
	@:require(flash10_1) static var STRING_DELETELINE : String;
	@:require(flash10_1) static var STRING_DOWNARROW : String;
	@:require(flash10_1) static var STRING_END : String;
	@:require(flash10_1) static var STRING_EXECUTE : String;
	@:require(flash10_1) static var STRING_F1 : String;
	@:require(flash10_1) static var STRING_F10 : String;
	@:require(flash10_1) static var STRING_F11 : String;
	@:require(flash10_1) static var STRING_F12 : String;
	@:require(flash10_1) static var STRING_F13 : String;
	@:require(flash10_1) static var STRING_F14 : String;
	@:require(flash10_1) static var STRING_F15 : String;
	@:require(flash10_1) static var STRING_F16 : String;
	@:require(flash10_1) static var STRING_F17 : String;
	@:require(flash10_1) static var STRING_F18 : String;
	@:require(flash10_1) static var STRING_F19 : String;
	@:require(flash10_1) static var STRING_F2 : String;
	@:require(flash10_1) static var STRING_F20 : String;
	@:require(flash10_1) static var STRING_F21 : String;
	@:require(flash10_1) static var STRING_F22 : String;
	@:require(flash10_1) static var STRING_F23 : String;
	@:require(flash10_1) static var STRING_F24 : String;
	@:require(flash10_1) static var STRING_F25 : String;
	@:require(flash10_1) static var STRING_F26 : String;
	@:require(flash10_1) static var STRING_F27 : String;
	@:require(flash10_1) static var STRING_F28 : String;
	@:require(flash10_1) static var STRING_F29 : String;
	@:require(flash10_1) static var STRING_F3 : String;
	@:require(flash10_1) static var STRING_F30 : String;
	@:require(flash10_1) static var STRING_F31 : String;
	@:require(flash10_1) static var STRING_F32 : String;
	@:require(flash10_1) static var STRING_F33 : String;
	@:require(flash10_1) static var STRING_F34 : String;
	@:require(flash10_1) static var STRING_F35 : String;
	@:require(flash10_1) static var STRING_F4 : String;
	@:require(flash10_1) static var STRING_F5 : String;
	@:require(flash10_1) static var STRING_F6 : String;
	@:require(flash10_1) static var STRING_F7 : String;
	@:require(flash10_1) static var STRING_F8 : String;
	@:require(flash10_1) static var STRING_F9 : String;
	@:require(flash10_1) static var STRING_FIND : String;
	@:require(flash10_1) static var STRING_HELP : String;
	@:require(flash10_1) static var STRING_HOME : String;
	@:require(flash10_1) static var STRING_INSERT : String;
	@:require(flash10_1) static var STRING_INSERTCHAR : String;
	@:require(flash10_1) static var STRING_INSERTLINE : String;
	@:require(flash10_1) static var STRING_LEFTARROW : String;
	@:require(flash10_1) static var STRING_MENU : String;
	@:require(flash10_1) static var STRING_MODESWITCH : String;
	@:require(flash10_1) static var STRING_NEXT : String;
	@:require(flash10_1) static var STRING_PAGEDOWN : String;
	@:require(flash10_1) static var STRING_PAGEUP : String;
	@:require(flash10_1) static var STRING_PAUSE : String;
	@:require(flash10_1) static var STRING_PREV : String;
	@:require(flash10_1) static var STRING_PRINT : String;
	@:require(flash10_1) static var STRING_PRINTSCREEN : String;
	@:require(flash10_1) static var STRING_REDO : String;
	@:require(flash10_1) static var STRING_RESET : String;
	@:require(flash10_1) static var STRING_RIGHTARROW : String;
	@:require(flash10_1) static var STRING_SCROLLLOCK : String;
	@:require(flash10_1) static var STRING_SELECT : String;
	@:require(flash10_1) static var STRING_STOP : String;
	@:require(flash10_1) static var STRING_SYSREQ : String;
	@:require(flash10_1) static var STRING_SYSTEM : String;
	@:require(flash10_1) static var STRING_UNDO : String;
	@:require(flash10_1) static var STRING_UPARROW : String;
	@:require(flash10_1) static var STRING_USER : String;
	@:require(flash10_1) static var T : UInt;
	static var TAB : UInt;
	@:require(flash10_1) static var U : UInt;
	static var UP : UInt;
	@:require(flash10_1) static var V : UInt;
	@:require(flash10_1) static var W : UInt;
	@:require(flash10_1) static var X : UInt;
	@:require(flash10_1) static var Y : UInt;
	@:require(flash10_1) static var Z : UInt;
	static var capsLock(default,null) : Bool;
	@:require(flash10_1) static var hasVirtualKeyboard(default,null) : Bool;
	static var numLock(default,null) : Bool;
	@:require(flash10_1) static var physicalKeyboardType(default,null) : KeyboardType;
	static function isAccessible() : Bool;
}
