package flash.text;

extern class TextField extends flash.display.InteractiveObject {
	function new() : Void;
	var alwaysShowSelection : Bool;
	var antiAliasType : String;
	function appendText(newText : String) : Void;
	var autoSize : String;
	var background : Bool;
	var backgroundColor : UInt;
	var border : Bool;
	var borderColor : UInt;
	var bottomScrollV(default,null) : Int;
	var caretIndex(default,null) : Int;
	var condenseWhite : Bool;
	var defaultTextFormat : flash.text.TextFormat;
	var displayAsPassword : Bool;
	var embedFonts : Bool;
	function getCharBoundaries(charIndex : Int) : flash.geom.Rectangle;
	function getCharIndexAtPoint(x : Float, y : Float) : Int;
	function getFirstCharInParagraph(charIndex : Int) : Int;
	function getImageReference(id : String) : flash.display.DisplayObject;
	function getLineIndexAtPoint(x : Float, y : Float) : Int;
	function getLineIndexOfChar(charIndex : Int) : Int;
	function getLineLength(lineIndex : Int) : Int;
	function getLineMetrics(lineIndex : Int) : flash.text.TextLineMetrics;
	function getLineOffset(lineIndex : Int) : Int;
	function getLineText(lineIndex : Int) : String;
	function getParagraphLength(charIndex : Int) : Int;
	function getRawText() : String;
	function getTextFormat(?beginIndex : Int, ?endIndex : Int) : flash.text.TextFormat;
	function getTextRuns(?beginIndex : Int, ?endIndex : Int) : Array<Dynamic>;
	function getXMLText(?beginIndex : Int, ?endIndex : Int) : String;
	var gridFitType : String;
	var htmlText : String;
	function insertXMLText(beginIndex : Int, endIndex : Int, richText : String, ?pasting : Bool) : Void;
	var length(default,null) : Int;
	var maxChars : Int;
	var maxScrollH(default,null) : Int;
	var maxScrollV(default,null) : Int;
	var mouseWheelEnabled : Bool;
	var multiline : Bool;
	var numLines(default,null) : Int;
	function replaceSelectedText(value : String) : Void;
	function replaceText(beginIndex : Int, endIndex : Int, newText : String) : Void;
	var restrict : String;
	var scrollH : Int;
	var scrollV : Int;
	var selectable : Bool;
	var selectedText(default,null) : String;
	var selectionBeginIndex(default,null) : Int;
	var selectionEndIndex(default,null) : Int;
	function setSelection(beginIndex : Int, endIndex : Int) : Void;
	function setTextFormat(format : flash.text.TextFormat, ?beginIndex : Int, ?endIndex : Int) : Void;
	var sharpness : Float;
	var styleSheet : flash.text.StyleSheet;
	var text : String;
	var textColor : UInt;
	var textHeight(default,null) : Float;
	var textWidth(default,null) : Float;
	var thickness : Float;
	var type : String;
	var useRichTextClipboard : Bool;
	var wordWrap : Bool;
	//private function copyRichText() : String;
	//private function pasteRichText(richText : String) : Bool;
	//private static var richTextFields : Array<Dynamic>;
}
