package flash.text;

extern class TextField extends flash.display.InteractiveObject {
	var alwaysShowSelection : Bool;
	var antiAliasType : AntiAliasType;
	var autoSize : TextFieldAutoSize;
	var background : Bool;
	var backgroundColor : UInt;
	var border : Bool;
	var borderColor : UInt;
	var bottomScrollV(default,null) : Int;
	var caretIndex(default,null) : Int;
	var condenseWhite : Bool;
	var defaultTextFormat : TextFormat;
	var displayAsPassword : Bool;
	var embedFonts : Bool;
	var gridFitType : GridFitType;
	var htmlText : String;
	var length(default,null) : Int;
	var maxChars : Int;
	var maxScrollH(default,null) : Int;
	var maxScrollV(default,null) : Int;
	var mouseWheelEnabled : Bool;
	var multiline : Bool;
	var numLines(default,null) : Int;
	var restrict : String;
	var scrollH : Int;
	var scrollV : Int;
	var selectable : Bool;
	var selectedText(default,null) : String;
	var selectionBeginIndex(default,null) : Int;
	var selectionEndIndex(default,null) : Int;
	var sharpness : Float;
	var styleSheet : StyleSheet;
	var text : String;
	var textColor : UInt;
	var textHeight(default,null) : Float;
	var textWidth(default,null) : Float;
	var thickness : Float;
	var type : TextFieldType;
	var useRichTextClipboard : Bool;
	var wordWrap : Bool;
	function new() : Void;
	function appendText(newText : String) : Void;
	function getCharBoundaries(charIndex : Int) : flash.geom.Rectangle;
	function getCharIndexAtPoint(x : Float, y : Float) : Int;
	function getFirstCharInParagraph(charIndex : Int) : Int;
	function getImageReference(id : String) : flash.display.DisplayObject;
	function getLineIndexAtPoint(x : Float, y : Float) : Int;
	function getLineIndexOfChar(charIndex : Int) : Int;
	function getLineLength(lineIndex : Int) : Int;
	function getLineMetrics(lineIndex : Int) : TextLineMetrics;
	function getLineOffset(lineIndex : Int) : Int;
	function getLineText(lineIndex : Int) : String;
	function getParagraphLength(charIndex : Int) : Int;
	function getRawText() : String;
	function getTextFormat(?beginIndex : Int, ?endIndex : Int) : TextFormat;
	function getTextRuns(?beginIndex : Int, ?endIndex : Int) : Array<Dynamic>;
	function getXMLText(?beginIndex : Int, ?endIndex : Int) : String;
	function insertXMLText(beginIndex : Int, endIndex : Int, richText : String, ?pasting : Bool) : Void;
	function replaceSelectedText(value : String) : Void;
	function replaceText(beginIndex : Int, endIndex : Int, newText : String) : Void;
	function setSelection(beginIndex : Int, endIndex : Int) : Void;
	function setTextFormat(format : TextFormat, ?beginIndex : Int, ?endIndex : Int) : Void;
}
