package cs.system.runtime.interopservices;

/** Indicates how to marshal the array elements when an array is marshaled from managed to unmanaged code as a . */
@:native("System.Runtime.InteropServices.VarEnum")
extern enum VarEnum {
	VT_ARRAY;
	VT_BLOB;
	VT_BLOB_OBJECT;
	VT_BOOL;
	VT_BSTR;
	VT_BYREF;
	VT_CARRAY;
	VT_CF;
	VT_CLSID;
	VT_CY;
	VT_DATE;
	VT_DECIMAL;
	VT_DISPATCH;
	VT_EMPTY;
	VT_ERROR;
	VT_FILETIME;
	VT_HRESULT;
	VT_I1;
	VT_I2;
	VT_I4;
	VT_I8;
	VT_INT;
	VT_LPSTR;
	VT_LPWSTR;
	VT_NULL;
	VT_PTR;
	VT_R4;
	VT_R8;
	VT_RECORD;
	VT_SAFEARRAY;
	VT_STORAGE;
	VT_STORED_OBJECT;
	VT_STREAM;
	VT_STREAMED_OBJECT;
	VT_UI1;
	VT_UI2;
	VT_UI4;
	VT_UI8;
	VT_UINT;
	VT_UNKNOWN;
	VT_USERDEFINED;
	VT_VARIANT;
	VT_VECTOR;
	VT_VOID;
}
