name: Check pull request target branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-branches:
    if: github.repository == 'HaxeFoundation/haxe'
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        env:
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "$HEAD_REPO" != "HaxeFoundation/haxe" ] && [ "$BASE_REF" != "development" ]; then
            echo "Merge requests from forks should target development."
            exit 1
          fi

