// Generated by Haxe 5.0.0-preview.1
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Xml
#include <Xml.h>
#endif
#ifndef INCLUDED__Xml_XmlType_Impl_
#include <_Xml/XmlType_Impl_.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_xml_Parser
#include <haxe/xml/Parser.h>
#endif
#ifndef INCLUDED_haxe_xml_XmlParserException
#include <haxe/xml/XmlParserException.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_71bfcf6fd7e2750c_115_parse,"haxe.xml.Parser","parse",0x937905c3,"haxe.xml.Parser.parse","haxe/xml/Parser.hx",115,0xe10296be)
HX_LOCAL_STACK_FRAME(_hx_pos_71bfcf6fd7e2750c_121_doParse,"haxe.xml.Parser","doParse",0x2e9a6a38,"haxe.xml.Parser.doParse","haxe/xml/Parser.hx",121,0xe10296be)
HX_LOCAL_STACK_FRAME(_hx_pos_71bfcf6fd7e2750c_418_isValidChar,"haxe.xml.Parser","isValidChar",0x52d1e638,"haxe.xml.Parser.isValidChar","haxe/xml/Parser.hx",418,0xe10296be)
HX_LOCAL_STACK_FRAME(_hx_pos_71bfcf6fd7e2750c_100_boot,"haxe.xml.Parser","boot",0x0af6f0a2,"haxe.xml.Parser.boot","haxe/xml/Parser.hx",100,0xe10296be)

namespace {

struct __Parser_objparse final : public ::hx::AutoCallable_obj<  ::Xml (::String, ::Dynamic) > {
	__Parser_objparse() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Parser_objparse*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	 ::Xml HX_LOCAL_RUN(::String str, ::Dynamic strict) override {
		return haxe::xml::Parser_obj::parse(str, strict);
	}
};

::hx::Callable<  ::Xml (::String, ::Dynamic) > _hx_alloc__Parser_objparse;

struct __Parser_objdoParse final : public ::hx::AutoCallable_obj< int (::String,bool, ::Dynamic, ::Xml) > {
	__Parser_objdoParse() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Parser_objdoParse*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	int HX_LOCAL_RUN(::String str,bool strict, ::Dynamic p, ::Xml parent) override {
		return haxe::xml::Parser_obj::doParse(str, strict, p, parent);
	}
};

::hx::Callable< int (::String,bool, ::Dynamic, ::Xml) > _hx_alloc__Parser_objdoParse;

struct __Parser_objisValidChar final : public ::hx::AutoCallable_obj< bool (int) > {
	__Parser_objisValidChar() {} 
	int __Compare(const ::hx::Object* inRhs) const override {
		auto casted = dynamic_cast<const __Parser_objisValidChar*>(inRhs);
		if (!casted) { return -1; }
		return 0;
	}
	bool HX_LOCAL_RUN(int c) override {
		return haxe::xml::Parser_obj::isValidChar(c);
	}
};

::hx::Callable< bool (int) > _hx_alloc__Parser_objisValidChar;

}

namespace haxe{
namespace xml{

void Parser_obj::__construct() { }

::Dynamic Parser_obj::__CreateEmpty() { return new Parser_obj; }

void* Parser_obj::_hx_vtable = 0;

::Dynamic Parser_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Parser_obj > _hx_result = new Parser_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Parser_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x1c6f1730;
}

 ::Xml Parser_obj::parse(::String str, ::Dynamic __o_strict){
            		 ::Dynamic strict = __o_strict;
            		if (::hx::IsNull(__o_strict)) strict = false;
            	HX_STACKFRAME(&_hx_pos_71bfcf6fd7e2750c_115_parse)
HXLINE( 116)		 ::Xml doc = ::Xml_obj::createDocument();
HXLINE( 117)		::haxe::xml::Parser_obj::doParse(str,( (bool)(strict) ),0,doc);
HXLINE( 118)		return doc;
            	}


::hx::Callable<  ::Xml (::String, ::Dynamic) > Parser_obj::parse_dyn() { return _hx_alloc__Parser_objparse; }

int Parser_obj::doParse(::String str,bool strict, ::Dynamic __o_p, ::Xml parent){
            		 ::Dynamic p = __o_p;
            		if (::hx::IsNull(__o_p)) p = 0;
            	HX_GC_STACKFRAME(&_hx_pos_71bfcf6fd7e2750c_121_doParse)
HXLINE( 122)		 ::Xml xml = null();
HXLINE( 123)		int state = 1;
HXLINE( 124)		int next = 1;
HXLINE( 125)		::String aname = null();
HXLINE( 126)		int start = 0;
HXLINE( 127)		int nsubs = 0;
HXLINE( 128)		int nbrackets = 0;
HXLINE( 129)		 ::StringBuf buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 131)		int escapeNext = 1;
HXLINE( 132)		int attrValQuote = -1;
HXLINE( 137)		while((( (int)(p) ) < str.length)){
HXLINE( 138)			int c = str.cca(( (int)(p) ));
HXLINE( 139)			switch((int)(state)){
            				case (int)0: {
HXLINE( 141)					switch((int)(c)){
            						case (int)9: case (int)10: case (int)13: case (int)32: {
            						}
            						break;
            						default:{
HXLINE( 144)							state = next;
HXLINE( 145)							continue;
            						}
            					}
            				}
            				break;
            				case (int)1: {
HXLINE( 148)					if ((c == 60)) {
HXLINE( 150)						state = 0;
HXLINE( 151)						next = 2;
            					}
            					else {
HXLINE( 153)						start = ( (int)(p) );
HXLINE( 154)						state = 13;
HXLINE( 155)						continue;
            					}
            				}
            				break;
            				case (int)2: {
HXLINE( 179)					switch((int)(c)){
            						case (int)33: {
HXLINE( 181)							if ((str.cca((( (int)(p) ) + 1)) == 91)) {
HXLINE( 182)								::hx::AddEq(p,2);
HXLINE( 183)								if ((str.substr(( (int)(p) ),6).toUpperCase() != HX_("CDATA[",ce,73,5f,1c))) {
HXLINE( 184)									HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected <![CDATA[",1c,11,1f,2d),str,( (int)(p) ))));
            								}
HXLINE( 185)								::hx::AddEq(p,5);
HXLINE( 186)								state = 17;
HXLINE( 187)								start = (( (int)(p) ) + 1);
            							}
            							else {
HXLINE( 188)								bool _hx_tmp;
HXDLIN( 188)								if ((str.cca((( (int)(p) ) + 1)) != 68)) {
HXLINE( 188)									_hx_tmp = (str.cca((( (int)(p) ) + 1)) == 100);
            								}
            								else {
HXLINE( 188)									_hx_tmp = true;
            								}
HXDLIN( 188)								if (_hx_tmp) {
HXLINE( 189)									if ((str.substr((( (int)(p) ) + 2),6).toUpperCase() != HX_("OCTYPE",ce,19,d4,61))) {
HXLINE( 190)										HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected <!DOCTYPE",c5,0b,26,b6),str,( (int)(p) ))));
            									}
HXLINE( 191)									::hx::AddEq(p,8);
HXLINE( 192)									state = 16;
HXLINE( 193)									start = (( (int)(p) ) + 1);
            								}
            								else {
HXLINE( 194)									bool _hx_tmp1;
HXDLIN( 194)									if ((str.cca((( (int)(p) ) + 1)) == 45)) {
HXLINE( 194)										_hx_tmp1 = (str.cca((( (int)(p) ) + 2)) != 45);
            									}
            									else {
HXLINE( 194)										_hx_tmp1 = true;
            									}
HXDLIN( 194)									if (_hx_tmp1) {
HXLINE( 194)										HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected <!--",8d,3d,c1,53),str,( (int)(p) ))));
            									}
            									else {
HXLINE( 196)										::hx::AddEq(p,2);
HXLINE( 197)										state = 15;
HXLINE( 198)										start = (( (int)(p) ) + 1);
            									}
            								}
            							}
            						}
            						break;
            						case (int)47: {
HXLINE( 204)							if (::hx::IsNull( parent )) {
HXLINE( 205)								HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected node name",a1,85,63,3f),str,( (int)(p) ))));
            							}
HXLINE( 206)							start = (( (int)(p) ) + 1);
HXLINE( 207)							state = 0;
HXLINE( 208)							next = 10;
            						}
            						break;
            						case (int)63: {
HXLINE( 201)							state = 14;
HXLINE( 202)							start = ( (int)(p) );
            						}
            						break;
            						default:{
HXLINE( 210)							state = 3;
HXLINE( 211)							start = ( (int)(p) );
HXLINE( 212)							continue;
            						}
            					}
            				}
            				break;
            				case (int)3: {
HXLINE( 215)					bool _hx_tmp2;
HXDLIN( 215)					bool _hx_tmp3;
HXDLIN( 215)					bool _hx_tmp4;
HXDLIN( 215)					bool _hx_tmp5;
HXDLIN( 215)					bool _hx_tmp6;
HXDLIN( 215)					bool _hx_tmp7;
HXDLIN( 215)					bool _hx_tmp8;
HXDLIN( 215)					if ((c >= 97)) {
HXLINE( 215)						_hx_tmp8 = (c <= 122);
            					}
            					else {
HXLINE( 215)						_hx_tmp8 = false;
            					}
HXDLIN( 215)					if (!(_hx_tmp8)) {
HXLINE( 215)						if ((c >= 65)) {
HXLINE( 215)							_hx_tmp7 = (c <= 90);
            						}
            						else {
HXLINE( 215)							_hx_tmp7 = false;
            						}
            					}
            					else {
HXLINE( 215)						_hx_tmp7 = true;
            					}
HXDLIN( 215)					if (!(_hx_tmp7)) {
HXLINE( 215)						if ((c >= 48)) {
HXLINE( 215)							_hx_tmp6 = (c <= 57);
            						}
            						else {
HXLINE( 215)							_hx_tmp6 = false;
            						}
            					}
            					else {
HXLINE( 215)						_hx_tmp6 = true;
            					}
HXDLIN( 215)					if (!(_hx_tmp6)) {
HXLINE( 215)						_hx_tmp5 = (c == 58);
            					}
            					else {
HXLINE( 215)						_hx_tmp5 = true;
            					}
HXDLIN( 215)					if (!(_hx_tmp5)) {
HXLINE( 215)						_hx_tmp4 = (c == 46);
            					}
            					else {
HXLINE( 215)						_hx_tmp4 = true;
            					}
HXDLIN( 215)					if (!(_hx_tmp4)) {
HXLINE( 215)						_hx_tmp3 = (c == 95);
            					}
            					else {
HXLINE( 215)						_hx_tmp3 = true;
            					}
HXDLIN( 215)					if (!(_hx_tmp3)) {
HXLINE( 215)						_hx_tmp2 = (c == 45);
            					}
            					else {
HXLINE( 215)						_hx_tmp2 = true;
            					}
HXDLIN( 215)					if (!(_hx_tmp2)) {
HXLINE( 216)						if ((( (int)(p) ) == start)) {
HXLINE( 217)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected node name",a1,85,63,3f),str,( (int)(p) ))));
            						}
HXLINE( 218)						xml = ::Xml_obj::createElement(str.substr(start,(( (int)(p) ) - start)));
HXLINE( 219)						{
HXLINE( 219)							parent->addChild(xml);
HXDLIN( 219)							++nsubs;
            						}
HXLINE( 220)						state = 0;
HXLINE( 221)						next = 4;
HXLINE( 222)						continue;
            					}
            				}
            				break;
            				case (int)4: {
HXLINE( 225)					switch((int)(c)){
            						case (int)47: {
HXLINE( 227)							state = 11;
            						}
            						break;
            						case (int)62: {
HXLINE( 229)							state = 9;
            						}
            						break;
            						default:{
HXLINE( 231)							state = 5;
HXLINE( 232)							start = ( (int)(p) );
HXLINE( 233)							continue;
            						}
            					}
            				}
            				break;
            				case (int)5: {
HXLINE( 236)					bool _hx_tmp9;
HXDLIN( 236)					bool _hx_tmp10;
HXDLIN( 236)					bool _hx_tmp11;
HXDLIN( 236)					bool _hx_tmp12;
HXDLIN( 236)					bool _hx_tmp13;
HXDLIN( 236)					bool _hx_tmp14;
HXDLIN( 236)					bool _hx_tmp15;
HXDLIN( 236)					if ((c >= 97)) {
HXLINE( 236)						_hx_tmp15 = (c <= 122);
            					}
            					else {
HXLINE( 236)						_hx_tmp15 = false;
            					}
HXDLIN( 236)					if (!(_hx_tmp15)) {
HXLINE( 236)						if ((c >= 65)) {
HXLINE( 236)							_hx_tmp14 = (c <= 90);
            						}
            						else {
HXLINE( 236)							_hx_tmp14 = false;
            						}
            					}
            					else {
HXLINE( 236)						_hx_tmp14 = true;
            					}
HXDLIN( 236)					if (!(_hx_tmp14)) {
HXLINE( 236)						if ((c >= 48)) {
HXLINE( 236)							_hx_tmp13 = (c <= 57);
            						}
            						else {
HXLINE( 236)							_hx_tmp13 = false;
            						}
            					}
            					else {
HXLINE( 236)						_hx_tmp13 = true;
            					}
HXDLIN( 236)					if (!(_hx_tmp13)) {
HXLINE( 236)						_hx_tmp12 = (c == 58);
            					}
            					else {
HXLINE( 236)						_hx_tmp12 = true;
            					}
HXDLIN( 236)					if (!(_hx_tmp12)) {
HXLINE( 236)						_hx_tmp11 = (c == 46);
            					}
            					else {
HXLINE( 236)						_hx_tmp11 = true;
            					}
HXDLIN( 236)					if (!(_hx_tmp11)) {
HXLINE( 236)						_hx_tmp10 = (c == 95);
            					}
            					else {
HXLINE( 236)						_hx_tmp10 = true;
            					}
HXDLIN( 236)					if (!(_hx_tmp10)) {
HXLINE( 236)						_hx_tmp9 = (c == 45);
            					}
            					else {
HXLINE( 236)						_hx_tmp9 = true;
            					}
HXDLIN( 236)					if (!(_hx_tmp9)) {
HXLINE( 238)						if ((start == ( (int)(p) ))) {
HXLINE( 239)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected attribute name",57,65,2b,54),str,( (int)(p) ))));
            						}
HXLINE( 237)						::String tmp = str.substr(start,(( (int)(p) ) - start));
HXLINE( 241)						aname = tmp;
HXLINE( 242)						if (xml->exists(aname)) {
HXLINE( 243)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,((HX_("Duplicate attribute [",22,75,cb,05) + aname) + HX_("]",5d,00,00,00)),str,( (int)(p) ))));
            						}
HXLINE( 244)						state = 0;
HXLINE( 245)						next = 6;
HXLINE( 246)						continue;
            					}
            				}
            				break;
            				case (int)6: {
HXLINE( 249)					if ((c == 61)) {
HXLINE( 251)						state = 0;
HXLINE( 252)						next = 7;
            					}
            					else {
HXLINE( 254)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected =",b5,dc,23,c6),str,( (int)(p) ))));
            					}
            				}
            				break;
            				case (int)7: {
HXLINE( 257)					switch((int)(c)){
            						case (int)34: case (int)39: {
HXLINE( 259)							buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 260)							state = 8;
HXLINE( 261)							start = (( (int)(p) ) + 1);
HXLINE( 262)							attrValQuote = c;
            						}
            						break;
            						default:{
HXLINE( 264)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected \"",9a,dc,23,c6),str,( (int)(p) ))));
            						}
            					}
            				}
            				break;
            				case (int)8: {
HXLINE( 267)					switch((int)(c)){
            						case (int)38: {
HXLINE( 269)							{
HXLINE( 269)								 ::Dynamic len = (( (int)(p) ) - start);
HXDLIN( 269)								if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 269)									buf->flush();
            								}
HXDLIN( 269)								if (::hx::IsNull( buf->b )) {
HXLINE( 269)									buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len));
            								}
            								else {
HXLINE( 269)									::Array< ::String > buf1 = buf->b;
HXDLIN( 269)									buf1->push(str.substr(start,len));
            								}
            							}
HXLINE( 270)							state = 18;
HXLINE( 271)							escapeNext = 8;
HXLINE( 272)							start = (( (int)(p) ) + 1);
            						}
            						break;
            						case (int)60: case (int)62: {
HXLINE( 273)							if (strict) {
HXLINE( 275)								HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,((HX_("Invalid unescaped ",ff,da,cb,cc) + ::String::fromCharCode(c)) + HX_(" in attribute value",52,5a,ca,13)),str,( (int)(p) ))));
            							}
            							else {
HXLINE( 276)								if ((c == attrValQuote)) {
HXLINE( 277)									{
HXLINE( 277)										 ::Dynamic len1 = (( (int)(p) ) - start);
HXDLIN( 277)										if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 277)											buf->flush();
            										}
HXDLIN( 277)										if (::hx::IsNull( buf->b )) {
HXLINE( 277)											buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len1));
            										}
            										else {
HXLINE( 277)											::Array< ::String > buf2 = buf->b;
HXDLIN( 277)											buf2->push(str.substr(start,len1));
            										}
            									}
HXLINE( 278)									::String val = buf->toString();
HXLINE( 279)									buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 280)									xml->set(aname,val);
HXLINE( 281)									state = 0;
HXLINE( 282)									next = 4;
            								}
            							}
            						}
            						break;
            						default:{
HXLINE( 276)							if ((c == attrValQuote)) {
HXLINE( 277)								{
HXLINE( 277)									 ::Dynamic len2 = (( (int)(p) ) - start);
HXDLIN( 277)									if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 277)										buf->flush();
            									}
HXDLIN( 277)									if (::hx::IsNull( buf->b )) {
HXLINE( 277)										buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len2));
            									}
            									else {
HXLINE( 277)										::Array< ::String > buf3 = buf->b;
HXDLIN( 277)										buf3->push(str.substr(start,len2));
            									}
            								}
HXLINE( 278)								::String val1 = buf->toString();
HXLINE( 279)								buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 280)								xml->set(aname,val1);
HXLINE( 281)								state = 0;
HXLINE( 282)								next = 4;
            							}
            						}
            					}
            				}
            				break;
            				case (int)9: {
HXLINE( 285)					p = ::haxe::xml::Parser_obj::doParse(str,strict,p,xml);
HXLINE( 286)					start = ( (int)(p) );
HXLINE( 287)					state = 1;
            				}
            				break;
            				case (int)10: {
HXLINE( 305)					bool _hx_tmp16;
HXDLIN( 305)					bool _hx_tmp17;
HXDLIN( 305)					bool _hx_tmp18;
HXDLIN( 305)					bool _hx_tmp19;
HXDLIN( 305)					bool _hx_tmp20;
HXDLIN( 305)					bool _hx_tmp21;
HXDLIN( 305)					bool _hx_tmp22;
HXDLIN( 305)					if ((c >= 97)) {
HXLINE( 305)						_hx_tmp22 = (c <= 122);
            					}
            					else {
HXLINE( 305)						_hx_tmp22 = false;
            					}
HXDLIN( 305)					if (!(_hx_tmp22)) {
HXLINE( 305)						if ((c >= 65)) {
HXLINE( 305)							_hx_tmp21 = (c <= 90);
            						}
            						else {
HXLINE( 305)							_hx_tmp21 = false;
            						}
            					}
            					else {
HXLINE( 305)						_hx_tmp21 = true;
            					}
HXDLIN( 305)					if (!(_hx_tmp21)) {
HXLINE( 305)						if ((c >= 48)) {
HXLINE( 305)							_hx_tmp20 = (c <= 57);
            						}
            						else {
HXLINE( 305)							_hx_tmp20 = false;
            						}
            					}
            					else {
HXLINE( 305)						_hx_tmp20 = true;
            					}
HXDLIN( 305)					if (!(_hx_tmp20)) {
HXLINE( 305)						_hx_tmp19 = (c == 58);
            					}
            					else {
HXLINE( 305)						_hx_tmp19 = true;
            					}
HXDLIN( 305)					if (!(_hx_tmp19)) {
HXLINE( 305)						_hx_tmp18 = (c == 46);
            					}
            					else {
HXLINE( 305)						_hx_tmp18 = true;
            					}
HXDLIN( 305)					if (!(_hx_tmp18)) {
HXLINE( 305)						_hx_tmp17 = (c == 95);
            					}
            					else {
HXLINE( 305)						_hx_tmp17 = true;
            					}
HXDLIN( 305)					if (!(_hx_tmp17)) {
HXLINE( 305)						_hx_tmp16 = (c == 45);
            					}
            					else {
HXLINE( 305)						_hx_tmp16 = true;
            					}
HXDLIN( 305)					if (!(_hx_tmp16)) {
HXLINE( 306)						if ((start == ( (int)(p) ))) {
HXLINE( 307)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected node name",a1,85,63,3f),str,( (int)(p) ))));
            						}
HXLINE( 309)						::String v = str.substr(start,(( (int)(p) ) - start));
HXLINE( 310)						bool _hx_tmp23;
HXDLIN( 310)						if (::hx::IsNotNull( parent )) {
HXLINE( 310)							_hx_tmp23 = (parent->nodeType != 0);
            						}
            						else {
HXLINE( 310)							_hx_tmp23 = true;
            						}
HXDLIN( 310)						if (_hx_tmp23) {
HXLINE( 311)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,((HX_("Unexpected </",42,6f,35,1e) + v) + HX_(">, tag is not open",35,30,75,b8)),str,( (int)(p) ))));
            						}
HXLINE( 313)						if ((parent->nodeType != ::Xml_obj::Element)) {
HXLINE( 313)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(parent->nodeType))));
            						}
HXDLIN( 313)						if ((v != parent->nodeName)) {
HXLINE( 314)							if ((parent->nodeType != ::Xml_obj::Element)) {
HXLINE( 314)								HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(parent->nodeType))));
            							}
HXDLIN( 314)							HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,((HX_("Expected </",fb,40,3d,99) + parent->nodeName) + HX_(">",3e,00,00,00)),str,( (int)(p) ))));
            						}
HXLINE( 316)						state = 0;
HXLINE( 317)						next = 12;
HXLINE( 318)						continue;
            					}
            				}
            				break;
            				case (int)11: {
HXLINE( 289)					if ((c == 62)) {
HXLINE( 291)						state = 1;
            					}
            					else {
HXLINE( 293)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected >",b6,dc,23,c6),str,( (int)(p) ))));
            					}
            				}
            				break;
            				case (int)12: {
HXLINE( 296)					if ((c == 62)) {
HXLINE( 298)						if ((nsubs == 0)) {
HXLINE( 299)							parent->addChild(::Xml_obj::createPCData(HX_("",00,00,00,00)));
            						}
HXLINE( 300)						return ( (int)(p) );
            					}
            					else {
HXLINE( 302)						HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Expected >",b6,dc,23,c6),str,( (int)(p) ))));
            					}
            				}
            				break;
            				case (int)13: {
HXLINE( 158)					if ((c == 60)) {
HXLINE( 159)						{
HXLINE( 159)							 ::Dynamic len3 = (( (int)(p) ) - start);
HXDLIN( 159)							if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 159)								buf->flush();
            							}
HXDLIN( 159)							if (::hx::IsNull( buf->b )) {
HXLINE( 159)								buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len3));
            							}
            							else {
HXLINE( 159)								::Array< ::String > buf4 = buf->b;
HXDLIN( 159)								buf4->push(str.substr(start,len3));
            							}
            						}
HXLINE( 160)						 ::Xml child = ::Xml_obj::createPCData(buf->toString());
HXLINE( 161)						buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 162)						{
HXLINE( 162)							parent->addChild(child);
HXDLIN( 162)							++nsubs;
            						}
HXLINE( 163)						state = 0;
HXLINE( 164)						next = 2;
            					}
            					else {
HXLINE( 165)						if ((c == 38)) {
HXLINE( 166)							{
HXLINE( 166)								 ::Dynamic len4 = (( (int)(p) ) - start);
HXDLIN( 166)								if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 166)									buf->flush();
            								}
HXDLIN( 166)								if (::hx::IsNull( buf->b )) {
HXLINE( 166)									buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len4));
            								}
            								else {
HXLINE( 166)									::Array< ::String > buf5 = buf->b;
HXDLIN( 166)									buf5->push(str.substr(start,len4));
            								}
            							}
HXLINE( 167)							state = 18;
HXLINE( 168)							escapeNext = 13;
HXLINE( 169)							start = (( (int)(p) ) + 1);
            						}
            					}
            				}
            				break;
            				case (int)14: {
HXLINE( 336)					bool _hx_tmp24;
HXDLIN( 336)					if ((c == 63)) {
HXLINE( 336)						_hx_tmp24 = (str.cca((( (int)(p) ) + 1)) == 62);
            					}
            					else {
HXLINE( 336)						_hx_tmp24 = false;
            					}
HXDLIN( 336)					if (_hx_tmp24) {
HXLINE( 337)						++p;
HXLINE( 338)						::String str1 = str.substr((start + 1),((( (int)(p) ) - start) - 2));
HXLINE( 339)						{
HXLINE( 339)							parent->addChild(::Xml_obj::createProcessingInstruction(str1));
HXDLIN( 339)							++nsubs;
            						}
HXLINE( 340)						state = 1;
            					}
            				}
            				break;
            				case (int)15: {
HXLINE( 321)					bool _hx_tmp25;
HXDLIN( 321)					bool _hx_tmp26;
HXDLIN( 321)					if ((c == 45)) {
HXLINE( 321)						_hx_tmp26 = (str.cca((( (int)(p) ) + 1)) == 45);
            					}
            					else {
HXLINE( 321)						_hx_tmp26 = false;
            					}
HXDLIN( 321)					if (_hx_tmp26) {
HXLINE( 321)						_hx_tmp25 = (str.cca((( (int)(p) ) + 2)) == 62);
            					}
            					else {
HXLINE( 321)						_hx_tmp25 = false;
            					}
HXDLIN( 321)					if (_hx_tmp25) {
HXLINE( 322)						{
HXLINE( 322)							parent->addChild(::Xml_obj::createComment(str.substr(start,(( (int)(p) ) - start))));
HXDLIN( 322)							++nsubs;
            						}
HXLINE( 323)						::hx::AddEq(p,2);
HXLINE( 324)						state = 1;
            					}
            				}
            				break;
            				case (int)16: {
HXLINE( 327)					if ((c == 91)) {
HXLINE( 328)						++nbrackets;
            					}
            					else {
HXLINE( 329)						if ((c == 93)) {
HXLINE( 330)							--nbrackets;
            						}
            						else {
HXLINE( 331)							bool _hx_tmp27;
HXDLIN( 331)							if ((c == 62)) {
HXLINE( 331)								_hx_tmp27 = (nbrackets == 0);
            							}
            							else {
HXLINE( 331)								_hx_tmp27 = false;
            							}
HXDLIN( 331)							if (_hx_tmp27) {
HXLINE( 332)								{
HXLINE( 332)									parent->addChild(::Xml_obj::createDocType(str.substr(start,(( (int)(p) ) - start))));
HXDLIN( 332)									++nsubs;
            								}
HXLINE( 333)								state = 1;
            							}
            						}
            					}
            				}
            				break;
            				case (int)17: {
HXLINE( 172)					bool _hx_tmp28;
HXDLIN( 172)					bool _hx_tmp29;
HXDLIN( 172)					if ((c == 93)) {
HXLINE( 172)						_hx_tmp29 = (str.cca((( (int)(p) ) + 1)) == 93);
            					}
            					else {
HXLINE( 172)						_hx_tmp29 = false;
            					}
HXDLIN( 172)					if (_hx_tmp29) {
HXLINE( 172)						_hx_tmp28 = (str.cca((( (int)(p) ) + 2)) == 62);
            					}
            					else {
HXLINE( 172)						_hx_tmp28 = false;
            					}
HXDLIN( 172)					if (_hx_tmp28) {
HXLINE( 173)						 ::Xml child1 = ::Xml_obj::createCData(str.substr(start,(( (int)(p) ) - start)));
HXLINE( 174)						{
HXLINE( 174)							parent->addChild(child1);
HXDLIN( 174)							++nsubs;
            						}
HXLINE( 175)						::hx::AddEq(p,2);
HXLINE( 176)						state = 1;
            					}
            				}
            				break;
            				case (int)18: {
HXLINE( 343)					if ((c == 59)) {
HXLINE( 344)						::String s = str.substr(start,(( (int)(p) ) - start)).toLowerCase();
HXLINE( 345)						if ((s.cca(0) == 35)) {
HXLINE( 346)							 ::Dynamic c1;
HXDLIN( 346)							if ((s.cca(1) == 120)) {
HXLINE( 346)								c1 = ::Std_obj::parseInt((HX_("0",30,00,00,00) + s.substr(1,(s.length - 1))));
            							}
            							else {
HXLINE( 346)								c1 = ::Std_obj::parseInt(s.substr(1,(s.length - 1)));
            							}
HXLINE( 366)							{
HXLINE( 366)								int c2 = ( (int)(c1) );
HXDLIN( 366)								if ((c2 >= 127)) {
HXLINE( 366)									::String x = ::String::fromCharCode(c2);
HXDLIN( 366)									if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 366)										buf->flush();
            									}
HXDLIN( 366)									if (::hx::IsNull( buf->b )) {
HXLINE( 366)										buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            									}
            									else {
HXLINE( 366)										::Array< ::String > buf6 = buf->b;
HXDLIN( 366)										buf6->push(::Std_obj::string(x));
            									}
            								}
            								else {
HXLINE( 366)									if (::hx::IsNull( buf->charBuf )) {
HXLINE( 366)										buf->charBuf = ::Array_obj< char >::__new();
            									}
HXDLIN( 366)									buf->charBuf->push(c2);
            								}
            							}
            						}
            						else {
HXLINE( 367)							if (!(::haxe::xml::Parser_obj::escapes->exists(s))) {
HXLINE( 368)								if (strict) {
HXLINE( 369)									HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,(HX_("Undefined entity: ",39,48,f2,48) + s),str,( (int)(p) ))));
            								}
HXLINE( 370)								{
HXLINE( 370)									::String x1 = ((HX_("&",26,00,00,00) + s) + HX_(";",3b,00,00,00));
HXDLIN( 370)									if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 370)										buf->flush();
            									}
HXDLIN( 370)									if (::hx::IsNull( buf->b )) {
HXLINE( 370)										buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x1));
            									}
            									else {
HXLINE( 370)										::Array< ::String > buf7 = buf->b;
HXDLIN( 370)										buf7->push(::Std_obj::string(x1));
            									}
            								}
            							}
            							else {
HXLINE( 372)								::String x2 = ::haxe::xml::Parser_obj::escapes->get_string(s);
HXDLIN( 372)								if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 372)									buf->flush();
            								}
HXDLIN( 372)								if (::hx::IsNull( buf->b )) {
HXLINE( 372)									buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x2));
            								}
            								else {
HXLINE( 372)									::Array< ::String > buf8 = buf->b;
HXDLIN( 372)									buf8->push(::Std_obj::string(x2));
            								}
            							}
            						}
HXLINE( 374)						start = (( (int)(p) ) + 1);
HXLINE( 375)						state = escapeNext;
            					}
            					else {
HXLINE( 376)						bool _hx_tmp30;
HXDLIN( 376)						bool _hx_tmp31;
HXDLIN( 376)						bool _hx_tmp32;
HXDLIN( 376)						bool _hx_tmp33;
HXDLIN( 376)						bool _hx_tmp34;
HXDLIN( 376)						bool _hx_tmp35;
HXDLIN( 376)						bool _hx_tmp36;
HXDLIN( 376)						bool _hx_tmp37;
HXDLIN( 376)						if ((c >= 97)) {
HXLINE( 376)							_hx_tmp37 = (c <= 122);
            						}
            						else {
HXLINE( 376)							_hx_tmp37 = false;
            						}
HXDLIN( 376)						if (!(_hx_tmp37)) {
HXLINE( 376)							if ((c >= 65)) {
HXLINE( 376)								_hx_tmp36 = (c <= 90);
            							}
            							else {
HXLINE( 376)								_hx_tmp36 = false;
            							}
            						}
            						else {
HXLINE( 376)							_hx_tmp36 = true;
            						}
HXDLIN( 376)						if (!(_hx_tmp36)) {
HXLINE( 376)							if ((c >= 48)) {
HXLINE( 376)								_hx_tmp35 = (c <= 57);
            							}
            							else {
HXLINE( 376)								_hx_tmp35 = false;
            							}
            						}
            						else {
HXLINE( 376)							_hx_tmp35 = true;
            						}
HXDLIN( 376)						if (!(_hx_tmp35)) {
HXLINE( 376)							_hx_tmp34 = (c == 58);
            						}
            						else {
HXLINE( 376)							_hx_tmp34 = true;
            						}
HXDLIN( 376)						if (!(_hx_tmp34)) {
HXLINE( 376)							_hx_tmp33 = (c == 46);
            						}
            						else {
HXLINE( 376)							_hx_tmp33 = true;
            						}
HXDLIN( 376)						if (!(_hx_tmp33)) {
HXLINE( 376)							_hx_tmp32 = (c == 95);
            						}
            						else {
HXLINE( 376)							_hx_tmp32 = true;
            						}
HXDLIN( 376)						if (!(_hx_tmp32)) {
HXLINE( 376)							_hx_tmp31 = (c == 45);
            						}
            						else {
HXLINE( 376)							_hx_tmp31 = true;
            						}
HXDLIN( 376)						if (!(_hx_tmp31)) {
HXLINE( 376)							_hx_tmp30 = (c != 35);
            						}
            						else {
HXLINE( 376)							_hx_tmp30 = false;
            						}
HXDLIN( 376)						if (_hx_tmp30) {
HXLINE( 377)							if (strict) {
HXLINE( 378)								HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,(HX_("Invalid character in entity: ",24,85,11,30) + ::String::fromCharCode(c)),str,( (int)(p) ))));
            							}
HXLINE( 379)							{
HXLINE( 379)								if (::hx::IsNull( buf->charBuf )) {
HXLINE( 379)									buf->charBuf = ::Array_obj< char >::__new();
            								}
HXDLIN( 379)								buf->charBuf->push(38);
            							}
HXLINE( 380)							{
HXLINE( 380)								 ::Dynamic len5 = (( (int)(p) ) - start);
HXDLIN( 380)								if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 380)									buf->flush();
            								}
HXDLIN( 380)								if (::hx::IsNull( buf->b )) {
HXLINE( 380)									buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len5));
            								}
            								else {
HXLINE( 380)									::Array< ::String > buf9 = buf->b;
HXDLIN( 380)									buf9->push(str.substr(start,len5));
            								}
            							}
HXLINE( 381)							--p;
HXLINE( 382)							start = (( (int)(p) ) + 1);
HXLINE( 383)							state = escapeNext;
            						}
            					}
            				}
            				break;
            			}
HXLINE( 386)			++p;
            		}
HXLINE( 389)		if ((state == 1)) {
HXLINE( 390)			start = ( (int)(p) );
HXLINE( 391)			state = 13;
            		}
HXLINE( 394)		if ((state == 13)) {
HXLINE( 395)			if ((parent->nodeType == 0)) {
HXLINE( 396)				if ((parent->nodeType != ::Xml_obj::Element)) {
HXLINE( 396)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown((HX_("Bad node type, expected Element but found ",d8,90,8b,bb) + ::_Xml::XmlType_Impl__obj::toString(parent->nodeType))));
            				}
HXDLIN( 396)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,((HX_("Unclosed node <",79,04,e1,00) + parent->nodeName) + HX_(">",3e,00,00,00)),str,( (int)(p) ))));
            			}
HXLINE( 398)			if ((( (int)(p) ) != start)) {
HXLINE( 399)				 ::Dynamic len6 = (( (int)(p) ) - start);
HXDLIN( 399)				if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 399)					buf->flush();
            				}
HXDLIN( 399)				if (::hx::IsNull( buf->b )) {
HXLINE( 399)					buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len6));
            				}
            				else {
HXLINE( 399)					::Array< ::String > buf10 = buf->b;
HXDLIN( 399)					buf10->push(str.substr(start,len6));
            				}
            			}
HXLINE( 400)			::String str2 = buf->toString();
HXLINE( 401)			bool _hx_tmp38;
HXDLIN( 401)			if ((str2.length <= 0)) {
HXLINE( 401)				_hx_tmp38 = (nsubs == 0);
            			}
            			else {
HXLINE( 401)				_hx_tmp38 = true;
            			}
HXDLIN( 401)			if (_hx_tmp38) {
HXLINE( 402)				parent->addChild(::Xml_obj::createPCData(buf->toString()));
HXDLIN( 402)				++nsubs;
            			}
HXLINE( 404)			return ( (int)(p) );
            		}
HXLINE( 407)		bool _hx_tmp39;
HXDLIN( 407)		bool _hx_tmp40;
HXDLIN( 407)		if (!(strict)) {
HXLINE( 407)			_hx_tmp40 = (state == 18);
            		}
            		else {
HXLINE( 407)			_hx_tmp40 = false;
            		}
HXDLIN( 407)		if (_hx_tmp40) {
HXLINE( 407)			_hx_tmp39 = (escapeNext == 13);
            		}
            		else {
HXLINE( 407)			_hx_tmp39 = false;
            		}
HXDLIN( 407)		if (_hx_tmp39) {
HXLINE( 408)			{
HXLINE( 408)				if (::hx::IsNull( buf->charBuf )) {
HXLINE( 408)					buf->charBuf = ::Array_obj< char >::__new();
            				}
HXDLIN( 408)				buf->charBuf->push(38);
            			}
HXLINE( 409)			{
HXLINE( 409)				 ::Dynamic len7 = (( (int)(p) ) - start);
HXDLIN( 409)				if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 409)					buf->flush();
            				}
HXDLIN( 409)				if (::hx::IsNull( buf->b )) {
HXLINE( 409)					buf->b = ::Array_obj< ::String >::__new(1)->init(0,str.substr(start,len7));
            				}
            				else {
HXLINE( 409)					::Array< ::String > buf11 = buf->b;
HXDLIN( 409)					buf11->push(str.substr(start,len7));
            				}
            			}
HXLINE( 410)			{
HXLINE( 410)				parent->addChild(::Xml_obj::createPCData(buf->toString()));
HXDLIN( 410)				++nsubs;
            			}
HXLINE( 411)			return ( (int)(p) );
            		}
HXLINE( 414)		HX_STACK_DO_THROW(::haxe::Exception_obj::thrown( ::haxe::xml::XmlParserException_obj::__alloc( HX_CTX ,HX_("Unexpected end",2c,3e,ab,50),str,( (int)(p) ))));
HXDLIN( 414)		return 0;
            	}


::hx::Callable< int (::String,bool, ::Dynamic, ::Xml) > Parser_obj::doParse_dyn() { return _hx_alloc__Parser_objdoParse; }

bool Parser_obj::isValidChar(int c){
            	HX_STACKFRAME(&_hx_pos_71bfcf6fd7e2750c_418_isValidChar)
HXDLIN( 418)		bool _hx_tmp;
HXDLIN( 418)		bool _hx_tmp1;
HXDLIN( 418)		bool _hx_tmp2;
HXDLIN( 418)		bool _hx_tmp3;
HXDLIN( 418)		bool _hx_tmp4;
HXDLIN( 418)		bool _hx_tmp5;
HXDLIN( 418)		if ((c >= 97)) {
HXDLIN( 418)			_hx_tmp5 = (c <= 122);
            		}
            		else {
HXDLIN( 418)			_hx_tmp5 = false;
            		}
HXDLIN( 418)		if (!(_hx_tmp5)) {
HXDLIN( 418)			if ((c >= 65)) {
HXDLIN( 418)				_hx_tmp4 = (c <= 90);
            			}
            			else {
HXDLIN( 418)				_hx_tmp4 = false;
            			}
            		}
            		else {
HXDLIN( 418)			_hx_tmp4 = true;
            		}
HXDLIN( 418)		if (!(_hx_tmp4)) {
HXDLIN( 418)			if ((c >= 48)) {
HXDLIN( 418)				_hx_tmp3 = (c <= 57);
            			}
            			else {
HXDLIN( 418)				_hx_tmp3 = false;
            			}
            		}
            		else {
HXDLIN( 418)			_hx_tmp3 = true;
            		}
HXDLIN( 418)		if (!(_hx_tmp3)) {
HXDLIN( 418)			_hx_tmp2 = (c == 58);
            		}
            		else {
HXDLIN( 418)			_hx_tmp2 = true;
            		}
HXDLIN( 418)		if (!(_hx_tmp2)) {
HXDLIN( 418)			_hx_tmp1 = (c == 46);
            		}
            		else {
HXDLIN( 418)			_hx_tmp1 = true;
            		}
HXDLIN( 418)		if (!(_hx_tmp1)) {
HXDLIN( 418)			_hx_tmp = (c == 95);
            		}
            		else {
HXDLIN( 418)			_hx_tmp = true;
            		}
HXDLIN( 418)		return (_hx_tmp || (c == 45));
            	}


::hx::Callable< bool (int) > Parser_obj::isValidChar_dyn() { return _hx_alloc__Parser_objisValidChar; }

 ::haxe::ds::StringMap Parser_obj::escapes;


Parser_obj::Parser_obj()
{
}

bool Parser_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"parse") ) { outValue = parse_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"doParse") ) { outValue = doParse_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"escapes") ) { outValue = escapes; return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"isValidChar") ) { outValue = isValidChar_dyn(); return true; }
	}
	return false;
}

bool Parser_obj::__SetStatic(const ::String& inName, ::Dynamic& ioValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 7:
		if (HX_FIELD_EQ(inName,"escapes") ) { escapes = ioValue.Cast<  ::haxe::ds::StringMap >(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo* Parser_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo Parser_obj_sStaticStorageInfo[] = {
	{ ::hx::fsObject /*  ::haxe::ds::StringMap */ , (void*) &Parser_obj::escapes, HX_("escapes",d2,cd,20,a4) },
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static ::String* Parser_obj_sMemberFields = 0;

static void Parser_obj_sMarkStatics(HX_MARK_PARAMS) { 
	HX_MARK_MEMBER_NAME(Parser_obj::escapes, "escapes");
 };

#ifdef HXCPP_VISIT_ALLOCS
static void Parser_obj_sVisitStatics(HX_VISIT_PARAMS) { 
	HX_VISIT_MEMBER_NAME(Parser_obj::escapes, "escapes");
 };

#endif

::hx::Class Parser_obj::__mClass;

static ::String Parser_obj_sStaticFields[] = {
	HX_("parse",33,90,55,bd),
	HX_("doParse",a8,70,82,f0),
	HX_("isValidChar",a8,e4,15,0d),
	HX_("escapes",d2,cd,20,a4),
	::String(null())
};

void Parser_obj::__register()
{
	Parser_obj _hx_dummy;
	Parser_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.xml.Parser",fe,49,90,c4);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Parser_obj::__GetStatic;
	__mClass->mSetStaticField = &Parser_obj::__SetStatic;
	__mClass->mMarkFunc = Parser_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Parser_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Parser_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Parser_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Parser_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Parser_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Parser_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Parser_obj::__boot()
{
_hx_alloc__Parser_objparse = new (::hx::NewObjectType::NewObjConst) __Parser_objparse();

_hx_alloc__Parser_objdoParse = new (::hx::NewObjectType::NewObjConst) __Parser_objdoParse();

_hx_alloc__Parser_objisValidChar = new (::hx::NewObjectType::NewObjConst) __Parser_objisValidChar();

{
HX_BEGIN_LOCAL_FUNC_S0(::hx::AutoCallable_obj<  ::haxe::ds::StringMap() >, _hx_Closure_0)
            		 ::haxe::ds::StringMap HX_LOCAL_RUN(  ){
            			HX_GC_STACKFRAME(&_hx_pos_71bfcf6fd7e2750c_100_boot)
HXLINE( 101)			 ::haxe::ds::StringMap h =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 102)			h->set(HX_("lt",88,5e,00,00),HX_("<",3c,00,00,00));
HXLINE( 103)			h->set(HX_("gt",2d,5a,00,00),HX_(">",3e,00,00,00));
HXLINE( 104)			h->set(HX_("amp",04,fa,49,00),HX_("&",26,00,00,00));
HXLINE( 105)			h->set(HX_("quot",09,45,0a,4b),HX_("\"",22,00,00,00));
HXLINE( 106)			h->set(HX_("apos",d3,0f,73,40),HX_("'",27,00,00,00));
HXLINE( 107)			return h;
            		}
            		int __Compare(const ::hx::Object* inRhs) const override {
            			return dynamic_cast<const _hx_Closure_0*>(inRhs) ? 0 : -1;
            		}
            		std::type_index callableId() const override {
            			return std::type_index{ typeid(_hx_Closure_0) };
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_71bfcf6fd7e2750c_100_boot)
HXDLIN( 100)		::haxe::xml::Parser_obj::escapes = ::hx::Callable<  ::haxe::ds::StringMap() >(new _hx_Closure_0())();
            	}
}

} // end namespace haxe
} // end namespace xml
