package cs.system.reflection.emit;

/** Provides support for alternative ways to generate the Microsoft intermediate language (MSIL) and metadata for a dynamic method, including methods for creating tokens and for inserting the code, exception handling, and local variable signature blobs. */
@:native("System.Reflection.Emit.DynamicILInfo")
extern class DynamicILInfo {
	/**
	 * Gets the dynamic method whose body is generated by the current instance.
	 * @return A  object representing the dynamic method for which the current  object
	 * is generating code.
	 */
	var DynamicMethod(default, never):cs.system.reflection.emit.DynamicMethod;
	@:overload(function(signature:cs.NativeArray<cs.UInt8>):Int {})
	@:overload(function(method:cs.system.reflection.emit.DynamicMethod):Int {})
	@:overload(function(field:cs.system.RuntimeFieldHandle):Int {})
	@:overload(function(method:cs.system.RuntimeMethodHandle):Int {})
	@:overload(function(type:cs.system.RuntimeTypeHandle):Int {})
	@:overload(function(literal:String):Int {})
	@:overload(function(field:cs.system.RuntimeFieldHandle, contextType:cs.system.RuntimeTypeHandle):Int {})
	/**
	 * Gets a token, valid in the scope of the current , representing the signature for
	 * the associated dynamic method.
	 * @param signature An array that contains the signature.
	 * @return A token that can be embedded in the metadata and the MSIL stream for the
	 * associated dynamic method.
	 */
	function GetTokenFor(method:cs.system.RuntimeMethodHandle, contextType:cs.system.RuntimeTypeHandle):Int;
	@:overload(function(code:cs.NativeArray<cs.UInt8>, maxStackSize:Int):Void {})
	/**
	 * Sets the code body of the associated dynamic method.
	 * @param code A pointer to a byte array containing the MSIL stream.
	 * @param codeSize The number of bytes in the MSIL stream.
	 * @param maxStackSize The maximum number of items on the operand stack when the
	 * method is executing.
	 */
	function SetCode(code:cs.Pointer<cs.UInt8>, codeSize:Int, maxStackSize:Int):Void;
	@:overload(function(exceptions:cs.NativeArray<cs.UInt8>):Void {})
	/**
	 * Sets the exception metadata for the associated dynamic method.
	 * @param exceptions A pointer to a byte array containing the exception metadata.
	 * @param exceptionsSize The number of bytes of exception metadata.
	 */
	function SetExceptions(exceptions:cs.Pointer<cs.UInt8>, exceptionsSize:Int):Void;
	@:overload(function(localSignature:cs.NativeArray<cs.UInt8>):Void {})
	/**
	 * Sets the local variable signature that describes the layout of local variables
	 * for the associated dynamic method.
	 * @param localSignature An array that contains the layout of local variables for
	 * the associated .
	 * @param signatureSize The number of bytes in the signature.
	 */
	function SetLocalSignature(localSignature:cs.Pointer<cs.UInt8>, signatureSize:Int):Void;
}
